### PR TITLE
 afinet: don't disable checksum calculation with spoof-source'd UDP6

### LINKED ISSUE #3525: Invalid checksum of 0 in UDP6 packet when using spoof_source(yes)
Hello,

spoof_source(yes) works fine in IPv4. In IPv6, it does correctly spoof the source, but creates an invalid checksum 0 for the packet, and so it ends up being dropped by the receiver as invalid. If spoof_source(no) is used instead, then the IPv6 checksum is calculated correctly, and so the packet is correctly processed by the receiver.

I suspect the issue might be that this "temporary workaround" is no longer working:

https://github.com/syslog-ng/syslog-ng/blob/1a7cc761b6c61c4abd2bcfaea4c6af3be6d862cc/modules/afsocket/afinet-dest.c#L552

Very likely that workaround is not needed anymore because it was added 8 years ago.

### PR DESCRIPTION
**Pull request by alltilla**
The problem, we worked around, has been fixed in libnet 1.1.6, which is out in every major distro. The workaround can be safely removed.

Fixes #3525.
~NOTE: Internal testing is still in progress!~

Signed-off-by: Attila Szakacs <attila.szakacs@oneidentity.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by MrAnno — DISMISSED** [review]

**Comment by Kokan** [comment]
Adding min version with 1.1.6 might help people not bump into having older version and silently causing issues.

**Comment by alltilla** [comment]
@Kokan Totally valid thing to do. Unfortunately it is pretty hard to do in case of libnet.
 1. `libnet` does net have a `.pc` file, so `pkg-config` cannot help.
 2. `libnet` itself only has full string version definition in its header (`#define LIBNET_VERSION "1.1.6"`), so comparison is a pain...

The only solution I see is to do the painful comparison using `strtok()` and `atoi()`, not sure if it is worth it.

**Comment by Kokan** [comment]
Thanks for checking out possibilities. I hoped that at least `libnet-config` provides version number, well as I see upstream at least going to provide .`pc` file, so in future we may have a version number...
At least please include the min version change in the news entry, so in the release news file it can be highlighted.

Otherwise lgtm from me.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by Kokan — APPROVED** [review]

**Review by bazsi — APPROVED** [review]

**Pull request merged**
