### PR TITLE
improve db-parser() error messages on duplicate patterns

### PR DESCRIPTION
**Pull request by bazsi**
I have created these patches while looking into #3542, please don't merge until that is concluded.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
kira fails because it hard-codes the format pdbtool dump is using, which I've tried to change - for the better.

**Comment by MrAnno** [comment]
@kira-syslogng retest this please branch=pdbtool-dump-impr;

**Review by MrAnno — APPROVED** [review]

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by alltilla — APPROVED** [review]

**Pull request merged**
