### PR TITLE
version bump: 3.27

### PR DESCRIPTION
**Pull request by furiel**

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
A deb/rpm changelog version bump will be needed too in `packaging/debian/changelog` and `packaging/rhel/syslog-ng.spec`.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
These are edited automatically by the dbld scripts.

**Comment by MrAnno** [comment]
Oh okay, sorry.

**Comment by lbudai** [comment]
@bazsi : unfortunately that's not true... dbld tarball generation fails due to versioning...

**Pull request merged**
