### PR TITLE
extend travis build with arm64

### PR DESCRIPTION
**Pull request by Kokan**
Not Arm related change: replaces *gradle* fixed version with the latest.

Add basic build and Ut execution for amr64 platform.

Note: due to lack of Criterion arm64 package, this job builds Criterion locally. As it was relativly quick (~70 second) to build from zero and the overall job was not the slowest. I avoided adding Criterion build cache.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by Kokan** [comment]
UT execution now works but it required building criterion in this project. I plan to explore the possibilities to obtain criterion library for this distribution, platform. From which one option is to build here locally and possibly cache the build.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
btw, an alternative to this could be running docker images with qemu based arm64 emulation. that can even run your desktops and could easily be integrated with dbld.

and dbld already resolves the criterion issue (in a similar way to what you did now), e.g. it builds criterion within the image.

**Comment by Kokan** [comment]
@bazsi that is a possibility, though I only did this because Travis kinda provides me the same thing effortlessly. If Travis would provided like Haiku OS, I would went for that as well.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
