### PR TITLE
Afsql typing support (4.0)

### PR DESCRIPTION
**Pull request by bazsi**
This pull requests improves @vivinperis 's PR #3295 so that it integrates with the latest typing changes.

This only received limited testing at this point.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by OverOrion** [comment]
Nice catch @mitzkia!

---
I've fiddled around with it a bit and it seems that the trigger to the crash is the `default` keyword in `values`. The old `_free_valid_str_pointers` (in `string_list_free`) had a guards against it:
https://github.com/syslog-ng/syslog-ng/blob/master/lib/string-list.c#L85-L97

I think that a custom `_free_valid_sql_values` function with the same guard could be the solution.

**Comment by bazsi** [comment]
I have pushed a fix (and a test to exercise it)

**Review by OverOrion — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
