### PR TITLE
scl/fortigate: add parser for fortigate format

### PR DESCRIPTION
**Pull request by bazsi**
This depends on #3538 that allows me to parse a stray <PRI> value without going into further details in the message. 

Otherwise it contains fortigate-parser() and an application adapter for app-parser() to parse the same automatically.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by gaborznagy** [comment]
@bazsi I've just pushed some changes to make the CI green.

We would add a news entry to the PR, if it's okay to you.

**Review by gaborznagy — APPROVED** [review]
We'll add a news entry, nevertheless it looks good to me.

**Comment by bazsi** [comment]
I have some improvements, still, so don't merge it yet.

Thanks

**Comment by gaborznagy** [comment]
> I have some improvements, still, so don't merge it yet. Thanks

Sorry, I thought it's final.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
I have now incorporated a change to syslog-format that allows me to parse a stray <PRI> header without going into further details in the message. The presence of the PRI field is pretty consistent even for senders that otherwise completely disregard conventions or standards in syslog.

A similar use-case exists in cisco-parser() which has ignored the syslog priority until now, but I've added that change too.

Let me know if you want me to split  up this branch. There are basically three logical parts:
  - the addition of the "no-header" flag in syslog-format
  - the addition of the fortigate-parser() that utilizes this flag
  - the change in cisco-parser() that starts using no-header
  - the change in the cisco application adapter to have an explicit filter to improve app-parser() performance (instead of running all messages through cisco-parser())

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
kira fails because we now properly parse the syslog facility of cisco messages, which is local7, in contrast with the previous value of "user".

nevertheless, another update, as we can get rid of the set-severity() piece of the cisco parser.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
removed the cisco specific bits and moved them into #3537. adding a news file in the next round.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
I've removed the no-header bits too and moved them into #3538

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
@kira-syslogng rebuild this please.

**Comment by bazsi** [comment]
@kira-syslogng build this please;

**Comment by bazsi** [comment]
@kira-syslogng test this please;

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
This is now considered final, but we should merge #3538 first.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by gaborznagy — APPROVED** [review]

**Review by MrAnno — APPROVED** [review]

**Pull request merged**
