### PR TITLE
package-indexer: add script for indexing packages

### PR DESCRIPTION
**Pull request by alltilla**
This script can be used to index the `deb` packages generated by `dbld`.

With this PR we only add the code and some static analysis workflows in GitHub Actions, but not the actual indexing workflow.

Signed-off-by: Attila Szakacs <attila.szakacs@oneidentity.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by MrAnno — APPROVED** [review]

**Comment by gaborznagy** [comment]
@alltilla: can you add the packaging/package-indexer dir to the dist tarball, please?

Sorry, I just spotted this now.

**Comment by alltilla** [comment]
Sure I can, but do we want it in the tarball, though?

**Comment by MrAnno** [comment]
The GitHub actions jobs are not in the tarball either.
I thought this was intentional. My reasoning is that these are not useful inside the syslog-ng tarball.

GitHub Actions configs are used for package generation and testing in a dev environment that requires git anyway.
I think the same applies to the package indexer code: it can be used to publish syslog-ng packages in an APT repository, which is specific to our use-case with ose-repo.syslog-ng.com (azure/DO backend, nightly/stable, etc.).

**Comment by gaborznagy** [comment]
> The GitHub actions jobs are not in the tarball either. I thought this was intentional. My reasoning is that these are not useful inside the syslog-ng tarball.
> 
> GitHub Actions configs are used for package generation and testing in a dev environment that requires git anyway. I think the same applies to the package indexer code: it can be used to publish syslog-ng packages in an APT repository, but it is specific to our use-case with ose-repo.syslog-ng.com (azure/DO backend, nightly/stable, etc.).

Thank you for both of you for the reasoning. I'm convinced.
To be honest, I just thought that we should include scripts by default, I didn't think more into it, my bad.

**Review by gaborznagy — APPROVED** [review]

**Pull request merged**
