### PR TITLE
Fix the kira issue with the hyrule packages

### PR DESCRIPTION
**Pull request by kovgeri01**
Fixes the issue of unloadable python module in kira

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kovgeri01** [comment]
@kira-syslogng test this please;

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kovgeri01** [comment]
@kira-syslogng  test this please test branch=fix_outdated_require_statement_in_hyrule_test;

**Comment by kovgeri01** [comment]
The hyrule dependency changed  , the kira tests had to be modified, closing this issue

**Pull request closed without merging**
