### PR TITLE
sync with downstream Debian packaging

### PR DESCRIPTION
**Pull request by bazsi**
I am working towards a dbld that uses packaging information to fetch build depencies instead of manually maintained package lists in packages.manifest. As a first step, this branch syncs our /packaging/debian directory with downstream and adds locally maintained - upstream only - patches against that, to make debian packaging easier to maintain & align with the one found in the official Debian repositories.

Originally I intended to submit both debsync and my dbld build dependency related work, but that proved to be too large, so let me submit this first and then the other would follow.

This branch should NOT touch anything outside of /packaging/deban & build.manifest and should produce packages for all supported platforms, so it should be easy to merge.

A timely merge would be appreciated (once this is green), maintaining the debsync portion is a pain, as I get huge conflicts whenever our packaging/debian changes.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
build packages please

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by bazsi** [comment]
build packages please

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by bazsi** [comment]
@kira-syslogng build packages please

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
build packages please

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
build packages please

**Comment by kira-syslogng** [comment]
Package Build SUCCESS

Packages are available at https://ci.syslog-ng.com/jenkins/job/kira-dbld-pull-requests/634/artifact/

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
build packages please

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
build packages please

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
build packages please

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
build packages please.

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
build packages please

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
build packages please

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
build packages please.

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
build packages please.

**Comment by kira-syslogng** [comment]
Package Build SUCCESS

Packages are available at https://ci.syslog-ng.com/jenkins/job/kira-dbld-pull-requests/645/artifact/

**Comment by bazsi** [comment]
build packages please

**Comment by kira-syslogng** [comment]
Package Build SUCCESS

Packages are available at https://ci.syslog-ng.com/jenkins/job/kira-dbld-pull-requests/646/artifact/

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
