### PR TITLE
Prepare v3.28.1

### PR DESCRIPTION
**Pull request by MrAnno**
- [x] Fix TLS connection closure (source side) #2811 
- [x] NEWS file

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
@kira-syslogng build packages please

**Comment by kira-syslogng** [comment]
Package Build SUCCESS

Packages are available at https://ci.syslog-ng.com/jenkins/job/kira-dbld-pull-requests/689/artifact/

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by furiel** [comment]
Please remove the doc fragment too. We do not want to carry it to the next release (doc/doc-3301.md)

**Comment by alltilla** [comment]
NEWS file looks good to me.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by nbsd** [comment]
@MrAnno  @alltilla You forgot to include the new manual page secure-logging(7) in the packaging for RHEL and Debian. As this manual page is the main source of information about the secure logging module, it should be included in every package build from the 3.28.1 sources.
I would also propose to explicitly mention this new manual page in the NEWS file, as it can be regarded as the user manual for the secure logging module.

**Comment by lbudai** [comment]
> @MrAnno @alltilla You forgot to include the new manual page secure-logging(7) in the packaging for RHEL and Debian. As this manual page is the main source of information about the secure logging module, it should be included in every package build from the 3.28.1 sources.
> I would also propose to explicitly mention this new manual page in the NEWS file, as it can be regarded as the user manual for the secure logging module.

I'm going to open a new PR for that.

**Pull request merged**
