### PR TITLE
README: add discord badge instead of gitter

### PR DESCRIPTION
**Pull request by bazsi**

### CODE REVIEW

**Comment by alltilla** [comment]
Should we set `label=Discord` to show that it points to discord?
```
[![Discord](https://img.shields.io/discord/1082023686028148877?label=Discord)](https://discord.gg/qmq53uBm2c)
```
[Discord](https://discord.gg/qmq53uBm2c)

**Comment by alltilla** [comment]
[Optional]

Also setting a logo would be cool, too, IMO.

```
[![Discord](https://img.shields.io/discord/1082023686028148877?label=Discord&logo=discord&logoColor=white)](https://discord.gg/qmq53uBm2c)
```
[Discord](https://discord.gg/qmq53uBm2c)

**Review by alltilla — APPROVED** [review]

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
updated to your last suggestion with the logo :)

i'll merge once you re-approve.

**Review by alltilla — APPROVED** [review]

**Pull request merged**
