### PR TITLE
cmake: Added missing handling of ENABLE_TESTING option in cmake builds

### PR DESCRIPTION
**Pull request by HofiOne**
CMake builds did not fully respect the ENABLE_TESTING option

Signed-off-by: Hofi <hofione@gmail.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by HofiOne** [comment]
> CMake has its own option called `BUILD_TESTING`: https://cmake.org/cmake/help/latest/module/CTest.html
> 
> I think we should use that one instead of specifying our own.

Actually, this is not a new one, I just used the one that the automake version is using.
Do we really want to use a different option than the automake introduced one?

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by HofiOne** [comment]
> I think yes, we should use the option that the build system provides if there is one.

as you wish

**Review by MrAnno — APPROVED** [review]

**Comment by HofiOne** [comment]
thanks, https://github.com/syslog-ng/syslog-ng/pull/4474

**Pull request merged**
