### PR TITLE
Add support for Ubuntu 22.04 Jammy Jellyfish

### PR DESCRIPTION
**Pull request by OverOrion**
This PR extends the supported platforms in `dbld` with the latest Ubuntu LTS (22.04 Jammy Jellyfish).

### CODE REVIEW

**Comment by alltilla** [comment]
We might want to change the per PR dbld image build job to test jammy instead of focal:
```
packages.yml-    needs: create-source-tarball
packages.yml-    uses: ./.github/workflows/create-packages.yml
packages.yml-    with:
packages.yml-      source-tarball-artifact-name: source-tarball
packages.yml-      dbld-image-mode: cache
packages.yml-      distros: '[
packages.yml-        "centos-7",
packages.yml-        "debian-bullseye",
packages.yml-        "debian-testing",
packages.yml-        "fedora-35",
packages.yml:        "ubuntu-focal"
packages.yml-      ]'
```

**Comment by OverOrion** [comment]
Rebased against master, added fixup regarding @alltilla' note.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by alltilla — APPROVED** [review]

**Review by MrAnno — APPROVED** [review]
Thank you.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
