### PR TITLE
`http()`: templated `url()`

### PR DESCRIPTION
**Pull request by alltilla**
This PR does not implement generating metrics dynamically based on the resolution of the url, but we should do so in the future.

Signed-off-by: Attila Szakacs <attila.szakacs@axoflow.com>

### CODE REVIEW

**Comment by MrAnno** [comment]
We've discussed the security implications of this PR privately, I think a few points need to be addressed before merging thing.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by MrAnno** [comment]
I'll review this tomorrow! Thanks

**Comment by MrAnno** [comment]
I think this is still missing one step that we discussed with Bazsi: we should parse the beginning of the URL and we should not allow macros coming from message in the schema or the domain part of the URI (not even in escaped form). Note that the SCL use-case of the parameterized URL is different than the runtime unsafe templating feature. We agreed that we don't want to support templated schemas or domains at first, and even if we eventually wanted to do such things, we would mark it as unsafe with a special syntax.

Can you explain why "flushing on worker key change" is forced in this PR, please? (I originally thought this functionality depends solely on the needs of the actual destination.)

LGTM otherwise

**Comment by alltilla** [comment]
> Can you explain why "flushing on worker key change" is forced in this PR, please? (I originally thought this functionality depends solely on the needs of the actual destination.)

Regarding the http driver, I think the option is only useful for templated urls, and have no effect otherwise. I wanted to make it easier to set templates in urls, so I set it to yes by default for the http driver.

---

>  we should parse the beginning of the URL and we should not allow macros coming from message in the schema or the domain part of the URI (not even in escaped form).

Done

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Review by MrAnno — APPROVED** [review]
Thank you very much!

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Review by MrAnno — COMMENTED** [review]
LGTM.
There are some compat issues in Kira.

For example, `CURLU_ALLOW_SPACE` is available only from v7.78.0.

**Comment by alltilla** [comment]
Thanks for the review! I have updated the PR and I hope it works now :/

**Comment by alltilla** [comment]
Finally,  it seems like it works :) https://github.com/syslog-ng/syslog-ng/pull/4663/commits/344c54105ebe38d25f2c6bdbd3b6c839e02fd4b0 was needed for cmake.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Review by MrAnno — APPROVED** [review]

**Comment by MrAnno** [comment]
Thank you. I'll merge it in 10 minutes, I'll just try it once again :)

**Comment by MrAnno** [comment]
(`$` escaping doesn't work in the validation method, but I don't see a real use-case there)

**Pull request merged**
