### PR TITLE
Fix journald namespaces detection on centos-7

### PR DESCRIPTION
**Pull request by gaborznagy**
With older pkg-config versions (0.27.1 on centos-7) PKG_CONFIG_CHECK_MODULES() macro doesn't check the library's version on multiple calls (if they have the same prefix).
It seems to be that the macro is idempotent.

With version 0.29.1 it is allowed to call the macro multiple times with the same prefix.

See config.log on centos-7 with pkg-config  version 0.27.1, on the second call it simply returns true.
```
configure:18300: checking for libsystemd
configure:18307: $PKG_CONFIG --exists --print-errors "libsystemd >= ${LIBSYSTEMD_MIN_VERSION}"
configure:18310: $? = 0
configure:18324: $PKG_CONFIG --exists --print-errors "libsystemd >= ${LIBSYSTEMD_MIN_VERSION}"
configure:18327: $? = 0
configure:18365: result: yes
configure:18372: checking for libsystemd
configure:18437: result: yes
```

Alternatively, this could be solved without additional PKG_CHECK_MODULES() calls on libsystemd,
with calling $PKG_CONFIG --modversion directly if we detected libsystemd in the first place.

Fixes: #3418

### CODE REVIEW

**Comment by gaborznagy** [comment]
@kira-syslogng build packages please;

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by gaborznagy** [comment]
building systemd-journal works fine, but now python/editline fails :cry: :cry: :cry:

```
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-compress
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
Compiling /home/jenkins/rpmbuild/BUILDROOT/syslog-ng-3.29.1.77.g7f0f773-1+20200924T103720.x86_64/usr/lib64/syslog-ng/python/syslogng/debuggercli/editline.py ...
  File "/usr/lib64/syslog-ng/python/syslogng/debuggercli/editline.py", line 51
    def __init__(self, subeditor, completer, namespace: dict = None):
                                                      ^
SyntaxError: invalid syntax



RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.v8caJp (%install)
    Bad exit status from /var/tmp/rpm-tmp.v8caJp (%install)
dbld/rules:125: recipe for target 'package-centos-7' failed
make: *** [package-centos-7] Error 1
```

I'll try to find the reason.

**Comment by Kokan** [comment]
@gaborznagy Type hint is 3.5 feature: https://docs.python.org/3/library/typing.html
But during package build (rpm) tries to compile python to byte code not respecting python version and uses OS default: python2.

This failure is not due to your change, so I think after review this is okay to merge, and the above error should be fixed in a new PR.

**Comment by gaborznagy** [comment]
Thanks for the tip, I didn't dig into it yet. I've suspected some python2-python3 issue.

I'll push the fix here, if it's not merged until I found the best resolution to the problem.

**Comment by gaborznagy** [comment]
@kira-syslogng build packages please;

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Package Build SUCCESS

Packages are available at https://ci.syslog-ng.com/jenkins/job/kira-dbld-pull-requests/711/artifact/

**Comment by gaborznagy** [comment]
I've fixed the rpm building error, by simply removing the type-hints from debuggercli/editline.py, as they are python3 only (no [`__future__`](https://docs.python.org/2/library/__future__.html) for that.

I didn't want this solution, as pyeditline is only available on python3 and it would have been nicer to create some conditionals to only put editline.py into the tarball on python3, but this was faster and since only a partial of the code had type hints, it didn't seem a huge backward step.

**Review by Kokan — APPROVED** [review]

**Review by alltilla — APPROVED** [review]
Tested with `dbld/rules release`, it works now :)

**Pull request merged**
