### PR TITLE
light: use consistent naming

### PR DESCRIPTION
**Pull request by MrAnno**
This probably causes more problems than it solves, but I wanted to do it for a long time.

@mitzkia Let me know if you like it.

The PR replaces "pytest" and "python_functional" references in favor of Light.

> In computing, an early tradition in the hacker community (especially at MIT) was to choose acronyms and abbreviations that referred humorously to themselves or to other abbreviations.

Let me do the same here :)

Light: Light Is Great for High-quality Tests

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by mitzkia — DISMISSED** [review]
I like the idea very much, thanks for the changes.

**Comment by alltilla** [comment]
Please only merge this alongside our internal MR.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
I've resolved a conflict and added a few missing tests to EXTRA_DIST.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by mitzkia — DISMISSED** [review]
Thanks for the change. Approve

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by mitzkia — APPROVED** [review]
Approve

**Review by bazsi — APPROVED** [review]
I like this a lot better. Thanks.

**Pull request merged**
