### PR TITLE
lib/tlscontext.c: fix libressl build

### PR DESCRIPTION
**Pull request by ffontaine**
Fix the following build failure with libressl raised since version 3.37.1 and https://github.com/syslog-ng/syslog-ng/commit/c7ba645918480da06b9e065c62ebd630312b0c7f:

```
/nvmedata/autobuild/instance-5/output-1/host/lib/gcc/nios2-buildroot-linux-gnu/10.3.0/../../../../nios2-buildroot-linux-gnu/bin/ld: ./lib/.libs/libsyslog-ng.so: undefined reference to `SSL_CTX_set1_client_sigalgs_list'
/nvmedata/autobuild/instance-5/output-1/host/lib/gcc/nios2-buildroot-linux-gnu/10.3.0/../../../../nios2-buildroot-linux-gnu/bin/ld: ./lib/.libs/libsyslog-ng.so: undefined reference to `SSL_CTX_set1_sigalgs_list'
```

Fixes:
 - http://autobuild.buildroot.org/results/84cf9f6a0f6de831a685b73c42eab868952c8b15

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by MrAnno** [comment]
@kira-syslogng ok to test

**Comment by MrAnno** [comment]
Hi @ffontaine,

Thank you for opening this PR.

We don't support LibreSSL explicitly, but we could build our sigalg feature conditionally based on a function-check, for example:
https://github.com/syslog-ng/syslog-ng/blob/76a312818528af211c8014c42729f0767816ecf2/lib/tlscontext.c#L1085-L1095

In that case, we need to propagate the error back to our configuration language, so that we won't just silently ignore the option, but report an error:
https://github.com/syslog-ng/syslog-ng/blob/f5b61f50d9161409f8e3403bc41ec5fd4c3b2bbc/modules/afsocket/afsocket-grammar.ym#L901-L906

**Comment by ffontaine** [comment]
I updated the PR as requested.

**Comment by MrAnno** [comment]
@ffontaine Thank you. Looks good to me.

In case the sigalgs and client-sigalgs config options are not available due to building against libressl (or any other reasons), the user should be notified instead of ignoring their config options silently. That part (the `afsocket-grammar.ym` part above) would be important to implement in my opinion.

Let me know if you're interested in implementing it.
If not, I'll be happy to add the remaining part to your pull request so that we can merge it.

**Comment by ffontaine** [comment]
Thanks for your proposal, I'll let you implement the remaining part.

**Review by MrAnno — APPROVED** [review]

**Review by alltilla — APPROVED** [review]
Awesome, thanks for this!

**Pull request merged**
