### PR TITLE
cmake: Fixed some file permissions during installation

### PR DESCRIPTION
**Pull request by HofiOne**
Signed-off-by: Hofi <hofione@gmail.com>

### CODE REVIEW

**Review by MrAnno — COMMENTED** [review]
~Doesn't using `install(SCRIPT)` instead of `install(FILES)` fix your permission issues?~

Sorry, I misread the docs.
What permissions do these files have in the source directory in the build environment, where the install() command produces wrong permissions?

**Comment by MrAnno** [comment]
`configure_file()` defaults to `USE_SOURCE_PERMISSIONS`, so the exec perms should be there.

What permissions does `syslog-ng-update-virtualenv.in` have in your source dir?
Did you mount the source into a VM or emulator?

**Comment by HofiOne** [comment]
> `configure_file()` defaults to `USE_SOURCE_PERMISSIONS`, so the exec perms should be there.
> 
> What permissions does `syslog-ng-update-virtualenv.in` have in your source dir? Did you mount the source into a VM or emulator?
> 
> `x` is kept in my environment.
> 
> ```
> $ ls -al scripts/
> -rwx------ 1 anno users 2992 márc  29 13.55 syslog-ng-update-virtualenv.in*
> ```
> 
> ```
> $ ls -al _install/bin/
> ---x------ 1 anno users   3059 ápr   20 12.49 syslog-ng-update-virtualenv
> ```

full native build on macOS ARM macBook and x85 mac mini , no venv included here

probably this is a `configure_file()` bug of cmake, as it had no effect in various tried scenarios, also as `install()` was already used, therefore I stayed with `install()` that works nicely on the tried boxes



original result without this fix 

syslog-ng-update-virtualenv 
---x------

update-patterndb
-rw-r--r-



after the fix

syslog-ng-update-virtualenv 
-rwxr-xr-x

update-patterndb
-rwxr-xr-x


so, 
- update-patterndb had no execute bit set at all
- syslog-ng-update-virtualenv  had no other bit set than execute for the owner

**Review by MrAnno — CHANGES_REQUESTED** [review]
Please use `install(PROGRAMS)` without any additional permission parameters, instead of working around file permissions.

> The PROGRAMS form is identical to the FILES form except that the default permissions for the installed file also include OWNER_EXECUTE, GROUP_EXECUTE, and WORLD_EXECUTE.

**Review by MrAnno — APPROVED** [review]
Thanks.

**Pull request merged**
