### PR TITLE
LightFunctionalTests: Add new test cases for no-header flag

### PR DESCRIPTION
**Pull request by cs-benedek**
Signed-off-by: Benedek Cserhati <benedek.cserhati@balabit.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by cs-benedek** [comment]
@kira-syslogng test this please;

**Comment by cs-benedek** [comment]
@kira-syslog-ng ok to test;

**Comment by cs-benedek** [comment]
@kira-syslogng ok to test;

**Comment by cs-benedek** [comment]
@kira-syslogng ok to test;

**Comment by cs-benedek** [comment]
@kira-syslogng test this please;

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by cs-benedek** [comment]
@kira-syslogng test this please;

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by mitzkia** [comment]
@kira-syslogng test this please test branch=micek_syslog_start_verbose_log; test=functions/source-drivers/file-source-driver/multiple-lines/;

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by cs-benedek** [comment]
@kira-syslogng test this please test=functions/source-drivers/file-source-driver/multiple-lines/;

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by mitzkia — APPROVED** [review]
Approved

**Review by bazsi — APPROVED** [review]

**Review by MrAnno — APPROVED** [review]

**Pull request merged**
