### PR TITLE
Avoid using the deprecated GTimeVal type

### PR DESCRIPTION
**Pull request by bazsi**
While working with #4739 it turned out that the easy fix for that is to upgrade
GLIB_MIN_VERSION to 2.68.

But glib deprecated GTimeVal that is scattered around the code. This branch gets rid of GTimeVal but does not bump the glib min version to 2.68 as we will need to add further changes to be warning free on 2.68

no news needed

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
@kira-syslogng retest this please;

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Kira-stress-test: Build FAILURE

**Review by alltilla — APPROVED** [review]
Approve, but it would be nice to see the KIRA stress test results. It fails because of an environment error, I have written a message about it on the Discord.

**Pull request merged**
