### PR TITLE
Version: 3.38.1

### PR DESCRIPTION
**Pull request by kira-syslogng**
Tarball is available at: https://github.com/syslog-ng/syslog-ng/actions/runs/2862802990

### CODE REVIEW

**Comment by MrAnno** [comment]
@kira-syslogng do stresstest

**Comment by kira-syslogng** [comment]
Kira-stress-test: Build SUCCESS

**Review by alltilla — APPROVED** [review]
Solid release 💪

**Comment by kira-syslogng** [comment]
**Draft release** workflow started: https://github.com/syslog-ng/syslog-ng/actions/runs/2942900132.

**Comment by kira-syslogng** [comment]
**Draft release** workflow failed.

**Comment by kira-syslogng** [comment]
**Draft release** workflow failed.

**Comment by kira-syslogng** [comment]
**Draft release** workflow finished successfully. Please check the Releases page: https://github.com/syslog-ng/syslog-ng/releases

**Pull request merged**
