### PR TITLE
dbld: remove setuptools version freeze

### PR DESCRIPTION
**Pull request by alltilla**
funcparserlib v1.0.0 is released: https://github.com/vlasovskikh/funcparserlib/issues/65#issuecomment-1114668161
For more info, see: 661e546e820dfccf02813c5bfa5445c79c00efa0

Signed-off-by: Attila Szakacs <attila.szakacs@oneidentity.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by gaborznagy** [comment]
Don't we need a new image for testing this?

**Comment by MrAnno** [comment]
I think we do, as the devshell workflow uses the latest published dbld image.

**Comment by alltilla** [comment]
Originally the problem occurred, when building the image, but sure, a lot of code went in to setuptools since then, so it is worth to test it completely. I will test it manually tomorrow.

**Comment by OverOrion** [comment]
@alltilla 
If you are okay with it I am just about to test it on my fork :D

**Comment by OverOrion** [comment]
[Successful run](https://github.com/OverOrion/syslog-ng/actions/runs/2258433325)

**Review by OverOrion — APPROVED** [review]

**Pull request merged**
