### PR TITLE
.mailmap: add mailmap file to map commiters to their canonical email …

### PR DESCRIPTION
**Pull request by bazsi**
…address

To make git statistics reasonably correct.

Signed-off-by: Balazs Scheidler <bazsi77@gmail.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by alltilla** [comment]
Could you put `.mailmap` to `tests/copyright/policy` under the category `ignore`? The travis copyright check does not like it. Otherwise looks good to me! :)

**Comment by Kokan** [comment]
What should be the policy of extending the `.mailmap` file ? I am thinking like, how could we keep it up to date ? (if not, should we have it?) Can we really build a database of names and e-mail addresses without asking first ?

Also a teaser for such statistic tool would be nice to see.

**Comment by lbudai** [comment]
@Kokan : 

I think this PR is not about 'building a database from contributors'... especially that git already stores these mail addresses :) It is just a normalization attempt, I think. (you can see, I'm using three or four mail addresses when contributing).

please, also read
https://github.com/git/git/blob/master/Documentation/mailmap.txt

**Comment by Kokan** [comment]
@lbudai 
> I think this PR is not about 'building a database from contributors'

sure it is not intended, but it does that.

> specially that git already stores these mail addresses :) 

Yes, git stores thoese information, which is as far as I know is okay due to copyrights.

I am not against the change at all (no change request from me), I am just genuinely interested in those questions.

**Comment by bazsi** [comment]
On Fri, Sep 27, 2019, 09:27 Kókai Péter <notifications@github.com> wrote:

> What should be the policy of extending the .mailmap file ? I am thinking
> like, how could we keep it up to date ? (if not, should we have it?) Can we
> really build a database of names and e-mail addresses without asking first ?
>

Well, when we notice that someone is using multiple addresses and has a
material amount in the git history we can include her/him so that all her
contributions are filed properly.

Or we can accept PRs for this file and as long as someone is modifying her
own records I would just merge it without questions.

On the whole our aim should be that the same person is using a single
address, whatever that address might be.

I dont think we need to "maintain" it too much. I went through the history
and when I noticed multiple addresses I just added it to the file.

Also a teaser for such statistic tool would be nice to see.
>
I am using gitstats, but github also uses this information for its
"contributors" page.

**Comment by bazsi** [comment]
@kokan did I answer your concerns? Can we merge this? This isn't a code change after all.

**Comment by Kokan** [comment]
@bazsi  thanks, just installed *gitstats*, looks great. please fix the copyright check, and approve from my side.

**Comment by bazsi** [comment]
I just fixed the copyright file, so I hope travis agrees :)

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
