### PR TITLE
Update Criterion to v2.4.0

### PR DESCRIPTION
**Pull request by MrAnno**

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by gaborznagy** [comment]
Can we revert the 3d6baf4f47e2e59b48de5f08eecb2abaf726bc21 commit, please?

Criterion is once again in Debian testing (although it's a 2.4-0-rc version, see https://tracker.debian.org/pkg/criterion).

**Comment by MrAnno** [comment]
Done.

**Comment by MrAnno** [comment]
The macOS job detected a double-free in one of our tests. I've added a fix.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by MrAnno** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request closed without merging**
