### PR TITLE
stats-aggregator: refactor and realtime counters

### PR DESCRIPTION
**Pull request by alltilla**
These commits were part of #4565.

This set of patches breaks KIRA for some reason. I think they are functionally correct, and further investigation is needed whether the testcase should be adjusted or the code. I have separated these commits as they are not necessary for #4565, so we should not block that PR on this change.

Depends on #4565.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
I have now removed the realtime counter to see if that causes kira to break. I also folded in one followup fix within the branch to the base commit.

**Comment by bazsi** [comment]
@kira-syslogng test this please;

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
another attempt, revert stats-change-per-second timer to 60 seconds instead of 1.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by HofiOne** [comment]
based on the failing kira test case `functions/other-functions/statistics/016-stats-check-max-and-avg-and-eps-counters-after-source-became-orphaned-and-reseted.zts` I made the following tests

with this config
```
@version: 4.2

@include "scl.conf"

options {
	stats_level(5);
};

source s_network_2336b6a5db7544a4b686aa7cbf022f55 {
	network(ip("127.0.0.1")
 	port(10241));
};

destination d_file_49c93536e58642709e4bb80057c4a301 {
	file("c1a8897a-1e49-4065-a960-b153f9478df7.txt");
};

log {
	source(s_network_2336b6a5db7544a4b686aa7cbf022f55);
	destination(d_file_49c93536e58642709e4bb80057c4a301);

	flags(flow-control);
};
        
```

- I've started a syslog-ng instance built from that master and then one built from this PR branch
- sent messages 2 times, like
```
 build/install/bin/loggen -T -r 10000 -s 128 -n 60 -S 127.0.0.1 10241
 build/install/bin/loggen -T -r 10000 -s 128 -n 120 -S 127.0.0.1 10241
```
- made a stat in both cases
```
syslog-ng-ctl stats |sort > old.txt
syslog-ng-ctl stats |sort > new.txt

```
- made a diff out of the stats results, and the output is
```
diff old_s.txt new_s.txt
6,8c6,8
< dst.file;d_file_49c93536e58642709e4bb80057c4a301#0;c1a8897a-1e49-4065-a960-b153f9478df7.txt;a;eps_last_1h;0
< dst.file;d_file_49c93536e58642709e4bb80057c4a301#0;c1a8897a-1e49-4065-a960-b153f9478df7.txt;a;eps_last_24h;0
< dst.file;d_file_49c93536e58642709e4bb80057c4a301#0;c1a8897a-1e49-4065-a960-b153f9478df7.txt;a;eps_since_start;0
---
> dst.file;d_file_49c93536e58642709e4bb80057c4a301#0;c1a8897a-1e49-4065-a960-b153f9478df7.txt;a;eps_last_1h;3
> dst.file;d_file_49c93536e58642709e4bb80057c4a301#0;c1a8897a-1e49-4065-a960-b153f9478df7.txt;a;eps_last_24h;3
> dst.file;d_file_49c93536e58642709e4bb80057c4a301#0;c1a8897a-1e49-4065-a960-b153f9478df7.txt;a;eps_since_start;3
50c50
< src.host;;localhost;d;stamp;1691672203
---
> src.host;;localhost;d;stamp;1691672250
52,55c52,55
< src.host;s_network_2336b6a5db7544a4b686aa7cbf022f55#0;localhost;d;stamp;1691672203
< src.network;s_network_2336b6a5db7544a4b686aa7cbf022f55#0;tcp,127.0.0.1;a;eps_last_1h;16
< src.network;s_network_2336b6a5db7544a4b686aa7cbf022f55#0;tcp,127.0.0.1;a;eps_last_24h;16
< src.network;s_network_2336b6a5db7544a4b686aa7cbf022f55#0;tcp,127.0.0.1;a;eps_since_start;16
---
> src.host;s_network_2336b6a5db7544a4b686aa7cbf022f55#0;localhost;d;stamp;1691672250
> src.network;s_network_2336b6a5db7544a4b686aa7cbf022f55#0;tcp,127.0.0.1;a;eps_last_1h;3
> src.network;s_network_2336b6a5db7544a4b686aa7cbf022f55#0;tcp,127.0.0.1;a;eps_last_24h;3
> src.network;s_network_2336b6a5db7544a4b686aa7cbf022f55#0;tcp,127.0.0.1;a;eps_since_start;3
59,63c59,63
< src.network;s_network_2336b6a5db7544a4b686aa7cbf022f55#0;tcp,127.0.0.1;o;stamp;1691672203
< src.network;s_network_2336b6a5db7544a4b686aa7cbf022f55#0;tcp,AF_INET(127.0.0.1:54524);d;free_window;100
< src.network;s_network_2336b6a5db7544a4b686aa7cbf022f55#0;tcp,AF_INET(127.0.0.1:54524);d;full_window;100
< src.network;s_network_2336b6a5db7544a4b686aa7cbf022f55#0;tcp,AF_INET(127.0.0.1:54538);d;free_window;100
< src.network;s_network_2336b6a5db7544a4b686aa7cbf022f55#0;tcp,AF_INET(127.0.0.1:54538);d;full_window;100
---
> src.network;s_network_2336b6a5db7544a4b686aa7cbf022f55#0;tcp,127.0.0.1;o;stamp;1691672250
> src.network;s_network_2336b6a5db7544a4b686aa7cbf022f55#0;tcp,AF_INET(127.0.0.1:54552);d;free_window;100
> src.network;s_network_2336b6a5db7544a4b686aa7cbf022f55#0;tcp,AF_INET(127.0.0.1:54552);d;full_window;100
> src.network;s_network_2336b6a5db7544a4b686aa7cbf022f55#0;tcp,AF_INET(127.0.0.1:54572);d;free_window;100
> src.network;s_network_2336b6a5db7544a4b686aa7cbf022f55#0;tcp,AF_INET(127.0.0.1:54572);d;full_window;100
66c66
< src.program;;prg00000;d;stamp;1691672203
---
> src.program;;prg00000;d;stamp;1691672250
68c68
< src.sender;;localhost;d;stamp;1691672203
---
> src.sender;;localhost;d;stamp;1691672250
70c70
< src.sender;s_network_2336b6a5db7544a4b686aa7cbf022f55#0;localhost;d;stamp;1691672203
---
> src.sender;s_network_2336b6a5db7544a4b686aa7cbf022f55#0;localhost;d;stamp;1691672250
```
it seems there are really differences in the `eps_` counters so the tests are failing for a good reason I guess

**Comment by bazsi** [comment]
Thanks, will check this.

One question: Does the test case contain specific numbers on the eps values, or it has a range it accepts?

**Comment by bazsi** [comment]
The difference in the counters may happen as the timer has been synchronized globally, whereas now it has its dedicated timer, which means their starting point may differ.  

Does the test wait some time before querying the stats? If yes, how much? the EPS counters are calculated once every minute (which is probably a bit too rare)

I am suspecting the test is too close to the implementation. But I'll still check the difference with the above case in mind.

Btw: the old version reports 0 eps for the file destination and 16 for the source, while the new version reports 3 eps for both the source and the destination, which is easier to explain, as there's only one source feeding the only destination.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
I've found the two issues that caused kira to break, so let's hope this gets green now.

**Review by alltilla — COMMENTED** [review]
Approve from me.

**Review by bazsi — APPROVED** [review]

**Comment by bazsi** [comment]
Based on the approve by @alltilla I am approving this.

**Pull request merged**
