### PR TITLE
Dbld fedora 32 support

### LINKED ISSUE #3314: Fedora 30 is End Of Life
Fedora 30 is End Of Life since last week. Attached you can find a patch, which changes DBLD to build for Fedora 32 instead of Fedora 30. It should work for almost a year from now.
[f30to32.txt](https://github.com/syslog-ng/syslog-ng/files/4722305/f30to32.txt)

### PR DESCRIPTION
**Pull request by bazsi**
pulled in from a patch by @czanik 

Fixes #3314

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by gaborznagy** [comment]
Do we want to run a kira-packages job on this?

**Comment by lbudai** [comment]
> Do we want to run a kira-packages job on this?

fedora-32 hasn't been added yet to that job (I'm modifying it just now - as eoan should be removed, too)

**Comment by lbudai** [comment]
build packages please.

**Comment by kira-syslogng** [comment]
Package Build SUCCESS

Packages are available at https://ci.syslog-ng.com/jenkins/job/kira-dbld-pull-requests/685/artifact/

**Pull request merged**
