### PR TITLE
#3366 : Added optionality for libexamples module

### PR DESCRIPTION
**Pull request by AryanSharma9917**

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Review by MrAnno — CHANGES_REQUESTED** [review]
Please add a configure check similar to this one:
https://github.com/syslog-ng/syslog-ng/blob/3611f13a82842ac84668a4a049bbd16f457b5fe2/configure.ac#L288-L290

**Comment by AryanSharma9917** [comment]
@MrAnno sir configuration for the libexample module has been added and I have sent the pr

**Pull request closed without merging**
