### PR TITLE
Version: 4.0.1

### PR DESCRIPTION
**Pull request by kira-syslogng**
Tarball is available at: https://github.com/syslog-ng/syslog-ng/actions/runs/3751843430

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Review by MrAnno — DISMISSED** [review]

**Review by bazsi — APPROVED** [review]

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
**Draft release** workflow started: https://github.com/syslog-ng/syslog-ng/actions/runs/3752504871.

**Comment by kira-syslogng** [comment]
**Draft release** workflow finished successfully. Please check the Releases page: https://github.com/syslog-ng/syslog-ng/releases

**Pull request merged**
