### PR TITLE
Version: 3.30.1

### PR DESCRIPTION
**Pull request by kira-syslogng**
Tarball is available at: https://github.com/syslog-ng/syslog-ng/actions/runs/359678060

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by gaborznagy — APPROVED** [review]

**Comment by gaborznagy** [comment]
> 
> 
> There are new commits ([18cc6b1](https://github.com/syslog-ng/syslog-ng/commit/18cc6b14e50599ac2daf162bebd64c09c58e4830)) on master. Please follow-up any necessary changes.

I forgot during the review, but I think we should advertise the sanitizer support with autotools. Maybe a developer notes section?
I'll push it to this branch, if you approve the idea.

**Comment by lbudai** [comment]
Artifact is 10 times bigger than in previous releases (58MB).
Debian directory contains binaries - it shouldn't.

**Comment by lbudai** [comment]
-> #3486

**Comment by alltilla** [comment]
It seems like GitHub Actions's `set-env` was removed not so long ago... There is a PR, which intends to use the new API: #3484

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by lbudai** [comment]
> It seems like GitHub Actions's `set-env` was removed not so long ago... There is a PR, which intends to use the new API: #3484

hmm..hmm...

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by lbudai — APPROVED** [review]

**Pull request merged**
