### PR TITLE
csv-scanner: fix strip-whitespace and null-value() handling for the g…

### LINKED ISSUE #4027: csv-parser(flags(strip-whitespace)) ignore "strip-whitespace"
# syslog-ng
## Version of syslog-ng
syslog-ng 3 (3.30.1)
Config version: 3.29
Installer-Version: 3.30.1

## Platform
alpine 3.15

I want to read the log myself. But I also want to parse the log. That's why I use JSON.
```
# input:
LOG:  starting PostgreSQL 14.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit

# code:
parser {
	csv-parser(columns("PGSEVERITY", "PGMSG"), delimiters(":"), flags(strip-whitespace, greedy));
};
rewrite {
	set('$(format-json d="${R_ISODATE}" zlm="${PGSEVERITY}" m="${PGMSG}")', value("MESSAGE"));
};

# output:
{"zlm":"LOG","m":"  starting PostgreSQL 14.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit","d":"2022-05-26T10:33:37+03:00"}
```
Spaces in `"  starting`

`csv-parser(flags(strip-whitespace))` ignore `strip-whitespace`

### PR DESCRIPTION
**Pull request by bazsi**
Fixes #4027

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by MrAnno — DISMISSED** [review]

**Comment by Kokan** [comment]
@bazsi please fix the style check for C code, otherwise it is approve from my side.

**Review by Kokan — APPROVED** [review]

**Comment by MrAnno** [comment]
I've fixed the mentioned minor stylistic issue.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by alltilla — APPROVED** [review]

**Pull request merged**
