### PR TITLE
disk-buffer: added alternative option names

### PR DESCRIPTION
**Pull request by alltilla**
`disk-buf-size()` -> `capacity-bytes()`
`qout-size()` -> `front-cache-size()`
`mem-buf-length()` -> `flow-control-window-size()`
`mem-buf-size()` -> `flow-control-window-bytes()`

Old option names are still available.

Example configs:
```
tcp(
  "127.0.0.1" port(2001)
  disk-buffer(
    reliable(yes)
    capacity-bytes(1GiB)
    flow-control-window-bytes(200MiB)
    front-cache-size(1000)
  )
);

tcp(
  "127.0.0.1" port(2001)
  disk-buffer(
    reliable(no)
    capacity-bytes(1GiB)
    flow-control-window-size(10000)
    front-cache-size(1000)
  )
);
```

Signed-off-by: Attila Szakacs <attila.szakacs@axoflow.com>

### CODE REVIEW

**Comment by bazsi** [comment]
Don't we want to change the keyword defines to have the new names and the old names to alias with the new ones?

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by MrAnno** [comment]
@kira-syslogng do stresstest

**Comment by kira-syslogng** [comment]
Kira-stress-test: Build SUCCESS

**Review by MrAnno — APPROVED** [review]

**Comment by alltilla** [comment]
@kira-syslogng retest this please

**Pull request merged**
