### PR TITLE
db-parser: add more detail to db-parser() log messages

### PR DESCRIPTION
**Pull request by bazsi**
Signed-off-by: Balazs Scheidler <bazsi77@gmail.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
@kira-syslogng fails because one of the log messages it tests on has changed to include more information.

This is the testcase: syslog-ng-pe-testdb/functions/other-functions/patterndb/004-patterndb-no-xml-when-reload.zts

That message now includes filename a db-parser() location information. @mitzkia can you please help in fixing that testcase?

thanks

**Review by MrAnno — APPROVED** [review]

**Review by Kokan — APPROVED** [review]

**Comment by MrAnno** [comment]
@kira-syslogng test this please test branch=dbparser-log-messages-improvement;

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
