### PR TITLE
Version: 4.4.0

### PR DESCRIPTION
**Pull request by kira-syslogng**
Tarball is available at: https://github.com/syslog-ng/syslog-ng/actions/runs/6239263124

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Review by MrAnno — APPROVED** [review]

**Comment by kira-syslogng** [comment]
**Draft release** workflow started: https://github.com/syslog-ng/syslog-ng/actions/runs/6298526644.

**Comment by kira-syslogng** [comment]
**Draft release** workflow failed.

**Pull request merged**
