### PR TITLE
Fix some compiler warnings

### PR DESCRIPTION
**Pull request by alltilla**

### CODE REVIEW

**Comment by alltilla** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build FAILURE

**Review by OverOrion — DISMISSED** [review]
LGTM, thank for the quick fix, let's wait for Kira's 2nd run.

**Review by OverOrion — APPROVED** [review]

**Comment by kira-syslogng** [comment]
Build FAILURE

**Pull request merged**
