### PR TITLE
doc: replaced obsolete admin guide links 

### PR DESCRIPTION
**Pull request by Muhammad-Shanif**
The previous link pointed to a website which did not have any "Administrator Guide". Replaced it with an updated link.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by bazsi** [comment]
please fix the commit summary so the CI does not fail https://github.com/syslog-ng/syslog-ng/actions/runs/4461396583/jobs/7836715962?pr=4375

thanks

**Comment by bazsi** [comment]
@Muhammad-Shanif would you please edit the commit summary so it meets the the guidelines as described here: https://github.com/syslog-ng/syslog-ng/blob/master/CONTRIBUTING.md#commit-messages

You can simply amend your commit using git gui or do an interactive rebase (git rebase -i master) and use the "r" command to reword the commit summary.

Otherwise this commit looks good.

**Review by MrAnno — APPROVED** [review]
Thanks for your PR.
Unfortunately, no admin guide is available for syslog-ng 4.1. A few invalid links have been replaced with the v3.37 guide's URL. I think that's better than having a broken link.

**Pull request merged**
