### PR TITLE
java/gradle: replace deprecated options in gradle 7

### PR DESCRIPTION
**Pull request by Kokan**
Details: https://docs.gradle.org/6.8.3/userguide/java_library_plugin.html#sec:java_library_configurations_graph

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by lbudai — DISMISSED** [review]

**Review by MrAnno — COMMENTED** [review]
Should we bump `GRADLE_MIN_VERSION="2.2"` with this change?

`implementation` seems to be a `>v3` keyword.
https://docs.gradle.org/3.4/release-notes.html

**Comment by Kokan** [comment]
Sure, bumped to 3.4 as min version.

**Review by MrAnno — APPROVED** [review]
Thank you.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by gaborznagy — APPROVED** [review]

**Pull request merged**
