### PR TITLE
Clang c++ compilation fixes

### PR DESCRIPTION
**Pull request by bazsi**
Let's see if this fixes 

https://github.com/syslog-ng/syslog-ng/issues/4652

### CODE REVIEW

**Comment by czanik** [comment]
FreeBSD CLANG fails:
```
mv -f ./modules/grpc/protos/google-proto/google/rpc/.deps/modules_grpc_protos_libgrpc_protos_la-status.pb.Tpo ./modules/grpc/protos/google-proto/google/rpc/.deps/modules_grpc_protos_libgrpc_protos_la-status.pb.Plo
/bin/sh ./libtool  --tag=CXX   --mode=link c++ -Wshadow -Wno-stack-protector -Wno-unused-parameter -Wno-variadic-macros   -I/usr/local/include -Wno-float-conversion -Wno-implicit-float-conversion -Wno-implicit-int-float-conversion -Wno-unknown-warning-option -DNOMINMAX -pthread -I./modules/grpc/protos/googleapis-proto -I./modules/grpc/protos/google-proto -I./modules/grpc/protos/opentelemetry-proto -I./modules/grpc/protos/otlp -I./modules/grpc/protos/grafana-loki -I./modules/grpc/protos/loki  -O2 -g -O2 -pipe -fstack-protector-strong -fno-strict-aliasing   -fstack-protector-strong  -o modules/grpc/protos/libgrpc-protos.la -rpath /usr/local/lib ./modules/grpc/protos/otlp/opentelemetry/proto/collector/logs/v1/modules_grpc_protos_libgrpc_protos_la-logs_service.grpc.pb.lo ./modules/grpc/protos/otlp/opentelemetry/proto/collector/logs/v1/modules_grpc_protos_libgrpc_protos_la-logs_service.pb.lo ./modules/grpc/protos/otlp/opentelemetry/proto/collector/metrics/v1/modules_grpc_protos_libgrpc_protos_la-metrics_service.grpc.pb.lo ./modules/grpc/protos/otlp/opentelemetry/proto/collector/metrics/v1/modules_grpc_protos_libgrpc_protos_la-metrics_service.pb.lo ./modules/grpc/protos/otlp/opentelemetry/proto/collector/trace/v1/modules_grpc_protos_libgrpc_protos_la-trace_service.grpc.pb.lo ./modules/grpc/protos/otlp/opentelemetry/proto/collector/trace/v1/modules_grpc_protos_libgrpc_protos_la-trace_service.pb.lo ./modules/grpc/protos/otlp/opentelemetry/proto/common/v1/modules_grpc_protos_libgrpc_protos_la-common.pb.lo ./modules/grpc/protos/otlp/opentelemetry/proto/logs/v1/modules_grpc_protos_libgrpc_protos_la-logs.pb.lo ./modules/grpc/protos/otlp/opentelemetry/proto/metrics/v1/modules_grpc_protos_libgrpc_protos_la-metrics.pb.lo ./modules/grpc/protos/otlp/opentelemetry/proto/resource/v1/modules_grpc_protos_libgrpc_protos_la-resource.pb.lo ./modules/grpc/protos/otlp/opentelemetry/proto/trace/v1/modules_grpc_protos_libgrpc_protos_la-trace.pb.lo ./modules/grpc/protos/loki/modules_grpc_protos_libgrpc_protos_la-push.grpc.pb.lo ./modules/grpc/protos/loki/modules_grpc_protos_libgrpc_protos_la-push.pb.lo ./modules/grpc/protos/google-proto/google/api/modules_grpc_protos_libgrpc_protos_la-annotations.pb.lo ./modules/grpc/protos/google-proto/google/api/modules_grpc_protos_libgrpc_protos_la-client.pb.lo ./modules/grpc/protos/google-proto/google/api/modules_grpc_protos_libgrpc_protos_la-field_behavior.pb.lo ./modules/grpc/protos/google-proto/google/api/modules_grpc_protos_libgrpc_protos_la-http.pb.lo ./modules/grpc/protos/google-proto/google/api/modules_grpc_protos_libgrpc_protos_la-launch_stage.pb.lo ./modules/grpc/protos/google-proto/google/api/modules_grpc_protos_libgrpc_protos_la-resource.pb.lo ./modules/grpc/protos/google-proto/google/cloud/bigquery/storage/v1/modules_grpc_protos_libgrpc_protos_la-annotations.pb.lo ./modules/grpc/protos/google-proto/google/cloud/bigquery/storage/v1/modules_grpc_protos_libgrpc_protos_la-arrow.pb.lo ./modules/grpc/protos/google-proto/google/cloud/bigquery/storage/v1/modules_grpc_protos_libgrpc_protos_la-avro.pb.lo ./modules/grpc/protos/google-proto/google/cloud/bigquery/storage/v1/modules_grpc_protos_libgrpc_protos_la-protobuf.pb.lo ./modules/grpc/protos/google-proto/google/cloud/bigquery/storage/v1/modules_grpc_protos_libgrpc_protos_la-storage.grpc.pb.lo ./modules/grpc/protos/google-proto/google/cloud/bigquery/storage/v1/modules_grpc_protos_libgrpc_protos_la-storage.pb.lo ./modules/grpc/protos/google-proto/google/cloud/bigquery/storage/v1/modules_grpc_protos_libgrpc_protos_la-stream.pb.lo ./modules/grpc/protos/google-proto/google/cloud/bigquery/storage/v1/modules_grpc_protos_libgrpc_protos_la-table.pb.lo ./modules/grpc/protos/google-proto/google/rpc/modules_grpc_protos_libgrpc_protos_la-status.pb.lo ./lib/libsyslog-ng.la -L/usr/local/lib -lprotobuf -L/usr/local/lib -lgrpc++ -lgrpc -lgpr -labsl_spinlock_wait -labsl_crc32c -labsl_crc_internal -labsl_crc_cpu_detect -labsl_strings_internal -labsl_cordz_functions -labsl_cordz_handle -labsl_graphcycles_internal -labsl_civil_time -labsl_time_zone -labsl_debugging_internal -labsl_demangle_internal -labsl_malloc_internal -labsl_cord_internal -labsl_cordz_info -labsl_crc_cord_state -labsl_bad_optional_access -labsl_flags_program_name -labsl_flags_internal -labsl_log_severity -labsl_str_format_internal -labsl_flags_reflection -labsl_flags_private_handle_accessor -labsl_flags_commandlineflag -labsl_flags_commandlineflag_internal -labsl_flags_config -labsl_city -labsl_bad_variant_access -labsl_low_level_hash -labsl_hashtablez_sampler -labsl_exponential_biased -labsl_throw_delegate -labsl_random_distributions -labsl_random_internal_randen_hwaes -labsl_random_internal_randen_hwaes_impl -labsl_random_internal_randen_slow -labsl_random_internal_platform -labsl_int128 -labsl_random_internal_randen -labsl_random_seed_sequences -labsl_random_internal_pool_urbg -labsl_random_internal_seed_material -labsl_random_seed_gen_exception /usr/lib/libexecinfo.so -labsl_stacktrace -labsl_strerror -labsl_symbolize -labsl_raw_hash_set -labsl_raw_logging_internal -lrt -labsl_base -labsl_cord -labsl_flags -labsl_flags_marshalling -labsl_hash -labsl_status -labsl_statusor -labsl_strings -labsl_synchronization -labsl_time -lstdc++ 
libtool: link: c++  -fPIC -DPIC -shared -nostdlib /usr/lib/crti.o /usr/lib/crtbeginS.o  ./modules/grpc/protos/otlp/opentelemetry/proto/collector/logs/v1/.libs/modules_grpc_protos_libgrpc_protos_la-logs_service.grpc.pb.o ./modules/grpc/protos/otlp/opentelemetry/proto/collector/logs/v1/.libs/modules_grpc_protos_libgrpc_protos_la-logs_service.pb.o ./modules/grpc/protos/otlp/opentelemetry/proto/collector/metrics/v1/.libs/modules_grpc_protos_libgrpc_protos_la-metrics_service.grpc.pb.o ./modules/grpc/protos/otlp/opentelemetry/proto/collector/metrics/v1/.libs/modules_grpc_protos_libgrpc_protos_la-metrics_service.pb.o ./modules/grpc/protos/otlp/opentelemetry/proto/collector/trace/v1/.libs/modules_grpc_protos_libgrpc_protos_la-trace_service.grpc.pb.o ./modules/grpc/protos/otlp/opentelemetry/proto/collector/trace/v1/.libs/modules_grpc_protos_libgrpc_protos_la-trace_service.pb.o ./modules/grpc/protos/otlp/opentelemetry/proto/common/v1/.libs/modules_grpc_protos_libgrpc_protos_la-common.pb.o ./modules/grpc/protos/otlp/opentelemetry/proto/logs/v1/.libs/modules_grpc_protos_libgrpc_protos_la-logs.pb.o ./modules/grpc/protos/otlp/opentelemetry/proto/metrics/v1/.libs/modules_grpc_protos_libgrpc_protos_la-metrics.pb.o ./modules/grpc/protos/otlp/opentelemetry/proto/resource/v1/.libs/modules_grpc_protos_libgrpc_protos_la-resource.pb.o ./modules/grpc/protos/otlp/opentelemetry/proto/trace/v1/.libs/modules_grpc_protos_libgrpc_protos_la-trace.pb.o ./modules/grpc/protos/loki/.libs/modules_grpc_protos_libgrpc_protos_la-push.grpc.pb.o ./modules/grpc/protos/loki/.libs/modules_grpc_protos_libgrpc_protos_la-push.pb.o ./modules/grpc/protos/google-proto/google/api/.libs/modules_grpc_protos_libgrpc_protos_la-annotations.pb.o ./modules/grpc/protos/google-proto/google/api/.libs/modules_grpc_protos_libgrpc_protos_la-client.pb.o ./modules/grpc/protos/google-proto/google/api/.libs/modules_grpc_protos_libgrpc_protos_la-field_behavior.pb.o ./modules/grpc/protos/google-proto/google/api/.libs/modules_grpc_protos_libgrpc_protos_la-http.pb.o ./modules/grpc/protos/google-proto/google/api/.libs/modules_grpc_protos_libgrpc_protos_la-launch_stage.pb.o ./modules/grpc/protos/google-proto/google/api/.libs/modules_grpc_protos_libgrpc_protos_la-resource.pb.o ./modules/grpc/protos/google-proto/google/cloud/bigquery/storage/v1/.libs/modules_grpc_protos_libgrpc_protos_la-annotations.pb.o ./modules/grpc/protos/google-proto/google/cloud/bigquery/storage/v1/.libs/modules_grpc_protos_libgrpc_protos_la-arrow.pb.o ./modules/grpc/protos/google-proto/google/cloud/bigquery/storage/v1/.libs/modules_grpc_protos_libgrpc_protos_la-avro.pb.o ./modules/grpc/protos/google-proto/google/cloud/bigquery/storage/v1/.libs/modules_grpc_protos_libgrpc_protos_la-protobuf.pb.o ./modules/grpc/protos/google-proto/google/cloud/bigquery/storage/v1/.libs/modules_grpc_protos_libgrpc_protos_la-storage.grpc.pb.o ./modules/grpc/protos/google-proto/google/cloud/bigquery/storage/v1/.libs/modules_grpc_protos_libgrpc_protos_la-storage.pb.o ./modules/grpc/protos/google-proto/google/cloud/bigquery/storage/v1/.libs/modules_grpc_protos_libgrpc_protos_la-stream.pb.o ./modules/grpc/protos/google-proto/google/cloud/bigquery/storage/v1/.libs/modules_grpc_protos_libgrpc_protos_la-table.pb.o ./modules/grpc/protos/google-proto/google/rpc/.libs/modules_grpc_protos_libgrpc_protos_la-status.pb.o   -Wl,-rpath -Wl,/root/syslog-ng-grpc/work/syslog-ng-4.5.0.48.gad9c376/lib/.libs -Wl,-rpath -Wl,/usr/local/lib ./lib/.libs/libsyslog-ng.so -L/usr/local/lib -lprotobuf -lgrpc++ -lgrpc -lgpr -labsl_spinlock_wait -labsl_crc32c -labsl_crc_internal -labsl_crc_cpu_detect -labsl_strings_internal -labsl_cordz_functions -labsl_cordz_handle -labsl_graphcycles_internal -labsl_civil_time -labsl_time_zone -labsl_debugging_internal -labsl_demangle_internal -labsl_malloc_internal -labsl_cord_internal -labsl_cordz_info -labsl_crc_cord_state -labsl_bad_optional_access -labsl_flags_program_name -labsl_flags_internal -labsl_log_severity -labsl_str_format_internal -labsl_flags_reflection -labsl_flags_private_handle_accessor -labsl_flags_commandlineflag -labsl_flags_commandlineflag_internal -labsl_flags_config -labsl_city -labsl_bad_variant_access -labsl_low_level_hash -labsl_hashtablez_sampler -labsl_exponential_biased -labsl_throw_delegate -labsl_random_distributions -labsl_random_internal_randen_hwaes -labsl_random_internal_randen_hwaes_impl -labsl_random_internal_randen_slow -labsl_random_internal_platform -labsl_int128 -labsl_random_internal_randen -labsl_random_seed_sequences -labsl_random_internal_pool_urbg -labsl_random_internal_seed_material -labsl_random_seed_gen_exception -labsl_stacktrace -labsl_strerror -labsl_symbolize -labsl_raw_hash_set -labsl_raw_logging_internal -lrt -labsl_base -labsl_cord -labsl_flags -labsl_flags_marshalling -labsl_hash -labsl_status -labsl_statusor -labsl_strings -labsl_synchronization -labsl_time -lstdc++ -L/usr/lib -lc++ -lm -lc -lgcc -lgcc_s /usr/lib/crtendS.o /usr/lib/crtn.o  -O2 -g -O2 -fstack-protector-strong -fstack-protector-strong   -pthread -Wl,-soname -Wl,libgrpc-protos.so.0 -o modules/grpc/protos/.libs/libgrpc-protos.so.0.0.0
c++: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
ld: error: unable to find library -lstdc++
c++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[4]: *** [Makefile:14900: modules/grpc/protos/libgrpc-protos.la] Error 1
gmake[3]: *** [Makefile:28768: all-recursive] Error 1
gmake[2]: *** [Makefile:12404: all] Error 2
gmake[2]: Leaving directory '/root/syslog-ng-grpc/work/syslog-ng-4.5.0.48.gad9c376'
*** Error code 1
```
Most likely because it has c++, but no libstdc++, according to the output of ```find```.

Next up: trying gcc on FreeBSD again.

**Comment by czanik** [comment]
Using GCC it compiles, but some modules fail to load:
```
root@fb132:~/syslog-ng-grpc # syslog-ng -V
syslog-ng 4 (4.5.0.48.gad9c376)
Config version: 4.2
Installer-Version: 4.5.0.48.gad9c376
Revision: 
Compile-Date: Dec  4 2023 16:43:50
Module-Directory: /usr/local/lib/syslog-ng
Module-Path: /usr/local/lib/syslog-ng
Include-Path: /usr/local/share/syslog-ng/include
Error opening plugin module; module='loki', error='/usr/local/lib/libgrpc-protos.so.0: Undefined symbol "_ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev"'
Error opening plugin module; module='otel', error='/usr/local/lib/syslog-ng/libotel.so: Undefined symbol "_ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E"'
Available-Modules: http,json-plugin,add-contextual-data,affile,afprog,afsocket,afstomp,afuser,appmodel,azure-auth-header,basicfuncs,cef,confgen,cryptofuncs,csvparser,correlation,disk-buffer,examples,graphite,hook-commands,kvformat,linux-kmsg-format,map-value-pairs,metrics-probe,pseudofile,regexp-parser,secure-logging,stardate,syslogformat,system-source,tags-parser,tfgetent,timestamp,xml,rate-limit-filter
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off
Enable-Systemd: off
```

**Comment by czanik** [comment]
OK. I did a bit of experimenting. Replacing all occurrences of ```stdc++``` with ```c++``` in code helps a lot. At least syslog-ng does not throw an error on ```syslog-ng -V```:
```
[root@fb132 ~/syslog-ng-grpc]# syslog-ng -V
syslog-ng 4 (4.5.0.48.gad9c376)
Config version: 4.2
Installer-Version: 4.5.0.48.gad9c376
Revision: 
Compile-Date: Dec  4 2023 18:09:44
Module-Directory: /usr/local/lib/syslog-ng
Module-Path: /usr/local/lib/syslog-ng
Include-Path: /usr/local/share/syslog-ng/include
Available-Modules: http,loki,otel,json-plugin,add-contextual-data,affile,afprog,afsocket,afstomp,afuser,appmodel,azure-auth-header,basicfuncs,cef,confgen,cryptofuncs,csvparser,correlation,disk-buffer,examples,graphite,hook-commands,kvformat,linux-kmsg-format,map-value-pairs,metrics-probe,pseudofile,regexp-parser,secure-logging,stardate,syslogformat,system-source,tags-parser,tfgetent,timestamp,xml,rate-limit-filter
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off
Enable-Systemd: off
```
All I did was:
```
grep -Rl stdc++ * > 1
```
and
```
for i in `cat 1` ; do sed -i czp 's/stdc++/c++/g' $i ; done
```
So, it seems that I found the solution for my favorite OS, FreeBSD. However, a lot more users run RHEL, and RHEL 9 is getting popular...

**Comment by bazsi** [comment]
I was just wondering how we got that the g_pointer_atomic_*() functions support anything but pointers? Because we passing a gssize to them at the moment.

@MrAnno do you have a recollection of that?

**Comment by MrAnno** [comment]
We wanted 64-bit stats counters wherever they are available, so we implemented atomic_gssize on top of atomic pointers. There is a static assertion making sure that the size of gssize matches the size of a void pointer.

**Comment by bazsi** [comment]
Just pushed an alternative solution. This should trigger a lot of compilation warnings but should let syslog-ng compile. Details: https://gitlab.gnome.org/GNOME/glib/-/issues/3193#note_1935964

@czanik can you please check if his indeed compiles on RHEL9?

The FreeBSD issue is separate, if you compile with gcc the issue is that your protobuf libraries are compiled with clang and that causes the linker error. Actually you get the same issue with clang but it errors out instead of simply generating an invalid binary.  The right solution is indeed to link against -lc++ instead of -lstdc++ but we would need to detect somehow which one is the right one.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by czanik** [comment]
@bazsi Thanks! I'm still waiting for the Fedora / RHEL builds, but (open)SUSE build results are already available. This patch breaks SLES 12 SP5:
```
[   27s] checking for glib-2.0 >= 2.32 gmodule-2.0 gthread-2.0... yes
[   27s] checking for g_list_copy_deep... yes
[   27s] checking for g_ptr_array_find_with_equal_func... no
[   27s] checking for g_canonicalize_filename... no
[   27s] checking sanity checking Glib headers... no
[   27s] configure: error: Glib headers inconsistent with current compiler setting. You might be using 32 bit Glib with a 64 bit compiler, check PKG_CONFIG_PATH
[   28s] error: Bad exit status from /var/tmp/rpm-tmp.9BiXoz (%build)
```

**Comment by czanik** [comment]
@bazsi RHEL 9 compile finished successfully: https://download.copr.fedorainfracloud.org/results/czanik/syslog-ng-githead/epel-9-x86_64/06728673-syslog-ng/builder-live.log.gz

I'll try to install it now.

**Comment by bazsi** [comment]
centos7 and sles sp5 breaks as they don't have glib 2.68 which this PR would start depending on.

**Comment by bazsi** [comment]
I've tried to fix up centos7. let's see if that works.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
@kira-syslogng retest this please;

**Comment by bazsi** [comment]
This is finally green. With that we can properly compile syslog-ng with clang++ that should fix our RHEL9 build.

@czanik can you please try it?

FreeBSD is still not working, as for that we would need to find out the proper c++ library to use. stdc++ or c++

**Comment by czanik** [comment]
Thanks @bazsi, all builds are green, including ancient distros, like RHEL 7 and SLES 12.

I even tested FreeBSD, and even that works just fine, if I replace stdc++ with c++ using sed...

So, this is OK and a very welcome change from my part, but as these are huge changes, I'll ping the PE team to check it.

**Comment by czanik** [comment]
@bazsi I just got a response from a PE member: it will need some minor fixes on the PE side, but can go ahead.

**Comment by bazsi** [comment]
Thanks. I still need a review. Could @HofiOne or someone add their review? This is split into two PRs, so we could focus on the first part initially.

**Review by HofiOne — APPROVED** [review]

**Comment by HofiOne** [comment]
Unfortunately there are still other issues on macOS, one of them is

```
[ 92%] Building CXX object modules/cloud-auth/CMakeFiles/cloud-auth-cpp.dir/cloud-auth.cpp.o
cd /Users/hofi/Develop/Balabit/syslog-ng/build/modules/cloud-auth && /Applications/Development/Xcode/15.1/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_68 -DYYDEBUG=1 -D_GNU_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -D__APPLE_USE_RFC_3542 -I/Users/hofi/Develop/Balabit/syslog-ng/build -I/Users/hofi/Develop/Balabit/syslog-ng/build/modules/cloud-auth -I/Users/hofi/Develop/Balabit/syslog-ng/lib -I/Users/hofi/Develop/Balabit/syslog-ng/build/lib -isystem /Users/hofi/Develop/Balabit/syslog-ng -isystem /Users/hofi/Develop/Balabit/syslog-ng/modules/cloud-auth -isystem /Users/hofi/Develop/Balabit/syslog-ng/modules/cloud-auth/jwt-cpp/include -isystem /Library/Frameworks/Mono.framework/Headers -isystem /opt/homebrew/Cellar/ivykis/0.42.4/include -isystem /opt/homebrew/Cellar/pcre2/10.42/include -isystem /Users/hofi/Develop/Balabit/syslog-ng/lib/eventlog/src -isystem /opt/homebrew/Cellar/glib/2.78.3/include/glib-2.0 -isystem /opt/homebrew/Cellar/glib/2.78.3/lib/glib-2.0/include -isystem /opt/homebrew/Cellar/openssl@1.1/1.1.1w/include -g -std=c++14 -arch arm64 -isysroot /Applications/Development/Xcode/15.1/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -fPIC -Wshadow -Wno-stack-protector -Wno-unused-parameter -Wno-variadic-macros -Wswitch-default -Wall -Wuninitialized -Wdeprecated -Wdeprecated-declarations -Woverflow -Wdouble-promotion -Wfloat-equal -Wpointer-arith -Wmissing-format-attribute -Wundef -Wignored-qualifiers -Wfloat-conversion -MD -MT modules/cloud-auth/CMakeFiles/cloud-auth-cpp.dir/cloud-auth.cpp.o -MF CMakeFiles/cloud-auth-cpp.dir/cloud-auth.cpp.o.d -o CMakeFiles/cloud-auth-cpp.dir/cloud-auth.cpp.o -c /Users/hofi/Develop/Balabit/syslog-ng/modules/cloud-auth/cloud-auth.cpp
In file included from /Users/hofi/Develop/Balabit/syslog-ng/modules/cloud-auth/cloud-auth.cpp:23:
In file included from /Users/hofi/Develop/Balabit/syslog-ng/modules/cloud-auth/cloud-auth.hpp:26:
In file included from /Users/hofi/Develop/Balabit/syslog-ng/modules/cloud-auth/cloud-auth.h:26:
In file included from /Users/hofi/Develop/Balabit/syslog-ng/lib/syslog-ng.h:35:
In file included from /Users/hofi/Develop/Balabit/syslog-ng/lib/compat/glib.h:29:
In file included from /opt/homebrew/Cellar/glib/2.78.3/include/glib-2.0/glib.h:34:
In file included from /opt/homebrew/Cellar/glib/2.78.3/include/glib-2.0/glib/gasyncqueue.h:34:
In file included from /opt/homebrew/Cellar/glib/2.78.3/include/glib-2.0/glib/gthread.h:34:
In file included from /opt/homebrew/Cellar/glib/2.78.3/include/glib-2.0/glib/gatomic.h:30:
In file included from /opt/homebrew/Cellar/glib/2.78.3/include/glib-2.0/glib/glib-typeof.h:43:
In file included from /Applications/Development/Xcode/15.1/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/type_traits:421:
In file included from /Applications/Development/Xcode/15.1/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/invoke.h:15:
In file included from /Applications/Development/Xcode/15.1/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__type_traits/apply_cv.h:15:
In file included from /Applications/Development/Xcode/15.1/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__type_traits/remove_reference.h:13:
In file included from /Applications/Development/Xcode/15.1/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/cstddef:41:
/Users/hofi/Develop/Balabit/syslog-ng/version:1:1: error: expected unqualified-id
4.5.0
^
```
This is an old issue with the version number define

**Comment by bazsi** [comment]
This seems to be the VERSION file in the root of syslog-ng. but that's all
caps e.g. "VERSION" and not "version"

**Comment by HofiOne** [comment]
> This seems to be the VERSION file in the root of syslog-ng. but that's all caps e.g. "VERSION" and not "version"

Yepp, we discussed this one once with @alltilla, not an easy fix as a bunch of build stuff depends on this (CI, PE)

**Comment by alltilla** [comment]
Yes the macOS filename case insensitivity is what tricks us here, I believe.

**Comment by HofiOne** [comment]
> Yes the macOS filename case insensitivity is what tricks us here, I believe.

@bazsi , @alltilla 

I finally got a working  build of GRPC dependant modules (so basically now all the c++ modules) on macOS as well

2 questions

1. it seems `libgrpc-protos.dylib` got referenced in the otel and the bigquery modules from
`install/lib/libgrpc-protos.dylib`
intead of 
`install/lib/syslog-ng/libgrpc-protos.dylib`
or the `libgrpc-protos.dylib` lib is installed to an incorrect location (`install/lib/syslog-ng/`)
which one is the required here?

2. it seems the `VERSION` file in the root folder of the syslog-ng repository is used only during the packaging flows
is this true?
(i just simply renamed the file, clean built everything and the build was successful, `syslog-ng --version` shows a correct version number)

**Comment by HofiOne** [comment]
>     2. it seems the `VERSION` file in the root folder of the syslog-ng repository is used only during the packaging flows
>        is this true?
>        (i just simply renamed the file, clean built everything and the build was successful, `syslog-ng --version` shows a correct version number)

no2. is solved by #4775

**Comment by alltilla** [comment]
Rebased to master and resolved the merge conflicts.

**Comment by alltilla** [comment]
Rebased to master.

**Review by alltilla — APPROVED** [review]

**Review by alltilla — APPROVED** [review]

**Review by alltilla — APPROVED** [review]

**Pull request merged**
