### PR TITLE
template: fix assertion failure for escaped templates

### LINKED ISSUE #4100: syslog-ng crashed in g_assert() if template-escape(yes) is set
# syslog-ng
## Version of syslog-ng
syslog-ng 3 (3.37.1)
Config version: 3.35
Installer-Version: 3.37.1
Revision: 
Module-Directory: /usr/lib/syslog-ng
Module-Path: /usr/lib/syslog-ng
Include-Path: /usr/share/syslog-ng/include
Available-Modules: stardate,http,kvformat,appmodel,afsql,basicfuncs,dbparser,tags-parser,affile,azure-auth-header,pseudofile,syslogformat,json-plugin,disk-buffer,add-contextual-data,linux-kmsg-format,graphite,tfgetent,timestamp,system-source,xml,afsocket,confgen,afprog,csvparser,cryptofuncs,hook-commands,examples,rate-limit-filter,afuser,map-value-pairs,secure-logging,cef,sdjournal,regexp-parser
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: on
Enable-Systemd: on

## Platform
Ubuntu 18.04

## Debug bundle
N/A

# Issue
When template-escape(yes) is set in a template(), an assertion failure occurs in [_propagate_type()](https://github.com/syslog-ng/syslog-ng/blob/syslog-ng-3.37.1/lib/template/eval.c#L40).
It seems that the LogMessageValueType isn't returned if escape is set in [log_macro_expand()](https://github.com/syslog-ng/syslog-ng/blob/syslog-ng-3.37.1/lib/template/macros.c#L711).

## Failure
**
ERROR:lib/template/eval.c:40:_propagate_type: assertion failed: (elem_type != LM_VT_NONE)
Aborted (core dumped)

## Configuration
@version: 3.37
  
source src {
    systemd-journal(prefix(".SDATA.journald."));
    internal();
};

destination d_pipe {
        pipe("/tmp/local.fifo"
                        template("{\"hostname\": \"$HOST\"}")
                        template-escape(yes)
            );
};
log {
        source(src);
        destination(d_pipe);
};

### PR DESCRIPTION
**Pull request by bazsi**
Fixes #4100 

* news file is still missing

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by Kokan** [comment]
@kira-syslogng retest this please

**Comment by bazsi** [comment]
@kira-syslogng retest this please;

**Comment by Kokan** [comment]
In the checks the result is present, and checked manually the Kira test was success(https://ci.syslog-ng.com/jenkins/job/kira-starter/9863/) only the comment is missing.
@bazsi if you could add a news entry I think this is good to go in.

**Review by Kokan — APPROVED** [review]

**Pull request merged**
