### PR TITLE
Version: 4.0.0

### PR DESCRIPTION
**Pull request by kira-syslogng**
Tarball is available at: https://github.com/syslog-ng/syslog-ng/actions/runs/3395986360

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
I have updated the NEWS file from NEWS-4.0.md and various PRs, some of which have not been merged yet. With those it should be pretty complete, however proof-reading would be important as well as double-checking if I missed something.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
I have double-checked that all merges that happened after this PR was opened is documented in the NEWS file at this point.

#4191, #4195, #4206

This requires #4210 to become green.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
rebased to current master and added coverage of all PRs merged in the meanwhile (e.g. up to https://github.com/syslog-ng/syslog-ng/commit/0db7b32b25caa4f08706079f6be13a71ee069a8f)

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
rebased and updated with the last 3 merges to master (#4229, #4197, #4209)

kira fails on this one as we've started to require Python based LogParser's to actually use LogParser as the base class, and similarly for LogDestination's, we started to require that the Python class is derived from LogDestination.

This needs to change in the testcases kira is executing.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by MrAnno** [comment]
> This needs to change in the testcases kira is executing.

We'll do that with @HofiOne.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
updated for #4056

**Comment by bazsi** [comment]
@alltilla as it seems once the 4.0 version number kicks in, one of the diskq related unit tests breaks. Can you please check that?

**Comment by alltilla** [comment]
Sure, I will check it today.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by alltilla** [comment]
Updated the `NEWS.md` file entries for #4056 a bit.

**Comment by MrAnno** [comment]
I've rebased this branch onto the disk-buffer test correction.

**Comment by HofiOne** [comment]
@kira-syslogng test this please test branch=OSE-Version-4.0.0-Kira-Fixes;

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by HofiOne** [comment]
@kira-syslogng test this please test branch=OSE-Version-4.0.0-Kira-Fixes;

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by HofiOne** [comment]
@kira-syslogng test this please test branch=OSE-Version-4.0.0-Kira-Fixes;

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by HofiOne** [comment]
@kira-syslogng test this please test branch=OSE-Version-4.0.0-Kira-Fixes;

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by HofiOne** [comment]
@kira-syslogng test this please test branch=OSE-Version-4.0.0-Kira-Fixes;

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by HofiOne** [comment]
@kira-syslogng test this please test branch=OSE-Version-4.0.0-Kira-Fixes;

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by HofiOne** [comment]
@kira-syslogng test this please test branch=OSE-Version-4.0.0-Kira-Fixes;

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
rebased and updated NEWS with the latest PRs.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
rebased and updated to latest merges.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by MrAnno** [comment]
@HofiOne Could you please push the remaining Kira fixes to an internal testdb branch?

**Comment by HofiOne** [comment]
@kira-syslogng test this please test branch=OSE-Version-4.0.0-Kira-Fixes;

**Comment by bazsi** [comment]
updated with latest changes and rebased against master.

**Comment by MrAnno** [comment]
@kira-syslogng test this please test branch=OSE-Version-4.0.0-Kira-Fixes;

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by alltilla** [comment]
Updated with #4238

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by HofiOne** [comment]
@kira-syslogng test this please test branch=OSE-Version-4.0.0-Kira-Fixes;

**Comment by MrAnno** [comment]
Yay! Thanks, @HofiOne.

**Comment by MrAnno** [comment]
LGTM. I've fixed a few typos; you can check them here:
https://github.com/MrAnno/syslog-ng/commit/d6f1b4b69c0db1b6adbc1ed785c6bc7102da7256

If you like the fix, you can reset to the following branch, which contains these corrections and all the other news updates. I squashed them into the first NEWS update commit: https://github.com/MrAnno/syslog-ng/commits/version/4.0.0

**Comment by bazsi** [comment]
Just go ahead and push them. I am sure they are ok.

**Comment by MrAnno** [comment]
Pushed. Thank you.

**Comment by MrAnno** [comment]
@kira-syslogng test this please test branch=OSE-Version-4.0.0-Kira-Fixes;

**Review by MrAnno — APPROVED** [review]
A solid 14-page-long news file. Nice :)

**Comment by bazsi** [comment]
I've added the --with-python-packages=none documentation.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
@kira-syslogng test this please test branch=OSE-Version-4.0.0-Kira-Fixes;

**Comment by bazsi** [comment]
@MrAnno can you re-approve this please?

**Review by MrAnno — APPROVED** [review]

**Comment by kira-syslogng** [comment]
**Draft release** workflow started: https://github.com/syslog-ng/syslog-ng/actions/runs/3740374839.

**Comment by kira-syslogng** [comment]
**Draft release** workflow finished successfully. Please check the Releases page: https://github.com/syslog-ng/syslog-ng/releases

**Pull request merged**
