### PR TITLE
DbldKira: Upgrade Kira base image to Bionic

### PR DESCRIPTION
**Pull request by mitzkia**
This PR upgrades syslog-ng-kira image from Ubuntu Xenial to Ubuntu Bionic.
Due to this change libmongoc* and libbson* packages should be installed with a fixed version on Ubuntu Bionic (related issue: #3184 )

Signed-off-by: Andras Mitzki <andras.mitzki@balabit.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by alltilla** [comment]
@bazsi Can you take a look at this again please? Thanks! :)

**Comment by mitzkia** [comment]
Build packages please

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by mitzkia** [comment]
Build packages please

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by mitzkia** [comment]
Build packages please

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by mitzkia** [comment]
Build packages please

**Comment by kira-syslogng** [comment]
Package Build SUCCESS

Packages are available at https://ci.syslog-ng.com/jenkins/job/kira-dbld-pull-requests/668/artifact/

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by mitzkia** [comment]
Build packages please

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by mitzkia** [comment]
Build packages please

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by mitzkia** [comment]
Build packages please

**Comment by kira-syslogng** [comment]
Package Build SUCCESS

Packages are available at https://ci.syslog-ng.com/jenkins/job/kira-dbld-pull-requests/671/artifact/

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
