### PR TITLE
DBLDBuilddeps: Generalize python / pip install and upgrade for various python versions

### PR DESCRIPTION
**Pull request by mitzkia**
- also upgrade setuptools package along with pip

Signed-off-by: Andras Mitzki <andras.mitzki@balabit.com>

This PR fixes various python related issues in build packages, and also clarify python related installs during dbld image setup.

### CODE REVIEW

**Comment by mitzkia** [comment]
@kira-syslogng build packages please

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by mitzkia** [comment]
@kira-syslogng build packages please

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by mitzkia** [comment]
@kira-syslogng build packages please

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by mitzkia** [comment]
@kira-syslogng build packages please

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by mitzkia** [comment]
@kira-syslogng build packages please

**Comment by kira-syslogng** [comment]
Package Build SUCCESS

Packages are available at https://ci.syslog-ng.com/jenkins/job/kira-dbld-pull-requests/702/artifact/

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by mitzkia** [comment]
@kira-syslogng build packages please

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by mitzkia** [comment]
@kira-syslogng build packages please

**Comment by kira-syslogng** [comment]
Package Build SUCCESS

Packages are available at https://ci.syslog-ng.com/jenkins/job/kira-dbld-pull-requests/704/artifact/

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by mitzkia** [comment]
@bazsi I would like to ask you what was the original reason to install `pip==9.0.3` on CentOS systems?
In this PR I have changed it to the latest pip version, and the build packages has passed on all platforms.

**Pull request merged**
