### PR TITLE
Added macOS System-Source

### PR DESCRIPTION
**Pull request by yashmathne**
The system-source() source driver for syslog-ng automatically identifies the system and then links the appropriate source to read the system and kernel logs from. 
On macOS, since macOS version 10.8, there is no separate kernel log file, instead both system logs and kernel logs get logged onto a file named system.log. ( `/var/log/system.log` ). 
I have modified the `system-source.c` file to add a file driver to this file using a function already defined for creating files drivers for the different systems in accordance with the system-source() [documentation](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.30/administration-guide/27#TOPIC-1594950).

The application logs are excluded since application logs are highly dependent on what applications you run and shouldn't be in the standard system source.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by Kokan** [comment]
@kira-syslogng ok to test

**Comment by MrAnno** [comment]
Hi,

Thank you for opening this PR.

Reading this regular text file (`/var/log/system.log`) can be a good workaround for macOS, but the original intention with our `system()` source is to replace the given system's syslog implementation and receive messages directly, or in case that's not possible (for example with systemd-journal), just read system logs in a native manner.

In this specific case, `/var/log/system.log` is a filtered textual _output_ of Apple's syslogd.

AFAIK macOS uses its own structured/binary logging mechanism called ASL, which is a replacement for the standard `syslog()` interface. They seem to provide read/query/search methods as well:
https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/asl.3.html
They seem to deprecate this API too in favor of the higher level `OSLog` facility:
https://developer.apple.com/documentation/oslog

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
Closing in favor of #3908.

Thanks again for opening this PR. I'll test the patch on the latest macOS version and hopefully, it can be part of syslog-ng v3.36.1.

**Comment by HofiOne** [comment]
Native macOS system log source added in https://github.com/syslog-ng/syslog-ng/pull/4423

**Pull request closed without merging**
