### PR TITLE
Version: 4.6.0

### PR DESCRIPTION
**Pull request by kira-syslogng**
TODO:
 - [x] bigquery news entry

Tarball is available at: https://github.com/syslog-ng/syslog-ng/actions/runs/7460992146

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build triggered

**Comment by kira-syslogng** [comment]
Build FAILURE

**Review by MrAnno — DISMISSED** [review]

**Review by MrAnno — DISMISSED** [review]

**Review by MrAnno — DISMISSED** [review]

**Review by bazsi — APPROVED** [review]

**Comment by kira-syslogng** [comment]
**Draft release** workflow started: https://github.com/syslog-ng/syslog-ng/actions/runs/7652238858.

**Comment by kira-syslogng** [comment]
**Draft release** workflow finished successfully. Please check the Releases page: https://github.com/syslog-ng/syslog-ng/releases

**Pull request merged**
