### PR TITLE
Rename modules dbparser to correlation

### PR DESCRIPTION
**Pull request by bazsi**
This PR renames the modules/dbparser directory (and module) to modules/correlation to indicate that all of our correlation related plugins are stored there and not just dbparser.

This is coming from #4225 but can be merged separately. No NEWS file is required in my opinion, the module is auto-loaded anyway, but we can have a note in the NEWS if someone needs it to be necessary.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by alltilla** [comment]
Rebased to master, to get the python fix.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Review by alltilla — APPROVED** [review]
Kira build is failing on master, too, so it is not related to this PR.

**Comment by alltilla** [comment]
I have created a PR for the news entry about the so rename: https://github.com/syslog-ng/syslog-ng/pull/4299

**Pull request merged**
