### PR TITLE
Add Pull Request template

### PR DESCRIPTION
**Pull request by OverOrion**
This PR tries to give a gentle reminder of some steps that are required, but might not be enforced by the current CI and/or might be overlooked.

We've agreed on that it should be similar to the current issue template format, meaning that there are no checkboxes to tick as it would make things unnecessary complicated for smaller contributions. 

You can check how it looks on my fork:
https://github.com/OverOrion/syslog-ng/compare/master...OverOrion:test_branch?expand=1

I was reluctant to add the whole `PR description` from the [`CONTRIBUTING.md`](https://github.com/syslog-ng/syslog-ng/blob/master/CONTRIBUTING.md#pr-description) as they might not be in sync in the future and first time contributors are already informed to read the guidelines, nevertheless I am open to adding it, just let me know.

And of course if you have other notes / ideas / etc, please let me know!

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by MrAnno — APPROVED** [review]
Thank you.

**Review by Kokan — APPROVED** [review]

**Pull request merged**
