### PR TITLE
Add $TRANSPORT and $IP_PROTO macros

### PR DESCRIPTION
**Pull request by bazsi**
This branch implements two new name-value pairs populated by syslog-ng to make it easier to create drill-downs into the message streams via metrics.

**$TRANSPORT:**

This branch implements $TRANSPORT, a new key-value pair, automatically populated by syslog-ng to indicate the kind of transport that was used to receive the message.

The $TRANSPORT is a higher level protocol, at least compared to $PROTO (contains the L3 protocol id from /etc/protocols) or $IP_PROTO 

**$IP_PROTO:**
$IP_PROTO contains 4 for ipv4 and 6 for ipv6.

These are the current values from the afsocket module:
  * rfc3164+tls
  * rfc3164+tcp
  * rfc3164+udp
  * rfc3164+proxied-tls
  * rfc3164+`<custom logproto like altp>`
  * rfc5426: new style syslog over udp
  * rfc5425: new style syslog over tls
  * rfc6587: new style syslog over tcp
  * rfc5424+`<custom logproto like altp>`: new style syslog over a logproto plugin
  * unix-stream
  * unix-dgram

I have also added support for this to:
  * otel source (uses "otlp")
  * mqtt source (uses "mqtt")
  * hypr source (uses "hypr-api")

The branch also contains a couple of "other" patches:
 * a small refactor to define "predefined" name-value pairs that are not static in NVTable
 * a fix for an uninitialized value in transport-aux-data
 * the $PROTO value for transport(tls) connections is now "6"(tcp)
 * ~~v4-mapped addresses in IPv6 sources should be translated to simple IPv4 addresses, instead of their more complex v4-mapped syntax (e.g. 192.168.1.1 instead of ::ffff:192.168.1.1)~~
 * inline documentation for the explicit source side batching feature in Python

Some of these could be extracted, others we are depending on with the new features.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
I dropped the patch that causes MacOS builds to build and added it to #4674

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
Found the reason for the @kira-syslogng breakage. Let's hope it works out this time.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
@kira-syslogng retest this please;

**Review by MrAnno — APPROVED** [review]

**Pull request merged**
