### PR TITLE
Add spoof-source-max-msglen() to network() driver too

### PR DESCRIPTION
**Pull request by gaborznagy**
This PR also contains some cmake related fixes, when I've discovered that libnet discovery doesn't work with cmake.
See our CI (devshell):
https://github.com/syslog-ng/syslog-ng/runs/4170865219?check_suite_focus=true

I think the other package finds should be fixed as well. If the solution of libnet discovery is good, I'll make those changes too.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by bazsi — DISMISSED** [review]
the code changes look good to me. the CI failed for some reason, logs are not visible, maybe a restart is needed?

**Review by MrAnno — APPROVED** [review]

**Comment by MrAnno** [comment]
Distcheck is failing:
```
/__w/_temp/23201d4a-7d36-4eeb-92b3-5ea3b6aee0b5.sh: 36: [: Illegal number: sed -e 's,/opt/syslog\\*-ng/etc,/usr/local/etc,g' -e 's,/opt/syslog\\*-ng/,/usr/local/,g' <doc/man/secure-logging.7 >doc/man/secure-logging.7.tmp && mv doc/man/secure-logging.7.tmp doc/man/secure-logging.7
/__w/_temp/23201d4a-7d36-4eeb-92b3-5ea3b6aee0b5.sh: 45: return: Illegal number: sed
```

@bazsi Do you see the current CI output now? Maybe it was some kind of a permission problem.

**Comment by MrAnno** [comment]
@gaborznagy The actual failure is due to the renamed CMake find module. The new name needs to be usedin the autotools Makefile as well.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by gaborznagy** [comment]
Thank you for the help, the PR is all green now!!!! :tada: 

I'll mark this PR WIP for today, and I add the other cmake warning-related fixes too!
(mostly about the same find_package_handle_standard_args warning)

**Comment by gaborznagy** [comment]
All is done.

I still see some dev-warnings in cmake output (missing policies and for mongoc a deprecated cmake module is used), but I skip those in this PR.
The libmongoc related change requires version bumping to 1.7.0 if I saw it correctly, and on EPEL 7 the version is just 1.3.6.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by MrAnno — APPROVED** [review]
About CMake find modules: I  think we should start using imported targets in the long run.

**Review by bazsi — APPROVED** [review]

**Pull request merged**
