### PR TITLE
grpc: Further Loki and Otel module switches corrections

### PR DESCRIPTION
**Pull request by HofiOne**
- added the missing autotools counterpart of the earlier addition of the cmake otel and loki switches  
#4649
- added the missing cmake grpc-protos lib dependency to loki module
- added missing loki protobuf generation to the cmake builds

Signed-off-by: Hofi <hofione@gmail.com>

### CODE REVIEW

**Comment by bazsi** [comment]
I've tried this with --disable-loki and --disable-otel.  They seem to work. 

However the gRPC portion is still built for both otel and loki even if those modules are disabled.

What's more, those generated files are not included in the tarball, so any user would need the protobuf codegen tools to be able to compile syslog-ng.

I am not really convinced that --disable-loki or --disable-otel really helps much in this situation.

I think the following would improve the situation:

1) delegate the building of proto files to the appropriate subdirectory (e.g. loki related proto file should be declared in modules/grpc/loki and not in modules/grpc/protos). Get rid off the "protos" directory altogether (the libgprc-protos .so can be built by the Makefile in modules/grpc dir)

2) include all the cpp build products in the tarball, so the user does not need  and the building of loki and otel .proto files as long she/he uses a tarball to build from

3) --disable-loki and --disable-otel then would make some sense, they would disable both the protos file and the production code. (although both otel and loki would need to be part of the same installation package because of their common dependency on libgrpc-protos)

4) our tarball environment should have all tools required to build the grpc stuff (which it does I assume)

**Comment by HofiOne** [comment]
> I think the following would improve the situation:
> 
>     1. delegate the building of proto files to the appropriate subdirectory (e.g. loki related proto file should be declared in modules/grpc/loki and not in modules/grpc/protos). Get rid off the "protos" directory altogether (the libgprc-protos .so can be built by the Makefile in modules/grpc dir)

are there any special reasons why we do not build the generated protobuf codes right into the corresponding module (loki protos into the loki module, etc.) ?

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by HofiOne** [comment]
Based on the conversation with @bazsi closing this in favor of https://github.com/syslog-ng/syslog-ng/pull/4684

**Pull request closed without merging**
