### PR TITLE
Accept iso timestamp with a space instead of t

### PR DESCRIPTION
**Pull request by bazsi**
This patch implements accepting ISO8601 timestamps with a space instead of a 'T' in the middle, as this format happens a lot in the wild.

For instance ZScaler produces this syslog header:
```
<134>2022-01-27 10:32:35      reason=Allowed... # message continues
```

The patch causes syslog-ng to accept this timestamp both in RFC5424 and RFC3164 mode. I've decided this way as even if we permitted the incorrect formatting only in RFC3164 mode, I expect the same to happen in 5424 implementations too. And I know it's against the spec, but this seems to be an uphill battle.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
LGTM.
The macOS job failed on one of the unit tests:
```
[----] tests/unit/test_msgparse.c:163: Assertion failed: Unexpected timestamp, value=1162083600, expected=1162080000, msg=<7>2006-10-29 02:00:00
```

Please add a news entry.

**Comment by bazsi** [comment]
> ```
> [----] tests/unit/test_msgparse.c:163: Assertion failed: Unexpected timestamp, value=1162083600, expected=1162080000, msg=<7>2006-10-29 02:00:00
> ```

Probably MacOS has a different timezone and that test does not mock the timezone setting. I think the other testcase covers the parsing piece, so I've removed this failing testcase from test_msgparse. We still have one but that contains timezone
information and thus we validate that timestamps without 'T" are parsed end-to-end via the normal parser.

That test_msgparse unit test is a dire need of a refactor...

> 
> Please add a news entry.

I was about to. :)

**Comment by MrAnno** [comment]
> That test_msgparse unit test is a dire need of a refactor...

Yeah, that one is terrible. Sorry about that, I was lazy when I ported this test to Criterion :(

**Review by MrAnno — APPROVED** [review]

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by alltilla — APPROVED** [review]

**Pull request merged**
