### PR TITLE
Uʍop ǝpᴉsdn ɹǝsɹɐd dᴉlɟ

### PR DESCRIPTION
**Pull request by Kokan**
```
 ;)  
   )sey(txet-esrever
   )sey(txet-pilf
 (resrap-pilf  
```
:elpmaxe noitarugifnoc

EGASSEM esrever ro pilf ot ytilibissop dda :resrap-pilf

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by czanik** [comment]
I have tried to build the CentOS 7 packages using dbld, but it failed:

```
  CC       modules/regexp-parser/libregexp_parser_la-regexp-parser-parser.lo
  CC       modules/regexp-parser/libregexp_parser_la-regexp-parser-plugin.lo
  CC       modules/flip-parser/libflip_parser_la-flip-parser.lo
modules/flip-parser/flip-parser.c: In function '_flip':
modules/flip-parser/flip-parser.c:67:3: error: stray '\311' in program
   GString *ɯǝssɐƃǝ = g_string_new("");
   ^
modules/flip-parser/flip-parser.c:67:3: error: stray '\257' in program
modules/flip-parser/flip-parser.c:67:3: error: stray '\307' in program
modules/flip-parser/flip-parser.c:67:3: error: stray '\235' in program
modules/flip-parser/flip-parser.c:67:3: error: stray '\311' in program
modules/flip-parser/flip-parser.c:67:3: error: stray '\220' in program
modules/flip-parser/flip-parser.c:67:3: error: stray '\306' in program
modules/flip-parser/flip-parser.c:67:3: error: stray '\203' in program
modules/flip-parser/flip-parser.c:67:3: error: stray '\307' in program
modules/flip-parser/flip-parser.c:67:3: error: stray '\235' in program
modules/flip-parser/flip-parser.c:74:9: error: stray '\311' in program
         g_string_append(ɯǝssɐƃǝ, upside_map[index]);
         ^
modules/flip-parser/flip-parser.c:74:9: error: stray '\257' in program
modules/flip-parser/flip-parser.c:74:9: error: stray '\307' in program
modules/flip-parser/flip-parser.c:74:9: error: stray '\235' in program
modules/flip-parser/flip-parser.c:74:9: error: stray '\311' in program
modules/flip-parser/flip-parser.c:74:9: error: stray '\220' in program
modules/flip-parser/flip-parser.c:74:9: error: stray '\306' in program
modules/flip-parser/flip-parser.c:74:9: error: stray '\203' in program
modules/flip-parser/flip-parser.c:74:9: error: stray '\307' in program
modules/flip-parser/flip-parser.c:74:9: error: stray '\235' in program
modules/flip-parser/flip-parser.c:76:9: error: stray '\311' in program
         g_string_append_c(ɯǝssɐƃǝ, c);
         ^
modules/flip-parser/flip-parser.c:76:9: error: stray '\257' in program
modules/flip-parser/flip-parser.c:76:9: error: stray '\307' in program
modules/flip-parser/flip-parser.c:76:9: error: stray '\235' in program
modules/flip-parser/flip-parser.c:76:9: error: stray '\311' in program
modules/flip-parser/flip-parser.c:76:9: error: stray '\220' in program
modules/flip-parser/flip-parser.c:76:9: error: stray '\306' in program
modules/flip-parser/flip-parser.c:76:9: error: stray '\203' in program
modules/flip-parser/flip-parser.c:76:9: error: stray '\307' in program
modules/flip-parser/flip-parser.c:76:9: error: stray '\235' in program
modules/flip-parser/flip-parser.c:79:3: error: stray '\311' in program
   log_msg_set_value(*pmsg, LM_V_MESSAGE, ɯǝssɐƃǝ->str, ɯǝssɐƃǝ->len);
   ^
modules/flip-parser/flip-parser.c:79:3: error: stray '\257' in program
modules/flip-parser/flip-parser.c:79:3: error: stray '\307' in program
modules/flip-parser/flip-parser.c:79:3: error: stray '\235' in program
modules/flip-parser/flip-parser.c:79:3: error: stray '\311' in program
modules/flip-parser/flip-parser.c:79:3: error: stray '\220' in program
modules/flip-parser/flip-parser.c:79:3: error: stray '\306' in program
modules/flip-parser/flip-parser.c:79:3: error: stray '\203' in program
modules/flip-parser/flip-parser.c:79:3: error: stray '\307' in program
modules/flip-parser/flip-parser.c:79:3: error: stray '\235' in program
modules/flip-parser/flip-parser.c:79:3: error: stray '\311' in program
modules/flip-parser/flip-parser.c:79:3: error: stray '\257' in program
modules/flip-parser/flip-parser.c:79:3: error: stray '\307' in program
modules/flip-parser/flip-parser.c:79:3: error: stray '\235' in program
modules/flip-parser/flip-parser.c:79:3: error: stray '\311' in program
modules/flip-parser/flip-parser.c:79:3: error: stray '\220' in program
modules/flip-parser/flip-parser.c:79:3: error: stray '\306' in program
modules/flip-parser/flip-parser.c:79:3: error: stray '\203' in program
modules/flip-parser/flip-parser.c:79:3: error: stray '\307' in program
modules/flip-parser/flip-parser.c:79:3: error: stray '\235' in program
make[2]: *** [modules/flip-parser/libflip_parser_la-flip-parser.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

```

**Comment by czanik** [comment]
The build seems to fail on all SLES and openSUSE Leap releses but compiles fine on openSUSE Factory and Tumbleweed: https://build.opensuse.org/project/show/home:czanik:syslog-ng-githead/ So, maybe it needs a more recent version of glib2.

**Comment by alltilla** [comment]
For some reason `flip-text(no)` `reverse-text(yes)` did not reverse my message, it only put the spaces to random places... o.O

`syslog-ng.conf`:
```
@version: 3.36

source s_stdin {
  file(
    "/dev/stdin",
    flags(no-parse)
  );
};

parser p_flip {
  flip-parser(
    flip-text(no)
    reverse-text(yes)
  );
};

destination d_stdout {
  file(
    "/dev/stdout"
    template("${MSG}\n")
  );
};

log {
  source(s_stdin);
  parser(p_flip);
  destination(d_stdout);;
};
```

output:
```
./sbin/syslog-ng -Fe
[2022-04-01T08:54:14.886292] syslog-ng starting up; version='3.36.1.76.g6ceafe5'
geza kek az eg
ge za kek azeg
```

Still investigating...

**Comment by czanik** [comment]
My config is:
```
tumbleweed:~ # cat /etc/syslog-ng/conf.d/flip.conf 
parser p_flip {
  flip-parser(
    flip-text(no)
    reverse-text(yes)
  );
};

destination d_flip {
  file("/var/log/flip");
};

log {
  source(src);
  parser(p_flip);
  destination(d_flip);
};
```
Do I need additional settings to enable UTF8 compatibility?
```
tumbleweed:~ # logger this is a test
tumbleweed:~ # logger árvíztűrő tükörfúrógép
tumbleweed:~ # tail -2 /var/log/flip 
Apr  1 09:02:23 tumbleweed root[9081]: tset a si siht
Apr  1 09:02:35 tumbleweed root[9083]: p��g��r��fr��k��t ��r��tz��vr��
```

**Comment by gaborznagy** [comment]
At first, I didn't get it, but then
it makes sense!

**Comment by czanik** [comment]
Flipping is also problematic with Hungarian characters, but works better than reversing:
```
parser p_flip {
  flip-parser(
    flip-text(yes)
    reverse-text(no)
  );
};

destination d_flip {
  file("/var/log/flip");
};

log {
  source(src);
  parser(p_flip);
  destination(d_flip);
};







File /etc/syslog-ng/conf.d/flip.conf saved
tumbleweed:~ # systemctl restart syslog-ng
tumbleweed:~ # logger this is a test
tumbleweed:~ # logger árvíztűrő tükörfúrógép
tumbleweed:~ # tail -2 /var/log/flip 
Apr  1 09:21:53 tumbleweed root[9179]: ʇɥᴉs ᴉs a ʇǝsʇ
Apr  1 09:22:00 tumbleweed root[9180]: áɹʌízʇűɹő ʇüʞöɹɟúɹóᵷéd
```

**Comment by gaborznagy** [comment]
> The build seems to fail on all SLES and openSUSE Leap releses but compiles fine on openSUSE Factory and Tumbleweed: https://build.opensuse.org/project/show/home:czanik:syslog-ng-githead/ So, maybe it needs a more recent version of glib2.

It also depends on whether gcc supports identifiers with UTF-8. I've just tested centos-7 dbld image with `gcc -finput-charset=UTF-8` (gcc version is 4.8.5):
```
test.c:6:1: error: stray ‘\317’ in program                                                                                                                                                                   
 double ρ=1.0;                                                                                                                                                                                               
 ^                  
```
See on [gcc forum](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67224)

I don't know the reason for newer distros (e.g. OpenSuse Leap 15.2).

**Comment by MrAnno** [comment]
˙sʇuǝɯɯoɔ ᴚԀ ǝǝs ʇ,uɐɔ ʍou 'ʎɐʃdsıp ʇɹǝʌuı oʇ pǝpǝǝᴎ

**Comment by faxm0dem** [comment]
̶P̶l̶e̶a̶s̶e̶ ̶r̶e̶m̶o̶v̶e̶ ̶t̶h̶i̶s̶ ̶P̶R̶ ̶u̶s̶i̶n̶g̶ ̶t̶h̶e̶ ̶n̶e̶w̶ ̶g̶i̶t̶h̶u̶b̶ ̶s̶t̶r̶i̶k̶e̶t̶h̶r̶o̶u̶g̶h̶ ̶A̶P̶I̶ ̶

**Comment by Kokan** [comment]
It seems my solution has some issues I have to investigate. brb

**Pull request closed without merging**
