### PR TITLE
Remove python logmsg blacklist

### PR DESCRIPTION
**Pull request by bazsi**
This is a followup to #4057

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by MrAnno** [comment]
LGTM.

@bazsi Could you resolve the conflict, please?

**Comment by bazsi** [comment]
Rebased against current master.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by MrAnno** [comment]
Thank you.

Kira has an internal sync issue, we'll fix it soon.

**Comment by MrAnno** [comment]
@kira-syslogng retest this please

**Review by MrAnno — APPROVED** [review]

**Pull request merged**
