### PR TITLE
secret-storage: handle missing MAP_ANONYMOUS

### LINKED ISSUE #4199: MAP_ANONYMOUS undefined on older macOS
# syslog-ng
3.38.1

## Platform
macOS 10.10

# Issue
## Failure
Build fails thus:
```
lib/secret-storage/nondumpable-allocator.c:96:57: error: use of undeclared identifier 'MAP_ANONYMOUS'
  gpointer area = mmap(NULL, len, PROT_READ|PROT_WRITE, MAP_ANONYMOUS|MAP_PRIVATE, -1, 0);
                                                        ^
1 error generated.
```

## Input and output logs (if possible)
https://build.macports.org/builders/ports-10.10_x86_64-builder/builds/199959/steps/install-port/logs/stdio

## Discussion

`MAP_ANONYMOUS` used to be called `MAP_ANON` on older macOS versions, so the fix is simple:
```
#ifndef MAP_ANONYMOUS
#define MAP_ANONYMOUS MAP_ANON
#endif
```

Not sure if a compat header would be warranted when this is the only place it's used in the codebase.

### PR DESCRIPTION
**Pull request by jmroot**
Fixes #4199.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by bazsi** [comment]
Ok to test.

**Comment by MrAnno** [comment]
Thank you.

Does this mean syslog-ng is now functional on older macOS versions with your 2 pull requests?

That would be wonderful news, we could mention that in our release notes (https://github.com/syslog-ng/syslog-ng/blob/master/news/README.md) :)

**Comment by jmroot** [comment]
> Does this mean syslog-ng is now functional on older macOS versions with your 2 pull requests?

It at least compiles back to 10.7 with these fixes, though I haven't actually tested functionality on such old systems. 10.6 fails due to lack of `IP_PKTINFO`.

**Pull request merged**
