### PR TITLE
Kafka remove properties file

### PR DESCRIPTION
**Pull request by gaborznagy**
Its main purpose was to help the migration from the Java-based kafka() driver to kafka-c() driver.

kafka-c() driver supports the config() option, where the librdkafka properties in key-value pairs format can be passed.
See librdkafka configuration [here](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md)

Example:
```
destination d_kafka {
  kafka-c(
    topic("test-topic")
    bootstrap-servers("kafka-server.prod:9092")
    config(
      log_level => 4,
      reconnect.backoff.ms => 50
    )
  );
};
```

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by Barkodcz — APPROVED** [review]

**Comment by gaborznagy** [comment]
Removing WIP flag as syslog-ng 3.33 release is published.
Rebased to master.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Review by szemere — DISMISSED** [review]

**Review by Barkodcz — APPROVED** [review]
If the kira test was successful, then can be merge

**Comment by Kokan** [comment]
Please do not merge this. If new releases is needed for Attila's dq fix, it is better if this is not merged. Thanks.

**Comment by gaborznagy** [comment]
@kira-syslogng retest this please;

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by gaborznagy** [comment]
I've rebased the branch and dropped the unit test fixing parts (see #3735)

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by Kokan — APPROVED** [review]

**Review by szemere — APPROVED** [review]

**Pull request merged**
