### PR TITLE
[WIP] Kira test PR

### PR DESCRIPTION
**Pull request by MrAnno**

### CODE REVIEW

**Comment by MrAnno** [comment]
@kira-syslogng do perftest branch=perfmem-test;

**Comment by kira-syslogng** [comment]
Kira-performance-test: Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
@kira-syslogng do perftest branch=perfmem-test;

**Comment by kira-syslogng** [comment]
Kira-performance-test: Build FAILURE

**Comment by MrAnno** [comment]
@kira-syslogng do perftest

**Comment by kira-syslogng** [comment]
Kira-performance-test: Build FAILURE

**Comment by MrAnno** [comment]
@kira-syslogng do perftest branch=perfmem-test;

**Comment by kira-syslogng** [comment]
Kira-performance-test: Build FAILURE

**Comment by MrAnno** [comment]
@kira-syslogng do perftest branch=perfmem-test;

**Comment by MrAnno** [comment]
@kira-syslogng do perftest branch=memcheck-timeout;

**Comment by kira-syslogng** [comment]
Kira-performance-test: Build SUCCESS

**Comment by MrAnno** [comment]
@kira-syslogng do perftest branch=memcheck-timeout;

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Kira-performance-test: Build SUCCESS

**Comment by MrAnno** [comment]
@kira-syslogng do stresstest

**Comment by kira-syslogng** [comment]
Kira-performance-test: Build FAILURE

**Comment by MrAnno** [comment]
@kira-syslogng do perftest

**Comment by kira-syslogng** [comment]
Kira-stress-test: Build SUCCESS

**Pull request closed without merging**
