### PR TITLE
news: Add missing news file for PR-3130

### PR DESCRIPTION
**Pull request by mitzkia**
Signed-off-by: Andras Mitzki <andras.mitzki@balabit.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by mitzkia** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by lbudai** [comment]
@kira-syslogng : retest this please

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by mitzkia** [comment]
@kira-syslogng : retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
