### PR TITLE
Fix leak and invalid memory access in unit tests

### PR DESCRIPTION
**Pull request by MrAnno**
No news file needed.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by Kokan — APPROVED** [review]

**Review by szemere — APPROVED** [review]
I think these are really good findings. Thank You!

**Pull request merged**
