### PR TITLE
compat/glib: fix recursive call issue

### LINKED ISSUE #3210: syslog-ng 3.26 on RHEL 6 dumps core
Compiled syslog-ng 3.26.1 release for RHEL/CentOS 6. I could create a package, install it on CentOS 6, but syslog-ng does not start. It dumps core:
```
[root@centos65 ~]# syslog-ng -V
Segmentation fault (core dumped)
```
When I check the core file, this is what I get (I don't have debug symbols compiled/installed):
```
Core was generated by `syslog-ng -V'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000030806323f6 in g_hash_table_lookup_extended ()
   from /lib64/libglib-2.0.so.0
```

### PR DESCRIPTION
**Pull request by lbudai**
Fixes #3210

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by lbudai** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by lbudai** [comment]
@kira-syslogng : retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
