### PR TITLE
create-news: add new team members

### PR DESCRIPTION
**Pull request by gaborznagy**

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by gaborznagy** [comment]
Corrected usernames based on usernames in git commits.

**Review by szemere — DISMISSED** [review]

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by szemere — APPROVED** [review]

**Review by MrAnno — APPROVED** [review]

**Pull request merged**
