### PR TITLE
VERSION: rename to VERSION.txt

### PR DESCRIPTION
**Pull request by bazsi**
To avoid inclusion when a c++ source code includes <version>, which seems to happen on MacOS with Clang.

### CODE REVIEW

**Comment by bazsi** [comment]
Successful version bump job: https://github.com/bazsi/syslog-ng/actions/runs/7430217757

Once it is merged the draft release job: https://github.com/bazsi/syslog-ng/actions/runs/7430495431

**Comment by bazsi** [comment]
This is a trival change, apart the risk of breaking the release process. I've seen this turn green while going through the version bump and then merging the version bump PR into master and then generating the release artifacts.

**Review by alltilla — APPROVED** [review]

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by HofiOne** [comment]
> Build FAILURE

strange, it is still in progress and cannot see any failing step  up to now :-O

**Pull request merged**
