### PR TITLE
[WIP] lgtm: add config file

### PR DESCRIPTION
**Pull request by lbudai**
* LGTM currently uses ubuntu 18.10
* libmongoc has a cmake bug on ubuntu 18.04 and 18.10 and for this
reason LGTM reports failure

Signed-off-by: Laszlo Budai <laszlo.budai@outlook.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by Kokan** [comment]
@alltilla I hope that is not the case (failing due to master), also currently it fails for sure on this branch as well.

**Comment by alltilla** [comment]
> Analysis failed (could not build the merge commit and the base commit (761f455))
The analysis for the merge commit and the base commit (761f455) was not successful. For more information, see the build and analysis logs on LGTM.com

:(

**Comment by MrAnno** [comment]
@alltilla https://lgtm.com/projects/g/syslog-ng/syslog-ng/logs/rev/pr-5649c1210dbaca1c16c8e3da748fbac7faac9036/lang:cpp/stage:Build%20merge_1331880942d0cdfd950bbf314c50722567b01799

> [2020-01-29 13:30:16] [build] ++ tee /etc/apt/sources.list.d/syslog-ng-obs.list
> [2020-01-29 13:30:16] [build] tee: /etc/apt/sources.list.d/syslog-ng-obs.list: Permission denied

**Comment by alltilla** [comment]
@MrAnno Thanks! We have to check the build on lgtm.com.

**Comment by lbudai** [comment]
@MrAnno: yes, it seems it's not possible to workaround the issue this way.
Other question: when lgtm falls back to autotools then the build also fails... 
@kokan: do you have any information regarding this? (I did not check slack, or any other common internal channel, so if you already shared this, don't be angry :) )

**Comment by Kokan** [comment]
I only reported this issue to lgtm with a minimal reproduction: https://discuss.lgtm.com/t/cmake-with-libmongoc-1-0-unable-to-work/2614
(I did not plan to work on this, as a few of us said he is going to work on it, as nobody said that want to report I did that only.)

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request closed without merging**
