### PR TITLE
News file for 4.0

### PR DESCRIPTION
**Pull request by bazsi**

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
@bazsi  Do you think we can merge this and reference this changelog entry in the v3.38 release announcement as upcoming 4.0-changes that can be tested by changing the config version?

**Comment by kira-syslogng** [comment]
Build FAILURE

**Review by MrAnno — APPROVED** [review]
Thank you.

**Pull request merged**
