### PR TITLE
scl/fortigate: set $HOST value from .fortigate.devid

### LINKED ISSUE #4867: default-network-drivers() is not getting fortigate logs hostname ($HOST) correctly
# syslog-ng
## Version of syslog-ng
syslog-ng 4 (4.6.0)
Config version: 4.2
Installer-Version: 4.6.0
Revision:
Compile-Date: Jan 26 2024 09:03:13
Module-Directory: /usr/lib64/syslog-ng
Module-Path: /usr/lib64/syslog-ng
Include-Path: /usr/share/syslog-ng/include
Available-Modules: add-contextual-data,affile,afprog,afsocket,afstomp,afuser,appmodel,basicfuncs,cef,confgen,correlation,cryptofuncs,csvparser,disk-buffer,examples,graphite,hook-commands,json-plugin,kvformat,linux-kmsg-format,map-value-pairs,metrics-probe,pacctformat,pseudofile,rate-limit-filter,regexp-parser,sdjournal,stardate,syslogformat,system-source,tags-parser,tfgetent,timestamp,xml

## Platform
NAME="Red Hat Enterprise Linux"
VERSION="8.9 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.9 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"

# Issue
## Failure
When using the $HOST macro to write the filename its failing to parse properly the "devname=HOSTNAME1" field and using the network host actually sending the logs instead.

## Steps to reproduce

    cat fortigate_log.txt | nc -4 -n -v 127.0.0.1 514

    ls -l /var/log/sources
    -rw-r-----. 1 root root 27989 Mar 22 10:50 localhost.log

It should be:

    -rw-r-----. 1 root root 27989 Mar 22 10:50 HOSTNAME1.log

## Configuration
        @version: 4.2
        @include "scl.conf"
        
        source s_network {
            default-network-drivers(
                flags(no-parse, store-raw-message)
            );
        };
        
        destination d_destination {
            file(
                "/var/log/sources/${HOST}.log"
                template("${RAWMSG}\n")
                create_dirs(yes)
            );
        };
        
        log {
            source(s_network);
            destination(d_destination);
        };

## Input and output logs (if possible)

    <189>date=2024-03-20 time=17:03:13 devname="HOSTNAME1" devid="REDACTED" eventtime=1710950593069066435 tz="+0100" logid="0000000015" type="traffic" subtype="forward" level="notice" vd="root" srcip=REDACTED srcport=36892 srcintf="gen2" srcintfrole="undefined" dstip=REDACTED dstport=443 dstintf="gen2" dstintfrole="undefined" srccountry="Reserved" dstcountry="Germany" sessionid=145154130 proto=6 action="start" policyid=10 policytype="policy" poluuid="REDACTED" policyname="REDACTED" service="HTTPS" trandisp="noop" duration=0 sentbyte=0 rcvdbyte=0 sentpkt=0 rcvdpkt=0 appcat="unscanned"

I noticed it works well with other log formats like PaloAlto etc. Am I missing something here or is this normal?

Thanks in advance for helping.

### PR DESCRIPTION
**Pull request by bazsi**
This should fix #4867

### CODE REVIEW

**Comment by alltilla** [comment]
The example message here does not have the `devid` field, maybe it is optional.
https://docs.fortinet.com/document/fortigate/7.4.3/fortios-log-message-reference/357866/log-message-fields

Also, the original issue mentioned the `devname` as the expected field.
I think maybe we should have a fallback logic between `devid`, `devname` and `srcip`.

**Comment by bazsi** [comment]
@kira-

**Comment by alltilla** [comment]
The example log I shared does not have `devid` nor `devname`.
I wonder if it is really the best idea, to filter fortigate logs on `devname`.

```
		filter {
			"${`prefix`devname}" ne ""
		};
```

**Comment by bazsi** [comment]
> The example log I shared does not have `devid` nor `devname`. I wonder if it is really the best idea, to filter fortigate logs on `devname`.
> 
> ```
> 		filter {
> 			"${`prefix`devname}" ne ""
> 		};
> ```

I all examples I've found included the devname:
* https://community.fortinet.com/t5/Support-Forum/Need-clarification-with-hostname-of-Fortigate-firewall-operating/m-p/140529
* https://armor-defense.atlassian.net/wiki/spaces/KB/pages/3519580247/Hostname+Field+Extraction#[inlineExtension]Fortinet-Fortigate)

So I would use that as is. The devid is an inmutable serial number of the device.

**Pull request merged**
