### PR TITLE
Fix glib2.28 support

### PR DESCRIPTION
**Pull request by gaborznagy**
g_mutex_init, and embedding GMutex in a struct is only supported since glib 2.32.
See:
https://developer.gnome.org/glib/stable/glib-Threads.html#g-mutex-init
please note, this patch adds deprecated APIs (since 2.32) though:
https://developer.gnome.org/glib/stable/glib-Deprecated-Thread-APIs.html#g-mutex-new

We should consider increasing the minimum version of glib.
Most of the distros use newer versions, and centos6 will be EOL on november 30 (https://wiki.centos.org/About/Product).
glib versions in distros: https://repology.org/project/glib/versions
We've discussed that some enterprise distros (e.g. SLES) use old glib too, but I've checked SLES 12 and it seems to use newer glib.
(lifecycle: https://www.suse.com/lifecycle/, SUSE Linux Enterprise Server 12 SP5 with general EOL 31 Oct 2024)
glib version on SLES12: `glib2-devel	2.48.2-12.15.1`
Source: https://scc.suse.com/packages?name=SUSE%20Linux%20Enterprise%20Server&version=12.5&arch=x86_64&query=glib2&module=

### CODE REVIEW

**Comment by gaborznagy** [comment]
I would like to double-check this PR with an internal test job, please do not merge it until.
Sorry, I wanted to open the PR as draft, I just mark it as WIP until the internal tests are not finished.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by gaborznagy** [comment]
@kira-syslogng build packages please;

**Comment by kira-syslogng** [comment]
Package Build SUCCESS

Packages are available at https://ci.syslog-ng.com/jenkins/job/kira-dbld-pull-requests/726/artifact/

**Comment by gaborznagy** [comment]
@kira-syslogng build packages please;

**Comment by gaborznagy** [comment]
Our internal tests have been passed, removing WIP flag.

**Comment by kira-syslogng** [comment]
Package Build SUCCESS

Packages are available at https://ci.syslog-ng.com/jenkins/job/kira-dbld-pull-requests/730/artifact/

**Comment by gaborznagy** [comment]
IMHO We should consider moving our minimum version of glib to at least 2.32 (GStaticMutex and some threading-related APIs are deprecated since 2.32).
Centos 6 will be EOL and of November 2020, and even though other platforms were mentioned that uses old glib (e.g. SLES 12, but I haven't found package versions) I think we should keep up with the glib changes.

**Review by lbudai — APPROVED** [review]

**Review by Kokan — APPROVED** [review]

**Pull request merged**
