### PR TITLE
news: add entry for #4881

### PR DESCRIPTION
**Pull request by alltilla**

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by alltilla** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by alltilla** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by alltilla** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by folti** [comment]
@kira-syslogng  retest this please

**Review by MrAnno — APPROVED** [review]

**Pull request merged**
