### PR TITLE
kafka: minor test-related fixes

### PR DESCRIPTION
**Pull request by MrAnno**
No news file entry is needed.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by alltilla — APPROVED** [review]

**Comment by alltilla** [comment]
[optional]
If I remember correctly, for the main build step, `cmake` fails if there is an unused variable warning. I wonder why it does not happen for the unit tests. It might be worth to investigate it a bit.

**Comment by MrAnno** [comment]
It's because we forgot to add that test to the CMake build. (Fixed in #3704.)

**Comment by alltilla** [comment]
Thanks for checking!

**Comment by MrAnno** [comment]
I've cherry-picked the relevant parts from @gaborznagy's PR.

**Review by alltilla — APPROVED** [review]
Thanks!

**Review by Kokan — APPROVED** [review]

**Comment by alltilla** [comment]
We can merge this before 3.33.2, as it is a really small PR.

**Pull request merged**
