### PR TITLE
packaging/debian: fix rdkafka packaging

### PR DESCRIPTION
**Pull request by lbudai**
All SCLs are shipped by syslog-ng-core.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by lbudai** [comment]
@kira-syslogng : retest this please

**Comment by lbudai** [comment]
build packages please.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Package Build SUCCESS

Packages are available at https://ci.syslog-ng.com/jenkins/job/kira-dbld-pull-requests/663/artifact/

**Comment by lbudai** [comment]
@kira-syslogng : retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
