### PR TITLE
*.py: s/python/python3/ (exclude tests)

### PR DESCRIPTION
**Pull request by yifan19**
As stated by https://github.com/syslog-ng/syslog-ng/pull/3603
python2 is EOL.

Fix all shebangs calling python instead of python3
except the tests.

(correcting lib/merge-grammar.py)
Signed-off-by: Joe Slater <joe.slater@windriver.com>
(adding the rest)2a1a44fade7e73872361568bd2dad235d083dcf1
Signed-off-by: Yi Fan Yu <yifan.yu@windriver.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by Kokan** [comment]
@kira-syslogng ok to test

**Review by Kokan — COMMENTED** [review]
Looks good to me. The CI sadly fails, the one regarding mac os is an issue on the current master also, you can ignore that. The other one is a style check of the commit message, it does not like the `*` in the`*.py`, I would just replace it with `python:` and that should help.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by yifan19** [comment]
> Looks good to me. The CI sadly fails, the one regarding mac os is an issue on the current master also, you can ignore that. The other one is a style check of the commit message, it does not like the `*` in the`*.py`, I would just replace it with `python:` and that should help.

done.

**Review by Kokan — APPROVED** [review]

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by gaborznagy — APPROVED** [review]
Looks good to me.

I'm waiting with the merge, until an internal test is not finished.

**Pull request merged**
