### PR TITLE
Groupset typing support (4.0)

### PR DESCRIPTION
**Pull request by bazsi**
This branch enables groupset() expressions to propagate types.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by MrAnno — APPROVED** [review]
For reviewers: only the last 4 commits need to be reviewed in this PR.
Everything else is coming from #3888.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by alltilla — APPROVED** [review]
Approve for the last 4 commits.

**Review by MrAnno — APPROVED** [review]

**Comment by MrAnno** [comment]
I'll merge it after the template/macro typing support goes in.

**Pull request merged**
