### PR TITLE
Fix type validation in "pdbtool test"

### PR DESCRIPTION
**Pull request by bazsi**
`pdbtool test`: fix two type validation bugs:

  1) When `pdbtool test` validates the type information associated with a name-value
     pair, it was using string comparisons, which didn't take type aliases
     into account. This is now fixed, so that "int", "integer" or "int64"
     can all be used to mean the same type.

  2) When type information is missing from a `<test_value/>` tag, don't
     validate it against "string", rather accept any extracted type.

In addition to these fixes, a new alias "integer" was added to mean the same
as "int", simply because syslog-ng was erroneously using this term when
reporting type information in its own messages.

### CODE REVIEW

**Comment by smortex** [comment]
It seems that 8c2ebe34ee6774a3e68af4057aec5099fbcbd3e5 incorrectly says "Fixes: #4403" while the fix seems to be in f19dec039b6eeb79d785497b6a8fc84f382c07d1.

Regarding 8c2ebe34ee6774a3e68af4057aec5099fbcbd3e5, I _feel_ like I used this "feature" to detect examples I had forgotten to update while migrating, so ignoring the data type would mean I would not have catch them maybe.  This looks odd, but maybe I am wrong.  Just wanted to raise this concern in case it is legit :smile:

**Comment by bazsi** [comment]
> It seems that [8c2ebe3](https://github.com/syslog-ng/syslog-ng/commit/8c2ebe34ee6774a3e68af4057aec5099fbcbd3e5) incorrectly says "Fixes: #4403" while the fix seems to be in [f19dec0](https://github.com/syslog-ng/syslog-ng/commit/f19dec039b6eeb79d785497b6a8fc84f382c07d1).

fixed, thanks.

> 
> Regarding [8c2ebe3](https://github.com/syslog-ng/syslog-ng/commit/8c2ebe34ee6774a3e68af4057aec5099fbcbd3e5), I _feel_ like I used this "feature" to detect examples I had forgotten to update while migrating, so ignoring the data type would mean I would not have catch them maybe. This looks odd, but maybe I am wrong. Just wanted to raise this concern in case it is legit 


Thanks for the feedback. Good point.

My original has never been to make the type field required here, you might not types in your db-parser() using configuration after all, unless you are actually generating JSON or something that uses types.

What if I change the output somewhat in case no type information was supplied? so you could grep for this in the output.

Like this:
```
$  pdbtool test -v faxmodem.pdb 
Module loaded and initialized successfully; module='syslogformat'
Module loaded and initialized successfully; module='basicfuncs'
Testing message: program='zmwatch' message='INF ['zma -m 13' starting at 14/11/16 21:28:13, pid = 27714]'
 Match name='.classifier.rule_id', value='FLARE-3698', type='string', expected='FLARE-3698'
 Match name='time', value='14/11/16 21:28:13', type='string', expected='14/11/16 21:28:13'
 Match name='pid', value='27714', type='int', expected='27714'
 Match name='camera', value='13', type='int[unchecked]', expected='13'
```

note the `[unchecked]` qualifier in the output for the `camera` field. I am adding this to the branch. What do you think?

**Comment by smortex** [comment]
I don't tell that the old behavior is right and the new wrong, I just wanted to emphasis the fact that I *used* the old behavior and it might have some value.

A warning message as you describe is very acceptable I think, and if everyone is okay with this I think it is great :100: !

Thank you!

**Review by alltilla — APPROVED** [review]

**Comment by alltilla** [comment]
@kira-syslogng retest this please

**Pull request merged**
