### PR TITLE
C++/gRPC module improvements

### PR DESCRIPTION
**Pull request by MrAnno**

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Review by alltilla — APPROVED** [review]
Nice!

The KIRA failure is caused by the usual git dubious ownership problem. I have contacted @HofiOne to help us out. Please wait with the merge until that is done.

**Comment by alltilla** [comment]
@kira-syslogng retest this please

**Pull request merged**
