### PR TITLE
system source: fix FreeBSD kernel messages

### PR DESCRIPTION
**Pull request by czanik**
Remove the no-parse flag from kernel messages, so the message
header is no more part of the message.

Signed-off-by: Peter Czanik <peter@czanik.hu>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
This looks good to me, from a code perspective, but I haven't tested it. Can you show a before/after result on a sample message?

With that I can approve this. Also iirc there was a dragonflybsd related change, it'd be great to see how that would build on top of this.

**Comment by czanik** [comment]
@bazsi https://github.com/syslog-ng/syslog-ng/issues/3560 shows the before/after.

The DragonFlyBSD problem is described at https://github.com/syslog-ng/syslog-ng/issues/3576 but I'd like to keep it separate from this one.

**Review by bazsi — APPROVED** [review]

**Review by Kokan — APPROVED** [review]

**Comment by Kokan** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
