### PR TITLE
add the extraction of syslog PRI value in cisco-parser()

### PR DESCRIPTION
**Pull request by bazsi**
This PR depends on #3536

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by MrAnno** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build FAILURE

**Review by MrAnno — APPROVED** [review]

**Comment by MrAnno** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
Kira fails because it expects the cisco messages to have facility code user whereas the correct code is local7. And this is now correctly parsed.

**Comment by MrAnno** [comment]
@kira-syslogng retest this please branch=cisco-parser-improvement;

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
In my understanding, this PR depends only on #3538, but not on #3536, so it has no more unmerged dependencies that would hold it back.

**Comment by MrAnno** [comment]
@kira-syslogng retest this please branch=cisco-parser-improvement;

**Review by MrAnno — APPROVED** [review]

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by gaborznagy — APPROVED** [review]
I would add a news entry to highlight that PRI is now parsed in `cisco-parser()` from the relevant field.
Optionally add the performance improvement to `default-network-drivers()` as well.

Approve.

**Pull request merged**
