### PR TITLE
syslog-format: add support for no-rfc3164-fallback flag

### PR DESCRIPTION
**Pull request by bazsi**
This flag would allow you to attempt parsing RFC5424 first without
an automatic fallback to RFC3164.

RFC3164. With this option it is possible to use drop-invalid(yes)
plus no-rfc3164-fallback, effectively being able to filter on RFC5424 only.

Signed-off-by: Balazs Scheidler <bazsi77@gmail.com>

### CODE REVIEW

**Comment by rfaircloth-splunk** [comment]
This will be very useful

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by MrAnno — APPROVED** [review]
LGTM.
(There is a style-format issue in the modified test)

**Comment by MrAnno** [comment]
Should we add a news entry about this? This might come in handy when writing SCL blocks or format-based filters.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by MrAnno — APPROVED** [review]

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by alltilla — APPROVED** [review]

**Pull request merged**
