### PR TITLE
Fix issue #3397 Improve regex related test cases 

### LINKED ISSUE #3397: Improve regex related test cases
## Description of the problem
During the work of #3393 and #3381 we found the regex related test cases (https://github.com/syslog-ng/syslog-ng/blob/master/lib/filter/tests/test_filters_regexp.c) insufficient.

## Proposed solution
- Overview the current test cases. (i.e. Peter's founding in #3393, where we blindly accepted the reported length.)
- Introduce new test cases for dupnames. (#3381)
- New test cases based on the PCRE documentation.

## Additional context
https://www.pcre.org/original/doc/html/pcretest.html
pcretest and related examples might be a good starting point.

### PR DESCRIPTION
**Pull request by LittleFish33**
## Purpose / Description

Fix #3397 Improve regex related test cases

## Approach

* introduce new test cases for dupnames.
* introduce various test cases to ensure the correctness of the code

## How Has This Been Tested?

Pass unit tests

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by Kokan** [comment]
@kira-syslogng ok to test

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by Kokan — APPROVED** [review]

**Review by gaborznagy — APPROVED** [review]
Thank you @LittleFish33  for the contribution!

**Pull request merged**
