### PR TITLE
Dbld build dependency support

### PR DESCRIPTION
**Pull request by bazsi**
This is the continuation of #3204 that should add Build-Depends/BuildRequires support to dbld instead of having to maintain packages.manifest.

This is a quite intrusive change for the following reasons:
 * since I want to share code between the building of the docker image vs. the using the same image, I have changed the root of the docker build from dbld/images to dbld/ that required the movement of a number of files
 * I've changed the format for build.manifest. Previously, it was pretty low level: we could supply environment variables and extra command line options to the build command, which were used to enable/disable options in various packages. Instead of this I am introducing feature flags, where we can specify if a distro is using python2 or 3, enables java or not, etc. These feature flags are then mapped to packaging specific logic, that ensures that Build-Depends/BuildRequires are properly applied.
 * Since I am using pretty recent dpkg stuff, I've dropped jessie and trusty support. This is needed because DEB_BUILD_PROFILES support is needed at the very least into the `mk-build-deps` tool. https://wiki.debian.org/BuildProfileSpec
 
This is work in progress and I only opened the PR to raise awareness that this is coming :)

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
build packages please

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by bazsi** [comment]
build packages please.

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
build packages please.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by bazsi** [comment]
build packages please.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by bazsi** [comment]
build packages please.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by bazsi** [comment]
build packages please.

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by bazsi** [comment]
build packages please.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Package Build SUCCESS

Packages are available at https://ci.syslog-ng.com/jenkins/job/kira-dbld-pull-requests/654/artifact/

**Comment by bazsi** [comment]
build packages please.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by bazsi** [comment]
build packages please.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by bazsi** [comment]
build packages please.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by bazsi** [comment]
build packages please

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Package Build SUCCESS

Packages are available at https://ci.syslog-ng.com/jenkins/job/kira-dbld-pull-requests/658/artifact/

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
I have now updated/added documentation and fixed all travis issues (this is just a hope :), those that remain should only be nitpicks so removing WIP flag.

Hopefully this makes it into the next release.

**Comment by bazsi** [comment]
@kira-syslogng build packages please.

**Comment by kira-syslogng** [comment]
Package Build SUCCESS

Packages are available at https://ci.syslog-ng.com/jenkins/job/kira-dbld-pull-requests/659/artifact/

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
