### PR TITLE
Fix macOS CMake build

### PR DESCRIPTION
**Pull request by MrAnno**

### CODE REVIEW

**Comment by MrAnno** [comment]
@HofiOne I've fixed the CMake jobs on macOS.

The PR contains some destruction as well: I reduced the macOS CI matrix from 2*2*2 to 2.

My reasoning is the following:
Our main platform is Linux. Keeping four macOS jobs (where 2 of them are for testing on a non-macOS-native compiler) seems to be hard to maintain as the removed diff clearly shows.

I also removed the macOS-14 job because based on their documentation, `latest` and `14` are the same:
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-private-repositories

I don't see a reason to test against old macOS versions (Homebrew does that for us), but I can clearly see the rationale in keeping an x86 macOS as well, but again, we shouldn't maintain more macOS jobs than Linux devshell jobs in my opinion.

Seeing how much you worked on fixing the gcc environment, it was a really bad feeling to remove the job, but at the same time, it was quite nice to realize that almost all workarounds could be removed by dropping a few less interesting test combinations.

Please let me know if you disagree.

**Comment by MrAnno** [comment]
Hmm, it seems the documentation is incorrect. `latest != 14`.
In that case, I would rather keep the one that can run our test suite, and I will start working on fixing Criterion and our tests on Apple silicon.

**Comment by HofiOne** [comment]
> Hmm, it seems the documentation is incorrect. `latest != 14`. In that case, I will start working on fixing Criterion and our tests on Apple silicon. Once I succeed, we can hopefully reduce the number of jobs to 2.

yes, this was my first thought, the doc is a bit ahead of reality, once it would be the "latest", but now it is the last x86 builder, only 14 (that is still in beta) can target arm64

currently a bunch of x86 HW is out there, I do not think it is a good idea to drop them

I do not mind dropping gcc, I just followed the earlier habit
as you mentioned llvm is the native solution on macOS long ago, and now we have (objC) parts in the source that might never will be compiled with GCC 

the number of jobs is almost irrelevant in this case in my opinion, as actually the silicon builds are the fastest of all

**Comment by HofiOne** [comment]
> Hmm, it seems the documentation is incorrect. `latest != 14`. In that case, I will start working on fixing Criterion and our tests on Apple silicon. Once I succeed, we can hopefully reduce the number of jobs to 2.

as I can remember fixing criterion builds will not be an easy one, it requires modifications on the criterion side, or using a totally different method as Apple dropped the support of position-dependent code, even though there are still switches in the compiler, event the command line --help will lie about it, but it is not supported anymore

**Review by alltilla — APPROVED** [review]

**Comment by MrAnno** [comment]
The PR does not remove the ARM job.

**Comment by HofiOne** [comment]
> The PR does not remove the ARM job.

yepp, I see now, both the latest and the 14 matrix variants remained
(I just was confused after reading the original version)

as I mentioned, I'm not against dropping the GCC support, if you all think it is a good step, I'm in, just tried to mention that it had advantages as well we had GCC builds here

**Comment by MrAnno** [comment]
The diff shows how problematic it was to maintain the gcc variants, and 8 macOS jobs are way more than what we currently run in devshell on Linux. If we want to increase the portability checks, I suggest adding a FreeBSD job instead.

The ARM and x86 macOS jobs are still here, so we have 4 macOS jobs overall.

**Comment by MrAnno** [comment]
Thanks for the discussion

**Comment by MrAnno** [comment]
@HofiOne I found a way to disable ASLR on arm64:
```
./test_str-utils
[====] Synthesis: Tested: 19 | Passing: 19 | Failing: 0 | Crashing: 0 
```

`posix_spawn()` has an option that creates a new process without ASLR. The same method is used by lldb.
I believe this feature belongs to Criterion (BoxFort), so I'll try to implement it there.

**Comment by HofiOne** [comment]
Oh, nice!
Hopefully, it will work in the future as well.

Fun fact, when I did a bit of research on the topic the first time I [found the same possibility](https://forums.developer.apple.com/forums/thread/740227), but did not take it further with the necessary step, aka. looking deeper into how lldb does it :)

**Pull request merged**
