### PR TITLE
WIP: transport: add support for recvmmsg()

### PR DESCRIPTION
**Pull request by bazsi**
I received this patch from ferenc.sipos@oneidentity.com and both a review and a performance check is due, but I've opened the PR so it does not get lost.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by furiel** [comment]
This PR is stalled for almost a year. Is there anyone who can take ownership of this PR? If not, I will close this soon.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Pull request closed without merging**
