### PR TITLE
cloud-auth: implement gcp(user-managed-service-account()) 

### PR DESCRIPTION
**Pull request by alltilla**
This authentication method can be used on VMs in GCP to use the linked service.

Example minimal config, which tries to use the "default" service account:
```
cloud-auth(
  gcp(
    user-managed-service-account()
  )
)
```

Full config:
```
cloud-auth(
  gcp(
    user-managed-service-account(
      name("alltilla@syslog-ng-test-project.iam.gserviceaccount.com")
      metadata-url("my-custom-metadata-server:8080")
    )
  )
)
```

This authentication method is extremely useful with syslog-ng's `google-pubsub()` destination,
when it is running on VMs in GCP, for example:
```
destination {
  google-pubsub(
    project("syslog-ng-test-project")
    topic("syslog-ng-test-topic")
    auth(user-managed-service-account())
  );
};
```

For more info about this GCP authentication method, see:
 * https://cloud.google.com/compute/docs/access/authenticate-workloads#curl
 * https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances

### CODE REVIEW

**Comment by bazsi** [comment]
The Mac build fails, but strangely it uses ivykis from the system not from the submodule, where some of the fixes would be.

I am also puzzled why it does not find the picojson symbol, which it finds on all three other combinations (automake with both clang/gcc, and cmake with clang works, cmake with gcc does not).

That symbol is coming from a header only lib which has the symbol on my system.

**Comment by alltilla** [comment]
According to http://demangler.com/

The missing symbol `__ZN8picojson5value3getIlEERT_v` is `_long& picojson::value::get<long>()`.

The `int64_t` support is not always enabled in picojson: https://github.com/kazuho/picojson?tab=readme-ov-file#experimental-support-for-int64_t, probably that macOS build is not enabling it by default, but others do.

I'll just get a `double` and round it.

**Comment by bazsi** [comment]
This is not performance critical so I am fine with using double here.

**Review by bazsi — APPROVED** [review]

**Comment by ThomasDevoogdt** [comment]
The [configure.ac](https://github.com/syslog-ng/syslog-ng/blob/master/configure.ac) should not longer automaticially enable cloud-auth, similar to enable_http, a check for curl should be done here.

**Pull request merged**
