### PR TITLE
dbld: remove ubuntu-eoan support

### PR DESCRIPTION
**Pull request by bazsi**
eoan is not an LTS and we have focal instead.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by lbudai** [comment]
@kira-syslogng : retest this please

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
@lbudai this is the same problem we discussed in email, the libmongoc version we explicitly pull in in our dbld images is missing from OBS.

**Comment by lbudai** [comment]
> @lbudai this is the same problem we discussed in email, the libmongoc version we explicitly pull in in our dbld images is missing from OBS.

yes... unfortunately Packages.gz does not contain libmongoc-dev package... 
There are other issues regarding to OBS (missing Release.key file for Ubuntu Focal).

**Comment by lbudai** [comment]
@kira-syslogng : retest this please.

**Comment by bazsi** [comment]
What if we just fixed the libmongoc related files from dockerfile abd with that we would avoid the obs dependency?

**Comment by lbudai** [comment]
> What if we just fixed the libmongoc related files from dockerfile abd with that we would avoid the obs dependency?

I think it's not a big issue - OBS upgrades keys from time to time then we have to wait for upgrade the repository. Now it should work.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
