### PR TITLE
github-actions: cat and upload test-suite.log if make check fails

### PR DESCRIPTION
**Pull request by alltilla**
Note: `cmake` does not generate this log file, but it shows the test case's error while `make check` runs.

Signed-off-by: Attila Szakacs <attila.szakacs@oneidentity.com>

### CODE REVIEW

**Comment by alltilla** [comment]
Test run: https://github.com/alltilla/syslog-ng/actions/runs/623750429

**Review by Kokan — APPROVED** [review]

**Comment by kira-syslogng** [comment]
Build FAILURE

**Review by mitzkia — DISMISSED** [review]

**Comment by mitzkia** [comment]
I am right now working on Kira failure testcase.
So Kira fails not because of this PR

**Review by szemere — DISMISSED** [review]

**Comment by alltilla** [comment]
Update: added `cat`. Test run: https://github.com/alltilla/syslog-ng/actions/runs/623951807

**Review by szemere — APPROVED** [review]

**Review by gaborznagy — APPROVED** [review]
thanks for the additional "cat test-suite.log" part!

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by mitzkia** [comment]
@kira-syslogng test this please test branch=micek_fix_collided_port_allocation;

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by mitzkia — APPROVED** [review]

**Pull request merged**
