### PR TITLE
redis: fix no batch mode

### PR DESCRIPTION
**Pull request by therandomstring**
Fixed problem where Redis driver failed without `batch-line` option in use. 

Signed-off-by: Bálint Horváth <bal.horv.98@gmail.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Review by MrAnno — APPROVED** [review]
Nice catch.

**Comment by MrAnno** [comment]
It turned out we don't have any automated tests for the Redis destination, its default config mode was broken for months.

We should add at least a smoke/acceptance test (maybe in Light @mitzkia ;)).

**Pull request merged**
