### PR TITLE
Elasticsearch java dest optimizations

### PR DESCRIPTION
**Pull request by soubhik-c**
All observation started from syslogng 3.16 and found to be accurate upto 3.20.

While scaling for 1 million msgs/sec ingestion into elasticsearch using syslog-ng elastic-v2 java destination, we found few bottlenecks when we ran experiments for several hours (upto 72 hrs of constant traffic). Our goal was to get a sustained input without any jitters while listening on multiple udp ports in syslog-ng. 

Primary issue we found in the plugin is: 
a) Too much garbage generation and inefficient json formatting using Gson. 
b) Another glaring issue was no matter how many threads we employed, things weren't scaling due to threads either spending its time in formatting log messages or waiting for http reply but both never happening at the same time. In other words, a destination thread was either formatting message or sending bulk message & formatting was costlier than sending and waiting.

Throughput was viewed in kibana discovery graph and was extremely wavy. We found ES wasn't pushed hard enough in the beginning.

We tried async httpcomponent and connection pool causing http timeout. Main issue was too many ESReject of the bulk message occurring when constant traffic flowed in for longer duration. 

Also, with some http message profiling, we noted message was getting copied multiple times in its path, firstly during formatting and then Jest api level string concatenation and lastly httpcomponent trying to push the message. Message fragmentation at the httpcomponent level wasn't getting avoided due to lack of length prefix provided and these message copy was causing too much gc pressure.

Initially we tried introducing multiple threads in the elastic-v2 plugin that will accumulate individual messages and format them into a bulk message & do send/receive. Idea was if enough threads are introduced, at the cost of higher context switches, we should be able to send continuous stream of bulk messages using http connection pool timeout settings appropriately. This didn't turned out very effective as CMS garbage collector still paused heavily the entire operation and G1GC in java-8 was showed instability on continuous load. Quickly realised upgrading to java-11 isn't easy due to jni level incompatibilities.

Second approach which is in this PR was to introduce a dedicated threadpool of finite size according to the hardware configuration. Speaking of h/w configuration, though syslogng is designed for 1 instance per host, our client had high end boxes (in aws terms xLarge with 32 cores and 168GB ram) for syslogng. Another imposition was to use docker containers. This changed the dynamics quite a bit because now multiple syslogng instances were contesting for the same h/w resources. Decoupling log formatting and bulk request send/receive showed promising results and supported our analysis of the bottleneck. Early closure of the response by reading response code '200' worked out great as it means all messages were success and doesn't really need parsing of the whole response for message ids.
Traffic overload could gracefully be handled by dropping messages and inferences from statistics was more accurate. Our usecase was to give preference to latest data over earlier minute data i.e. unlike syslogng using FIFO queue, we intend to use LIFO queue at a later time to guarantee message delivery of stale data during the lull period instead of trying to catchup with the queued messages at the very next second. For network security analytics, current second data (whatever we could capture) is more important than retrying message of last few seconds. However, eventually we need all of the data to be in the system for later analysis.

The connection pool at the plugin level increments dropped message count of the same destination statistics for now. In future, with the use of LIFO queue, guaranteed delivery can be achieved. The entire pool implementation can be disabled with concurrent-request(1) in the configuration.
 
We could achieve better stable input to ES when compared to native http performance introduced in syslogng. One primary disadvantage with native http plugin as of now is higher network payload mainly due to complete parsing of the http bulk message response from ES which is significant. That effectively slows down on the next request, consumes higher cpu and eats up network bandwidth as well as blocks ES side writer thread pool longer.

In ES, the bulk message hops around multiple servers in the current design. In the java plugin, we introduced facility to avoid such hoping without need for 'key' based shard allocation. Using key based shard routing mandates that key to be known during query time which becomes counter productive while asking adhoc queries. So, to achieve single hop bulk message processing in ES, a more viable design is to define one index per ES host and freeze the REST url's host ip and index name association. In java plugin, index name can't be embedded into url, we enabled it optionaly in this PR. This resulted in great overall stability in traffic ingestion as cross distribution of messages in ES side was all local among multiple ES instances hosted on a single machine. OTOH, syslogng could roundrobin bulk messages and keep the load shifting among ES instances and remained uneffected during index merges happening on the other end. So, ESReject bulk message from one ES server helped failing over to another without any involved changes.

This is just a brief description and if the community thinks this is good to pursue, I can provide with more details on the experiments (basically the numbers around tps/mem/cpu/network) and configuration details.

Few comments in another ticket with additional experiment details.
https://github.com/balabit/syslog-ng/issues/2466#issuecomment-456366108
https://github.com/balabit/syslog-ng/issues/2466#issuecomment-456872007

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by lbudai** [comment]
@soubhik-c: thank you for your pull request and also for the detailed description.
We are going to check your work soon.
Just some thoughts: 
 * what if we would move to the official elastic REST lib? What do you think, would it solve your issue? Or we would need to port your solution? (currently we are not planning to replace the JEST lib)
* did you try to use the native, http-driver based elasticsearch destination? If no, could you take a look at that?(after we understand your problem and your solution, we will also check, if it could be solved in the native http based dst)

**Comment by soubhik-c** [comment]
@lbudai  thanks for your attention.

* I haven't tried official elastic REST lib off late but it uses httpasyncclient underneath. In my experiments, I tried to use httpasynclient directly & found under heavy load it behaved erratically and left lots of open connection to ES. Essentially traffic flow halted after sometime. Having said that, I would expect ES folks must have done a better job than me while using httpasynclient. Synch api won't solve the problem for sure. GC pressure is another concern and I am not sure how ES driver high level or low level api caters to multiple message copy. In summary, if ES async api is gc friendly as well as gives a mechanism to parsing the complete response only on Error, my thread pool changes can be avoided (assuming connection timeout of the httpclient pool bug of ES is fixed). For Jest lib, I have overridden some of its classes in this changeset to make it play nicely with plugin level consumer threads minimizing garbage to the maximum extent. This gave me a good boost in sustaining load.

* I have tried native http-driver and mentioned my observations & limitations of it in the description already.

**Comment by faxm0dem** [comment]
FWIW I just updated one of my elasticsearch feeding instances from 3.9.1/elasticsearch-v2-java to 3.21.1/elastic-http, and while it works perfectly, I noticed a high increase in network traffic (almost doubled), and an even higher increase in disk/IO activity on the Elasticsearch nodes (more than doubled).

**Comment by soubhik-c** [comment]
@faxm0dem Thanks for the info. I haven't tried elastic-http but tried native-http in 3.20. I too observed doubled traffic but C impl wasn't able to match performance or stability with these java changes at 500K msg/sec continuous load for 72hrs or more. I am waiting for the experts to get a hang of it and then discuss my changes in greater details. I can spare some cycles to experiment on specific aspect of the C impl from what comes out of our discussion.

**Comment by pzoleex** [comment]
@kira-syslogng test this please;

**Comment by kira-syslogng** [comment]
Build triggered

**Comment by kira-syslogng** [comment]
Build FAILURE
 
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
Closing due to inactivity.

**Pull request closed without merging**
