### PR TITLE
http: remove http-auth-header

### PR DESCRIPTION
**Pull request by lbudai**
There is an internal counterpart of this PR - which re-implements an internal auth-header plugin as a signal-slot plugin.

I think deprecation is not necessary in this case.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by lbudai** [comment]
PR #3288 contains the first patch, I'm closing this.

**Pull request closed without merging**
