### PR TITLE
syslog-ng-otlp: add url to persist name

### PR DESCRIPTION
**Pull request by alltilla**

### CODE REVIEW

**Review by MrAnno — COMMENTED** [review]
In general, we usually implement "persist-name upgrade" in order not to lose persistence information. Do we consider OTLP experimental, or should we care about upgrades?

**Comment by alltilla** [comment]
I think we should take upgrade into account, I will do it, thanks!

**Comment by alltilla** [comment]
@MrAnno Thanks, done!

**Review by MrAnno — APPROVED** [review]
Thanks!

**Pull request merged**
