### PR TITLE
Bugfixes and enhancements to the SELinux policy installer script and syslog-ng-debun

### PR DESCRIPTION
**Pull request by jszigetvari**
Added bugfixes and enhancements to the SELinux policy installer script and syslog-ng-debun

* corrected an OS-detection related bug in the SELinux policy installer's code
* updated syslog-ng-debun's OS-detection code to cope with the same problem
* bumped the version number and updated copyright information
* updated syslog-ng-debun to gather more, useful information
  (these include wec version, lsof-like information if lsof is not installed, information about socket files)

Signed-off-by: Janos SZIGETVARI jszigetvari@gmail.com

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Review by MrAnno — APPROVED** [review]

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by bazsi — APPROVED** [review]
I haven't tested the changes but all of them seem following/improving the conventions that exist in the files it changes. LGTM.

**Comment by MrAnno** [comment]
We're running some internal tests.

**Comment by MrAnno** [comment]
Thanks!

**Pull request merged**
