### PR TITLE
Add Docker image for arm64, update actions

### PR DESCRIPTION
**Pull request by lucacome**
Signed-off-by: Luca Comellini <luca.com@gmail.com>

Adds Docker images for arm64

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by MrAnno** [comment]
Hi @lucacome,

Thank you for opening this PR.

Unfortunately, our Docker images are based on the [APT repository](https://github.com/syslog-ng/syslog-ng#adding-the-apt-repository) we provide, which currently does not support arm64.
(Publishing aarch64 packages would be the first step of supporting arm64 Docker images.)

**Comment by MrAnno** [comment]
@lucacome Those are official Debian packages lagging behind a few versions, not ours.

**Comment by lucacome** [comment]
yeah @MrAnno but that's what the Dockerfile in the project seems to use...

**Comment by MrAnno** [comment]
The purpose of our Dockerfile (and Docker images) would be to always use the latest version of syslog-ng, which is coming from `https://ose-repo.syslog-ng.com/apt/`, an APT repo that is built and hosted by us, syslog-ng developers.

That repository currently does not support aarch64, so with your change, the build of the image falls back using the base image's official repo: `deb.debian.org`. I consider this as an unwanted side-effect because the official Debian repository contains older versions of syslog-ng, and the way they package syslog-ng is slightly different than ours.

**Comment by lucacome** [comment]
ah that makes sense, thanks for the explanation!

**Comment by MrAnno** [comment]
Let's reopen this PR once we have ARM64 packages.

**Comment by MrAnno** [comment]
FYI cloud-ready syslog-ng images are available by Axoflow (arm64 too):
https://github.com/axoflow/syslog-ng-docker/pkgs/container/syslog-ng

**Pull request closed without merging**
