### PR TITLE
config-option-database: remove in favor of a separate pip package

### PR DESCRIPTION
**Pull request by alltilla**
I have rewritten the whole code and created a separate pip package, which can be installed with pipx, so it is much easier to use.

See:
https://github.com/alltilla/syslog-ng-cfg-helper
https://pypi.org/project/syslog-ng-cfg-helper

Signed-off-by: Attila Szakacs <szakacs.attila96@gmail.com>

### CODE REVIEW

**Comment by alltilla** [comment]
@smortex FYI :)

**Comment by smortex** [comment]
Nice!  I am wondering if it would make sense to likewise remove the vim syntax file I recently updated: they are only part of the RPM packages, and for vim users, it is more convenient to have a repository to clone using pathogen / plugged.

We could setup a dedicated repo, e.g. `syslog-ng/vim-syslog-ng` where the main branch has the actual vim config and another branch has the tooling to regenerate new config using your tool when the syntax of syslog-ng is extended.

**Review by MrAnno — APPROVED** [review]
I'd probably add an "`other-`" NEWS entry about where this went.

**Comment by alltilla** [comment]
Thanks, added a news entry.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by alltilla** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by alltilla** [comment]
@smortex 

Good idea!
I have started a discussion, we can continue refining the idea there :) https://github.com/alltilla/syslog-ng-cfg-helper/discussions/1

**Comment by alltilla** [comment]
@kira-syslogng retest this please

**Review by MrAnno — APPROVED** [review]

**Pull request merged**
