### PR TITLE
Makefile.am: Eliminate warning for discarded qualifiers

### PR DESCRIPTION
**Pull request by vivinperis**
fixes: #1964

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by mehul-m-prajapati** [comment]
@vivinperis : You have only changed the Makefile. But, this task requires eliminating the warnings which you will get while compiling all the source files.

For that, you need to change some of the c files code such that `discarded qualifiers` warnings gets removed.

**Comment by vivinperis** [comment]
I tried the statistics method which @furiel suggested. 
It shows that there are 9 [-Wstrict-prototypes] errors. On further reading, I figured out that -Wstrict-prototypes is error restricted to GCC and clang doesn't show. Also, I am not able to see Wignored-qualifiers now.
I went through the error logs and and it started throwing "/KafkaDestinationProperties.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.".
Can someone help me out on how to proceed

**Pull request merged**
