### PR TITLE
github-actions: run jobs nightly

### PR DESCRIPTION
**Pull request by gaborznagy**
A test run on my fork:
https://github.com/gaborznagy/syslog-ng/actions/runs/387375769/workflow

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
would this run only the master nightly or all open PRs?

**Comment by gaborznagy** [comment]
> would this run only the master nightly or all open PRs?

This runs only for master branch.
https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events

**Review by szemere — APPROVED** [review]
Optional: I think this change worth to mention in the developer-notes. (news file) It is a big step towards quality.

**Review by alltilla — APPROVED** [review]
Nice, thanks! Now we should find a way to monitor them on a dashboard :)

**Pull request merged**
