### PR TITLE
libesmtp detection via pkg-config

### LINKED ISSUE #3646: syslog-ng fails to find newer esmtp
# syslog-ng
## Version of syslog-ng
3.30.1

## Platform
Linux Gentoo

# Issue
## Failure
Syslog-ng fails to find libesmtp during compilation:
````
checking for libESMTP... no
configure: error: libESMTP not found
````

## Steps to reproduce
Install newer libesmtp (we used commit c80e46678e1025f3116bdcc75563364744adbe18) and build syslog-ng with smtp support.

# Additional notes
Downstream bug report: https://bugs.gentoo.org/782643
Fix: https://github.com/gentoo/gentoo/blob/master/app-admin/syslog-ng/files/syslog-ng-3.30.1-esmtp-pkgconfig.patch

The newer version of libesmtp (snapshot) drops autotools and dropped its homebrew libesmtp-config utility too. We now have to use pkgconfig to find it.

### PR DESCRIPTION
**Pull request by MrAnno**
> The newer version of libesmtp drops autotools and dropped its homebrew libesmtp-config utility too. We now have to use pkgconfig to find it.

Fixes #3646

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by bazsi — DISMISSED** [review]

**Review by alltilla — APPROVED** [review]

**Comment by alltilla** [comment]
Closed by mistake.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by Kokan** [comment]
Please check cmake.

**Comment by MrAnno** [comment]
libESMTP 1.1.0 has been released:
https://github.com/libesmtp/libESMTP/releases/tag/v1.1.0

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by Kokan — APPROVED** [review]

**Comment by Kokan** [comment]
Thanks.

**Review by gaborznagy — APPROVED** [review]

**Pull request merged**
