### PR TITLE
misc: clean up some duplicate header includes

### PR DESCRIPTION
**Pull request by chunmeng**
Just clean up, no functional impact

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by Kokan** [comment]
@kira-syslogng ok to test

**Comment by Kokan** [comment]
Thanks for the patch. Just two formality. 
* Please remove those merge commits from your branch.
* Add sign-off to your commit with your name and email to make CI happy (https://travis-ci.org/github/syslog-ng/syslog-ng/jobs/701524577)

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by chunmeng** [comment]
> Thanks for the patch. Just two formality.
> 
> * Please remove those merge commits from your branch.
> * Add sign-off to your commit with your name and email to make CI happy (https://travis-ci.org/github/syslog-ng/syslog-ng/jobs/701524577)

Done.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
