### PR TITLE
lib: bump ivykis version on 0.43.2

### PR DESCRIPTION
**Pull request by ikheifets-splunk**
upgrading ivykis for fix [bug](https://github.com/buytenh/ivykis/pull/33)

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by czanik** [comment]
It needs some testing. Version 0.43.1 broke Fedora Linux when I tested. I have yet to test 0.43.2.

**Comment by ikheifets-splunk** [comment]
@czanik thanks for quick answer. We also [had a problem with CentOS7](https://github.com/axoflow/axosyslog/issues/85) with axosyslog 4.7.1 (before it became a fork of syslog-ng) few months ago and by this reason rollbacked on version 4.6.0.

**Comment by HofiOne** [comment]
@kira-syslogng test this please;

**Comment by czanik** [comment]
Tested 0.43.2 on Fedora 39 with the latest syslog-ng git snapshot and this time it worked without any problems. Also tested on FreeBSD, and everything I tested works as expected.

**Review by HofiOne — APPROVED** [review]

**Pull request merged**
