### PR TITLE
configure/cmake: support python configuration with "python" prefix

### PR DESCRIPTION
**Pull request by alltilla**
A little background of my motivation:

I am working on introducing GitHub Actions to the syslog-ng repo, where we have an option to run jobs with multiple variable options. These options get added to the jobs name during run like:
> job (foo, bar)

I would like to use two options:
```
python: python2/python3
build-tool: autotools/cmake
```

I am using the `python` option in the configure step, where if we do not allow `--with-python=python2` just `--with-python=2`, I have to change the option to:
```
python: 2/3
```
, which would name the job like 
> job (2, autotools)

, which is not so pretty as 
>job (python2, autotools)

Signed-off-by: Attila Szakacs <attila.szakacs@oneidentity.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by lbudai** [comment]
could you provide more details (I mean code) on where you are using these options?

**Comment by alltilla** [comment]
I am not on the computer, so I can only give these links, but I think they show my intention.

Example CI run: https://github.com/alltilla/syslog-ng/actions/runs/69784772

It's workflow file: https://github.com/alltilla/syslog-ng/actions/runs/69784772/workflow

**Comment by furiel** [comment]
Are there any alternatives? Is it possible to `cut` the variable in the github actions yaml file?

**Comment by alltilla** [comment]
@furiel: Sure it is possible, but I don't see the drawback of letting everyone use the "python" prefix.

**Comment by furiel** [comment]
We are talking about personal preferences. Not necessarily a must from my side, but here are my reasons.

For me it would be a little confusing. The `with-python` processing is already very complex. It is less about choosing between python2 or python3, but finding an appropriate pkg config file on the system. Whatever is specified with the `with-python`, it is explicitely mapped to a pc file.
For me this is a conceptual change.

I am not confortable with the trigger either. We are trying to achieve a cosmetic change in a tool that uses our build system by reshaping our build system, and not the ci tool. This is wrong direction of dependency.

**Comment by alltilla** [comment]
@furiel 
Sure, I see your point. It's okay, I will drop the PR. We will know the meaning behind `job (2, autotools)`.

**Pull request closed without merging**
