### PR TITLE
Filterx error handling

### PR DESCRIPTION
**Pull request by bazsi**
This PR implements an error handling for filterx expressions, so the key "error" cases are reported as statements
are evaluated.

It just covers variables/setattr/getattr/set-subscript/get-subscript

Functions are not covered yet.

This sits on top of #4885

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Review by alltilla — DISMISSED** [review]

**Review by alltilla — APPROVED** [review]

**Pull request merged**
