### PR TITLE
Secure logging project step 1

### LINKED ISSUE #3289: secure-logging module errors on 32-bit architectures
# syslog-ng
## Version of syslog-ng
syslog-ng 3.27.1 and some earlier versions

## Platform
Linux i686 (and many other 32-bit)

# Issue
## Failure
Test suite fails in secure-logging module:
FAIL: modules/secure-logging/tests/test_secure_logging
(when comparing first encoded-decoded message, even timestamps differ - the decoded one is 0)

It's caused by mixing guint64 and gsize/size_t types (and pointers to them), which differ on ILP32 architectures (gsize/size_t is 32-bit).

Fixing all compiler warnings in secure-logging module also fixes this test.
Proposed patch is attached.
[syslog-ng-types.patch.gz](https://github.com/syslog-ng/syslog-ng/files/4607496/syslog-ng-types.patch.gz)

### PR DESCRIPTION
**Pull request by nbsd**
This pull request contains changes from the [GitHub project](https://github.com/orgs/syslog-ng/projects/1) that was set up by the **syslog-ng** team to enhance the secure logging module. It includes all changes that were previously marked as _in progress_ and have been now been transferred to the next step called _review in progress_. However, the project is not yet finished, as some items still remain on the to do list.

Fixes #3289

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by Kokan** [comment]
@kira-syslogng ok to test

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
Reminder: after merging this PR, we should get rid of the `cmake_build=1` environment vars (test exclusions) in our CI environment (GitHub Actions, Travis, Light).

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by nbsd** [comment]
Thanks you very much for pointing me to the imbalance of g_new0() and g_free() calls. This was simply an oversight is now corrected.

**Comment by MrAnno** [comment]
@nbsd Thanks. You can just cherry-pick the commit if you're OK with it.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
