### PR TITLE
Legendary Kira PR is back again :)

### PR DESCRIPTION
**Pull request by mitzkia**
- This PR is for debugging Kira test jobs
- Please do not merge and do not delete this

### CODE REVIEW

**Comment by mitzkia** [comment]
@kira-syslogng test this please;

**Comment by mitzkia** [comment]
@kira-syslogng test this please test branch=followup_log_level_changes;

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by mitzkia** [comment]
@kira-syslogng test this please test branch=followup_log_level_changes;

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by mitzkia** [comment]
@kira-syslogng test this please test branch=followup_log_level_changes;

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by mitzkia** [comment]
@kira-syslogng test this please test branch=followup_log_level_changes;

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by MrAnno** [comment]
@kira-syslogng do stresstest

**Comment by kira-syslogng** [comment]
Kira-stress-test: Build SUCCESS

**Comment by mitzkia** [comment]
@kira-syslogng test this please;

**Comment by MrAnno** [comment]
@kira-syslogng retest this please

**Pull request closed without merging**
