### PR TITLE
Filterx primitive object caching

### PR DESCRIPTION
**Pull request by bazsi**
This branch introduces object caching for booleans, small integers and nulls, so we avoid allocating them during the
evaluation of the filterx language.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Review by alltilla — APPROVED** [review]

**Pull request merged**
