### PR TITLE
CI Python Fixes

### PR DESCRIPTION
**Pull request by therandomstring**
This PR fixes multiple light test failures caused by python dependency upgrades.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kovgeri01** [comment]
lgtm

**Review by kovgeri01 — APPROVED** [review]

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Pull request merged**
