### PR TITLE
Forward integrity and confidentiality of logs

### PR DESCRIPTION
**Pull request by nbsd**
Logs processed by syslog-ng are neither confidential nor integrity protected. The use of these logs for the purpose of security monitoring and forensic analysis in case of an incident is rather limited, as they may have been tampered with by an attacker trying to hide his trace.

The implementation providing forward integrity and confidentiality of logs using syslog-ng was recently presented at the [FOSDEM 2020](https://fosdem.org/2020/schedule/event/security_secure_logging_with_syslog_ng) is included in this pull request. 

This pull request is related to issue #3118.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by e-o-blass** [comment]
Please delete this pull request. It contains sensitive data.

**Pull request closed without merging**
