### PR TITLE
Missing news entries since 3.31.1 release

### PR DESCRIPTION
**Pull request by Kokan**
There were a few news entry not written, or at that time marked as not needed.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by alltilla** [comment]
I think `news/news-3565.md` should be `news/feature-3565.md` instead.

**Review by szemere — DISMISSED** [review]
Thank You!

**Comment by Kokan** [comment]
@alltilla yeah, you are right. moved the file.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by alltilla — APPROVED** [review]

**Review by szemere — APPROVED** [review]

**Pull request merged**
