### PR TITLE
Fixed Fedora Rawhide not Building in DBLD

### PR DESCRIPTION
**Pull request by therandomstring**
This build failure was caused by wget linking to a different version library than what it was built with. This was fixed by transitioning duilddeps to use curl.
This PR also adds a package update to the testing images to ensure they are up-to-date and provide better early warning capabilities for breaking changes in their respective OS family.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Review by kovgeri01 — APPROVED** [review]
fyi the codeql job is flaky for some reason, feel free to ignore it's results

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Review by kovgeri01 — APPROVED** [review]
lgtm

**Pull request merged**
