### PR TITLE
Mark Changes

### PR DESCRIPTION
**Pull request by nguyenfilip**
Currently, upon start or reload of configuration, first mark message comes only
after mark_freq. So in effect any restart/reload causes next mark to be delayed.

In addition to that, when many syslog-ng daemons start at the same
time, the mark messages are going to be correlated and may cause spikes
of those MARK's every time mark_freq passes.

This change aims to do the following. When periodical marks are used, emit first
mark as soon as possible after start/reload and then schedule second mark with
random delay in interval <1, mark_freq>.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by lbudai** [comment]
@kira-syslogng : ok to test

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by nguyenfilip** [comment]
@lbudai do you suggest just to hide this feature behind a config option. Or is there some other extension point/programming model in syslog-ng that I use?

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
I am not sure we would need an explicit option if the randomized distribution of mark messages make better sense than what we are doing today.

Can you offer more background information on why you think the new behaviour is better? What problem are you solving?

Also, if we were to randomize marks, I wouldn't spread them over mark_freq, that seems to be a bit too much, spreading them over a few seconds should solve spikes just as well. Also, I am not yet convinced synchronized MARKs cause that much headache. Are you reloading tens of thousands of syslog-ng instances in a synchronized manner?

Thanks

**Comment by lbudai** [comment]
@bazsi : I would not break compatibility.

I'm not questioning that the presence of a relatively huge number of simultaneous mark messages could be a problem in _some_ environments but I think randomized mark messages should not be the default.
I understand that the generation time of an individual mark message is a stochastic variable...

On the other hand, I do not see any problems with making this optional...

@nguyenfilip : yes, just add a new config option for enabling the randomized function
But at first, try to answer the questions from @bazsi .

**Comment by MrAnno** [comment]
Sorry, the PR was closed accidentally (misclick). I'm reopening, because @lbudai just turned off his computer.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by lbudai** [comment]
@nguyenfilip : any update on this?

**Comment by furiel** [comment]
Closing due to inactivity. Please reopen if you can share more about the use usecase, or need help from us about the implementation.

**Pull request closed without merging**
