### PR TITLE
WIP: block-name: First implementation of feature #2964

### LINKED ISSUE #2964: Rotate log files based on size
## Description of the problem
When using the logrotate with common configuration, log entries can be lost between the time in which the logrotate copies the file and the truncate of the file.

## Proposed solution
I suggest to rotate the log within syslog-ng based in a file size limit configuration parameter. Additionally one parameter with the desired suffix can be added.
I try was already done in https://github.com/pld-linux/syslog-ng/blob/master/log-file-size-limit.patch

## Alternatives
Add a disk buffer and reliable properties in syslog-ng configuration for each log file, and configure in logrotate the restart of syslog-ng in the end of each rotation. This solution has the disadvantage of periodically have to restart the syslog-ng. Potentially it can be too many restarts of syslog-ng depending on number of logs, size limits, and events recorded.

## Additional context
Already have a patch ready

### PR DESCRIPTION
**Pull request by amdrsantos**
Rotation of log files when the file reaches a size limit.

Fixes #2964 

Signed-off-by: Alexandre Santos <alexandre.rosas.santos@gmail.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by szemere** [comment]
ok to test

**Comment by bazsi** [comment]
The reason we didn't integrate similar functionality in the past was that the rotation is a pretty complicated topic that I would prefer to keep out of the file driver code. However I find out of the box support for this kind of use case valueable.

The way this should be solved in my mind is to introduce driver specific events

**Comment by amdrsantos** [comment]
Ok. I will try to work in a plugin.

Can you point me some example in the code?

**Comment by bazsi** [comment]
There's no example right now as the framework doesn't exist yet. 

The outline of the framework would be something like this:
* We will need a way to represent a hook function (function pointer plus name-value pairs as arguments)
* We will need a way to represent registrations against those hooks (like a hash table, keyed with the hook's name, containing a list of hook functions to be invoked) this would be associated with the LogDriver instance that emit the events
* we can probably use the inner-dest/inner-source plugin interfaces to instantiate the plugins that receive the events and where we can do the actual registrations against the hooks
* We will need an API for doing the registrations that can validate that a specific hook exists for a specific plugin and another API for doing a hook invocation.
* Once we have this, we only need to add hook invocations to the file destination in case of file size rollovers and another plugin to receive the event (which will also do the rotation).
* I would also extend hook commands to allow registration to any existing hook to invoke a command.

At the end I would check if:
* Acquire_queue mechanism could use the same or not.
* The current overwrite_if_older mechanism could use this or not

**Comment by alltilla** [comment]
@amdrsantos 
Hi Alexandre,

Did you have any progress with the PR since your last comment, are you planning to work on it? Can we give you any help with it?

Attila

**Comment by amdrsantos** [comment]
Hi Attila,

Right now I do not have the time to spend in this development.
The log rotation is implemented using the program() destination option of
syslog-ng.

The script implementing this functionality receive as parameter: the log
file name, the maximum log file size and the maximum of log files it can
get. It is running in daemon mode following the sequence:

1. Is actively listening its stdin;
2. Receives the message and writes to the correspondent log file;
3. Checks if the size of log file is greater than the specified MAX_SIZE
4. If 3. Is true,
       a. Generates a temporary logrotate configuration file for the
correspondent log file
       b.Calls logrotate with the generated logrotate configuration file
       c. Deletes the temporary logrotate configuration file
5. Go to step 1

I will try to come back to the improvement in syslog-ng as soon as I can.

Cheers,
Alex

**Comment by Kokan** [comment]
@amdrsantos Closing due to your response not having time to deal with this, and @bazsi comment about different approach to reach the final goal.

**Comment by bazsi** [comment]
The framework was created and incorporated into http (the signal-slot mechanism), so this should be much easier to implement now.

**Pull request closed without merging**
