### PR TITLE
Fix removed libesmtp from debian testing

### PR DESCRIPTION
**Pull request by kovgeri01**
As of 2024-08-01 debian removed libesmtp from debian:testing:
https://tracker.debian.org/news/1550783/libesmtp-removed-from-testing/

This will change the dbld from mainly using debian-testing to debian bookworm to reduce issues like this

### CODE REVIEW

**Comment by kovgeri01** [comment]
I just wanted to make sure this was out issue on debian testing.

@czanik I am no expert on debian processes will it be re-included or whould we disable in the mean time?

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kovgeri01** [comment]
never mind I am still on it, it is not really a good idea to disable it everywhere (all platform that has debian packaging)

**Review by HofiOne — APPROVED** [review]

**Pull request merged**
