### PR TITLE
version: 3.26

### PR DESCRIPTION
**Pull request by alltilla**
Signed-off-by: Attila Szakacs <attila.szakacs@oneidentity.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by lbudai** [comment]
hmmm... I'd prefer a version change PR like I did previously: I changed each 'layer'  in a separate commit. I'm opening a new PR.

**Comment by gaborznagy** [comment]
@lbudai then please include the python versioning improvements introduced this as well...

**Comment by lbudai** [comment]
@gaborznagy: as I mentioned in the internal slack channel, I included a refactor. Am I missed something else?

**Comment by alltilla** [comment]
Closing in favor of #3163

**Pull request closed without merging**
