### PR TITLE
Version: 4.1.1

### PR DESCRIPTION
**Pull request by kira-syslogng**
Tarball is available at: https://github.com/syslog-ng/syslog-ng/actions/runs/4384139583

### CODE REVIEW

**Comment by bazsi** [comment]
This looks good to me. Thanks

**Comment by czanik** [comment]
Is the SLES 12 fix included?

**Comment by bazsi** [comment]
No, there was no PR from that since #4359

**Comment by bazsi** [comment]
I just pushed a fix on top of this PR to add the missing include.

**Review by MrAnno — APPROVED** [review]

**Comment by kira-syslogng** [comment]
**Draft release** workflow started: https://github.com/syslog-ng/syslog-ng/actions/runs/4385445222.

**Comment by kira-syslogng** [comment]
**Draft release** workflow finished successfully. Please check the Releases page: https://github.com/syslog-ng/syslog-ng/releases

**Pull request merged**
