### PR TITLE
Install bison on kira

### PR DESCRIPTION
**Pull request by gaborznagy**
This is just a test, to see if kira would work on top of #3547

### CODE REVIEW

**Comment by gaborznagy** [comment]
@kira-syslogng test this please;

**Comment by gaborznagy** [comment]
@kira-syslogng retest this please;

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by gaborznagy** [comment]
@kira-syslogng retest this please;

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request closed without merging**
