### PR TITLE
Fix dbld package build/creation

### LINKED ISSUE #3076: dbld/rules rpm-centos-7 broken
Tested with this mornings git snapshot, when I try to build CentOS 7 binaries with ```dbld/rules rpm-centos-7``` it fails with the following error:

```
[...]
tardir=syslog-ng-3.25.1.65.gb4accf6 && tar --format=ustar -chf - "$tardir" | eval GZIP= gzip --best -c >syslog-ng-3.25.1.65.gb4accf6.tar.gz
if test -d "syslog-ng-3.25.1.65.gb4accf6"; then find "syslog-ng-3.25.1.65.gb4accf6" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "syslog-ng-3.25.1.65.gb4accf6" || { sleep 5 && rm -rf "syslog-ng-3.25.1.65.gb4accf6"; }; else :; fi
Your tarball is in /build, also available on the host in $(top_srcdir)/dbld/build
docker run -e USER_NAME_ON_HOST=root --network=host --privileged --ulimit nofile=1024:1024 -v /root/syslog-ng:/source -v /root/syslog-ng/dbld/build:/build -v /root/syslog-ng/dbld/install:/install -e CONFIGURE_OPTS="${CONFIGURE_OPTS:---enable-debug --enable-manpages --with-python=2 --prefix=/install }" -e CCACHE_DIR=/build/ccache -e VERSION=3.25.1.65.gb4accf6 -e PATH=/usr/lib/ccache:/usr/lib64/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin -e GRADLE_USER_HOME=/build/gradle-home -e GRADLE_PROJECT_CACHE_DIR=/build/gradle-cache -e GRADLE_FLAGS=--build-cache  --rm -i balabit/syslog-ng-ubuntu-bionic /source/dbld/pkg-tarball snapshot
Generating snapshot version in debian/
Generating snapshot version in syslog-ng.spec
docker run -e USER_NAME_ON_HOST=root --network=host --privileged --ulimit nofile=1024:1024 -v /root/syslog-ng:/source -v /root/syslog-ng/dbld/build:/build -v /root/syslog-ng/dbld/install:/install -e CONFIGURE_OPTS="${CONFIGURE_OPTS:---enable-debug --enable-manpages --with-python=2 --prefix=/install }" -e CCACHE_DIR=/build/ccache -e VERSION=3.25.1.65.gb4accf6 -e PATH=/usr/lib/ccache:/usr/lib64/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin -e GRADLE_USER_HOME=/build/gradle-home -e GRADLE_PROJECT_CACHE_DIR=/build/gradle-cache -e GRADLE_FLAGS=--build-cache  --rm -i  balabit/syslog-ng-centos-7 /source/dbld/rpm
Running build as:  env rpmbuild --define _dbld 1 -ta syslog-ng-3.25.1.65.gb4accf6.tar.gz --without kafka --with python2
error: File /build/syslog-ng-3.25.1.tar.gz: No such file or directory
make: *** [dbld/rules:122: rpm-centos-7] Error 1
```

### PR DESCRIPTION
**Pull request by gaborznagy**
Recently in commit b17153c lsb-release package is removed form every image
except from the new kira image.
This caused that devshell image (or where debug symbols needed) cannot be built
as neither devshell image or its base image ubuntu-bionic did not contain lsb-release.

I've tried adding it devshell region in package.manifest,
but it should be in its base image, then it did not work because of other dependency tangles...

I've also renamed `enable_dbgsyms` function as it works on ubuntu only.

Fixes #3076

### CODE REVIEW

**Comment by gaborznagy** [comment]
@kira-syslogng Build packages please;

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
This is failing due to 2 reasons:
- `The repository 'http://archive.ubuntu.com/ubuntu cosmic Release' does not have a Release file.` Cosmic is EOL, their repos have been removed I guess.
- Centos 7: `Running build as:  env rpmbuild --define _dbld 1 -ta syslog-ng-3.25.1.314.gd44c0ad.tar.gz --without kafka --with python2
error: File /build/syslog-ng-3.25.1.tar.gz: No such file or directory`

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by gaborznagy** [comment]
Set it to WIP, we try to resolve every issue: https://github.com/syslog-ng/syslog-ng/pull/3143#issuecomment-592437127

**Comment by bazsi** [comment]
Hmm, I was copying to the root as rpmbuild didn't find the one in the subdirectory. I remember trying. Poo

**Comment by MrAnno** [comment]
I don't know what has happened since then, but now rpmbuild seems to find and even prefer the one under `packaging/rhel` in the CentOS 7 image, so I've removed all copies to avoid confusion. I might have overlooked something, but we'll double-check everything with Jenkins once Gábor accepts gaborznagy/pull/5.

**Comment by gaborznagy** [comment]
@kira-syslogng Build packages please;

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
One (hopefully last) remaining issue:

```
error: Installed (but unpackaged) file(s) found:
   /usr/lib64/syslog-ng/libazure-auth-header.so
   /usr/share/man/man1/persist-tool.1.gz
    Installed (but unpackaged) file(s) found:
   /usr/lib64/syslog-ng/libazure-auth-header.so
   /usr/share/man/man1/persist-tool.1.gz
```

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by gaborznagy** [comment]
@kira-syslogng Build packages please;

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by gaborznagy** [comment]
@kira-syslogng Build packages please;

**Comment by kira-syslogng** [comment]
Package Build SUCCESS

Packages are available at https://ci.syslog-ng.com/jenkins/job/kira-dbld-pull-requests/625/artifact/

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by gaborznagy** [comment]
@kira-syslogng Build packages please;

**Comment by kira-syslogng** [comment]
Package Build SUCCESS

Packages are available at https://ci.syslog-ng.com/jenkins/job/kira-dbld-pull-requests/626/artifact/

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by gaborznagy** [comment]
@kira-syslogng Build packages please;

(I have forgot ubuntu-trusty were not tested.)

**Comment by kira-syslogng** [comment]
Package Build SUCCESS

Packages are available at https://ci.syslog-ng.com/jenkins/job/kira-dbld-pull-requests/627/artifact/

**Comment by gaborznagy** [comment]
:fireworks:

**Pull request merged**
