### PR TITLE
News entry and Readme update for the upcoming syslog-ng OSE APT repository

### PR DESCRIPTION
**Pull request by MrAnno**

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by alltilla — DISMISSED** [review]
We can merge this, and change [DRAFT] in the version bump PR.

**Comment by MrAnno** [comment]
Removed the "Draft" flag.

I can also replace the masked URLs with the final domain name in this PR, if you want to.
I think it won't cause any problems as we purged everything, we only have the previous v3.34.1 release and a few nightly snapshots in the repo.

**Comment by MrAnno** [comment]
I'd prefer doing it in this PR because I also modified the README as well.

**Comment by alltilla** [comment]
@MrAnno Sure, go for it :)

**Comment by MrAnno** [comment]
Thanks. Done.

**Review by alltilla — APPROVED** [review]
Yaay!

**Comment by kira-syslogng** [comment]
Build FAILURE

**Review by Kokan — APPROVED** [review]

**Pull request merged**
