### PR TITLE
ci: fix syntax error in output parameter generation

### PR DESCRIPTION
**Pull request by MrAnno**
A syntax error has been introduced in #4231.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by MrAnno** [comment]
@HofiOne Something is not okay with internal tests, Kira has issues with a PE-only WEC test case:

```
File /mnt/jenkins/workspace/kira-test-compile-automake-run-testdb/syslog-ng-pe-testdb/functions/source-drivers/wec/019-wec-bookmark-handling-subs-name-change.zts:8 in <module>
23:31:54 #     'platform': get_specified_linux_from_list(all_linux, 19),
23:31:54 #   File /mnt/jenkins/workspace/kira-test-compile-automake-run-testdb/syslog-ng-pe-testdb/ZTS/Globals/Functions.py:94 in get_specified_linux_from_list
23:31:54 #     raise Exception("No item in the list.")
23:31:54 # 
```

**Comment by bazsi** [comment]
How can I check if this is correct? I mean the last one did look right, was green in CI, what else should I check?

**Comment by MrAnno** [comment]
These are non-PR jobs unfortunately.
I check them manually in my fork:
https://github.com/MrAnno/syslog-ng/actions/runs/3783747491

**Review by bazsi — APPROVED** [review]

**Comment by bazsi** [comment]
kira is still failing, hopefully we can get that fixed. in the meanwhile I am merging this and keep a good look at our nightly jobs.

**Comment by bazsi** [comment]
just in time for our today's nightly at 11pm, that's in 32 mins

**Comment by bazsi** [comment]
It's 11pm UTC, so it should have started by now. Interestingly yesterday's
job started 11:15pm UTC. Maybe github is randomizing the jobs so they
spread around a bit.

**Comment by MrAnno** [comment]
As far as I see, it starts around 12:15 every night.
https://github.com/syslog-ng/syslog-ng/actions/workflows/nightly-release.yml

**Pull request merged**
