### PR TITLE
http: Bugfix: http dd does not detect cURL compression support

### PR DESCRIPTION
**Pull request by therandomstring**
So far the compilation of http_dd with compression options only detected the presence of Zlib. This caused a compilation error when Zlib was found, but cURL on the system has been compiled without it.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
I have cleaned up this patch and compression support somewhat. I am not saying I am perfectly happy, but things improved a lot. I have updated this branch by forcepushing to the original branch @therandomstring 

I have manually tested the code with compression enabled and it does work, but there was a lot of churn. Some more testing would be appreciated.

**Comment by bazsi** [comment]
I am merging these with my latest changes. That moves the http compression implementation to something closer to what I would expect.

I've also fixed a bug which caused the "Content-Encoding" header to be included in each request 16 times (more exactly the number of workers times)

**Review by alltilla — APPROVED** [review]

**Comment by kira-syslogng** [comment]
Build FAILURE

**Pull request merged**
