### PR TITLE
syslog parser fix crash during handling short inputs

### LINKED ISSUE #3328: Abnormal message causes Segmentation fault
# syslog-ng
## Version of syslog-ng
```
syslog-ng 3 (3.27.1)
Config version: 3.22
Installer-Version: 3.27.1
Revision:
Module-Directory: /usr/local/lib/syslog-ng
Module-Path: /home/sense/test-fuzz/syslog-ng-3.27.1/inst/usr/local/lib/syslog-ng
Include-Path: /usr/local/share/syslog-ng/include
Available-Modules: stardate,basicfuncs,add-contextual-data,xml,examples,hook-commands,disk-buffer,appmodel,azure-auth-header,confgen,map-value-pairs,afsocket,affile,tfgetent,graphite,syslogformat,cryptofuncs,kvformat,secure-logging,cef,linux-kmsg-format,csvparser,tags-parser,afprog,afsql,afuser,timestamp,system-source,pseudofile,dbparser
Enable-Debug: on
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off
Enable-Systemd: off
```

## Platform
Debian 10

## Issue
The message, that contains just bytes: "4\0  " causes Segmentation fault

## Steps to reproduce
```
printf '4\0  ' | syslog-ng \
        --foreground \
        --cfgfile=$CONFIG
Segmentation fault
```

## Configuration
```
@version:3.22

source s_src {
        stdin(follow-freq(1));
};

destination d_dst {
        file("/tmp/dest.log");
};

log {
        source(s_src);
        destination(d_dst);
};
```

### PR DESCRIPTION
**Pull request by Kokan**
Fixes #3328.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by furiel** [comment]
Looks good to me. If not too difficult, could you add a unit test for this case?

**Comment by Kokan** [comment]
@furiel Do you want me to add test for the case of skipping sequence id, or crashing due to short input ? Either of those UT are not difficult.

If possible I would avoid adding a test cases that was generated with fuzzing. The reason that I could add a lot of them, and instead the idea is to add a test that does fuzzing as the input generated by fuzzer that actually causes crashes are implementation dependent. I would rather create UT based on functionality and on coverage bases.

The fuzzer test is actually on its way, I just curved this PR out of it as it was possible to do so.

Do you think that it would still worth to add such case ?

**Comment by furiel** [comment]
@Kokan I agree the tests by the fuzzer are superior. Thanks!

**Pull request merged**
