### PR TITLE
tlscontext: add workaround for a TLS 1.3 bug to prevent data loss

### PR DESCRIPTION
**Pull request by MrAnno**
This is a workaround for an OpenSSL TLS 1.3 bug that results in data loss when one-way protocols are used and a connection is closed by the client right after sending data.

"TLS 1.3 session tickets make it impossible to reliably implement communication patterns where the server never sends application-level data."

- https://github.com/openssl/openssl/issues/10880
- https://github.com/openssl/openssl/issues/7948

`SSL_CTX_set_num_tickets(0)` disables TLS 1.3 session tickets (no session ticket will be sent to the client after a full handshake). Tickets are used for session resumption.

An alternative workaround would be doing a bidirectional SSL shutdown (finishing #2811), but syslog-ng is usually used together with other applications that may not take the bidi shutdown step (it is not mandatory, not even in RFC5425).

### CODE REVIEW

**Comment by MrAnno** [comment]
@kira-syslogng do perftest

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Kira-performance-test: Build SUCCESS

**Comment by furiel** [comment]
I am not understanding the context entirely, just coming from the man page:

https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_num_tickets.html

> The default number of tickets is 2; the default number of tickets sent following a resumption handshake is 1 but this cannot be changed using these functions. The number of tickets following a resumption handshake can be reduced to 0 using custom session ticket callbacks (see SSL_CTX_set_session_ticket_cb(3)).

Should this mean we need to have a `SSL_CTX_set_session_ticket_cb` somewhere as well?

**Comment by furiel** [comment]
Never mind, probably not necessary. If tickets disabled, resumption cannot happen, therefore it does not matter how many tickets we send after resumption.

**Comment by furiel** [comment]
Do we need to take care of loggen too? Inside `open_ssl_connection`  in `loggen_helper.c`?

**Comment by furiel** [comment]
Ok loggen is client only, so not affected.

**Pull request merged**
