### PR TITLE
RHEL 7 packaging: fix logrotate file conflict with rsyslog

### LINKED ISSUE #1384: Yum Install dependency collision with rsyslog
# syslog-ng

## Version of syslog-ng
latest (3/14/17)
```

## Platform

RHEL7

# Issue
syslog-ng fails to install via standard yum install.

## Failure
syslog-ng package wants to write to /etc/logrotate.d/syslog.  Systems with rsyslog installed report this as a dependency violation.

## Optimal fix
configure package to use /etc/logrotate.d/syslog-ng to avoid future collision.

### PR DESCRIPTION
**Pull request by MrAnno**
Fixes #1384

> I had long discussions with Red Hat about it, but renaming it to syslog-ng does not work.
https://github.com/syslog-ng/syslog-ng/issues/1384#issuecomment-286978553

More info: https://github.com/syslog-ng/syslog-ng/issues/1384#issuecomment-644716350

### CODE REVIEW

**Comment by MrAnno** [comment]
@kira-syslogng build packages please

**Comment by MrAnno** [comment]
@czanik Please tell us when you backport this to the "official" syslog-ng package in EPEL 8.
Thanks for the patch. :+1:

**Comment by kira-syslogng** [comment]
Package Build SUCCESS

Packages are available at https://ci.syslog-ng.com/jenkins/job/kira-dbld-pull-requests/691/artifact/

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
There was a comment from Evan on the mailing list iirc, where he had
concerns about the rename of the logrotate file. Are we handling that
somehow?

**Comment by czanik** [comment]
No, there is nothing we can do here. In RHEL 8 the rsyslog package has its logrotate file as /etc/logrotate.d/syslog, but has rsyslog specific part in it (reloading rsyslog). If we copy an rsyslog-related logrotate file to /etc/logrotae.d/syslog-ng then the config in the syslog-ng-logrotate subpackage would not overwrite it and would not work.

**Comment by bazsi** [comment]
What if we ran sed against the config file on installation?

**Comment by czanik** [comment]
No. I ran into too many sed magic fixing corner cases in syslog-ng packaging and causing hard to debug problems later on.

**Comment by MrAnno** [comment]
https://lists.balabit.hu/pipermail/syslog-ng/2020-June/025949.html

**Comment by czanik** [comment]
[syslog-ng.spec.diff.txt](https://github.com/syslog-ng/syslog-ng/files/4820846/syslog-ng.spec.diff.txt)
I did not receive any further feedback, but as it resolves both the original problem (rsyslog & syslog-ng together) and Evan's problem (name change) I think it's good enough. Tested on Fedora 31, CentOS 7 and CentOS 8, and worked everywhere as expected.
As usual, I lack necessary git skills, so ere is a new diff for syslog-ng.spec. I removed my other changes (related to removing java modules). The changelog part is also a bit messed up...

**Comment by MrAnno** [comment]
Thanks. PR updated.

**Comment by MrAnno** [comment]
@kira-syslogng build packages, please

**Comment by kira-syslogng** [comment]
Package Build SUCCESS

Packages are available at https://ci.syslog-ng.com/jenkins/job/kira-dbld-pull-requests/693/artifact/

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
