### PR TITLE
Fix macOS CI

### PR DESCRIPTION
**Pull request by MrAnno**
Based on https://github.com/Homebrew/homebrew-core/blob/master/Formula/syslog-ng.rb

This fixes the macOS CI (the image seems to be updated and contains a broken net-snmp installation).

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Review by bazsi — DISMISSED** [review]

**Comment by MrAnno** [comment]
This makes the macOS CI job green on master (an environmental change caused the issue). @HofiOne @bazsi @therandomstring Please take a look and merge it, when you can.

**Review by HofiOne — COMMENTED** [review]
I think we need to use brew --prefix everywhere instead (especially on os versions where brew is keg-only now)

sg. like

`export HOMEBREW_PREFIX=$(brew --prefix)`
`export PATH=${HOMEBREW_PREFIX}/opt/bison/bin:${HOMEBREW_PREFIX}/opt/libnet/bin:${HOMEBREW_PREFIX}/opt/net-snmp/sbin:$PATH`
`export PKG_CONFIG_PATH=${HOMEBREW_PREFIX}/opt/openssl@1.1/lib/pkgconfig:${HOMEBREW_PREFIX}/opt/net-snmp/lib/pkgconfig:$PKG_CONFIG_PATH`

**Comment by bazsi** [comment]
> @MrAnno I think we need to use brew --prefix everywhere instead (especially on os versions where brew is keg-only now)
> 
> sg. like
> 
> `export HOMEBREW_PREFIX=$(brew --prefix)` `export PATH=${HOMEBREW_PREFIX}/opt/bison/bin:${HOMEBREW_PREFIX}/opt/libnet/bin:${HOMEBREW_PREFIX}/opt/net-snmp/sbin:$PATH` `export PKG_CONFIG_PATH=${HOMEBREW_PREFIX}/opt/openssl@1.1/lib/pkgconfig:${HOMEBREW_PREFIX}/opt/net-snmp/lib/pkgconfig:$PKG_CONFIG_PATH`

I don't have an opinion, so please disregard my previous approve here, honestly I have no clue about brew.

If you have a conclusion that runs green and all of you agree with it I can live with it.

**Comment by MrAnno** [comment]
@HofiOne Good idea, I'm fixing it. Thanks.

**Review by HofiOne — APPROVED** [review]

**Comment by kira-syslogng** [comment]
Build FAILURE

**Pull request merged**
