### PR TITLE
Add rewrite rule to rename a macro

### PR DESCRIPTION
**Pull request by faxm0dem**
```
rewrite { rename(source('old_name'), destination('new_name')); };
```

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
@faxm0dem Thanks for opening this.

This PR is a result of an IRC conversation with @faxm0dem.
He used regexp filters with store-matches (the same applies to `regexp-parser()` as well), where named capture groups can not contain dots (due to a PCRE limitation), so when a simple one-depth prefix is not enough, values need to be renamed manually.
But in general, `rename()` might be useful in other use-cases.

IMHO `rename()` is a nice rewrite rule, maybe we should consider implementing it natively, but I personally like the SCL too. :)

**Comment by MrAnno** [comment]
These are my thoughts on the native version:

- Performance (but I don't see that it could be significant)
- Debugging the native version may be a bit easier (preprocess-into, debug/trace messages, etc.)
- Another, but really really weak reason would be the fact that a native `rename()` could work without including `scl.conf`.

But again, I do like this SCL, so I think we could make it merge ready, if no one implements the native `rename()` until v3.35.
(We can replace the SCL with the native implementation whenever we want.)

**Comment by faxm0dem** [comment]
ok, so I'll move forward and implement the corner cases using `if`s or `channels`

**Comment by bazsi** [comment]
I just wanted to mention, that I have another use-case for renaming name-value pairs, which I would prefer to do natively, namely I would like to be able to "shift" the name-value pairs that store matches (e.g. $1, $2, etc), similarly how bash can do that.

With that we could have limited array support for processing JSON arrays, which I am experimenting with in #3768

**Comment by MrAnno** [comment]
Wow, it would be really cool :)

**Comment by bazsi** [comment]
I've just merged #3841 which solves this via native code, also handling all the corner cases correctly. Closing this in favour of that one. Thanks @faxm0dem for suggesting/working on this.

**Pull request closed without merging**
