### PR TITLE
Merge snmp modules

### PR DESCRIPTION
**Pull request by lbudai**
As a first step, I'm working only on snmpdest.
Unfortunately `snmp` as name cannot be used ... net-snmp defines `snmp_error()`.
So I'm using the good old 'AF' prefix ;)

update: it is ready to review.

### CODE REVIEW

**Comment by lbudai** [comment]
@kira-syslogng : build packages please

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by lbudai** [comment]
First results seems promising ... (Distro packages job is partially failed, rpm package generation seems to be broken, independently from this changeset).

**Comment by lbudai** [comment]
@kira-syslogng : build packages please

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by lbudai** [comment]
@kira-syslogng : build packages please

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by lbudai** [comment]
@kira-syslogng : build packages please

**Comment by kira-syslogng** [comment]
Package Build FAILURE

**Comment by lbudai** [comment]
Distro packages failure: not caused by this PR...

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
