### PR TITLE
Refactor evt_tag_printf() to evt_tag_mem() where possible

### PR DESCRIPTION
**Pull request by dkl**
As mentioned in https://github.com/syslog-ng/syslog-ng/pull/4064, `evt_tag_printf(..., "%.*s", ...)` can be refactored to `evt_tag_mem()` in many places. There are some uses remaining which can not be trivially converted, for example `evt_tag_printf(..., "%.*s%s", ...)`.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by bazsi** [comment]
@kira-syslogng retest this please;

**Review by OverOrion — APPROVED** [review]
Thank you @dkl for your refactor, it is much appreciated!

**Pull request merged**
