### PR TITLE
App parser refactor

### PR DESCRIPTION
**Pull request by bazsi**
This PR refactors the app-parser() and has the following changes:

1) it gets rid off the "*" topic, which basically allowed applications to register to _all_ topics. This does not make much sense for me now, and as far as I understand noone is using it and is undocumented. The only big user is sc4s. @rjha-splunk @ikheifets-splunk  please check if this would bother you. My assumption that it is not.

2) it creates the possibility to create app-parser() like entities by extracting an AppModelObject base class.

3) it has some refactors as well

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
@kira-syslogng: retest this please;

**Comment by ikheifets-splunk** [comment]
Thanks for notification @bazsi. We will check it asap

**Comment by ikheifets-splunk** [comment]
Hello, @bazsi !
Is it possible to download dev build (probably you building on CI)?
I think it shouldn't break anything, but anyway we need to run tests to be sure on 100%.

**Pull request closed without merging**
