### PR TITLE
missing news files

### PR DESCRIPTION
**Pull request by lbudai**
Question: what about example configs?
Do we want to include them in the news file?
(I've added example configs... sometimes it is useful for users...)

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by alltilla** [comment]
I like the higher verbosity of these entries. At some places maybe a bit much, but the approach is good IMO.

It is true, that we did not write this much in the news file before, but that can be explained with the fact, that one person did not have the time to explain all the entries this deeply.

@MrAnno, what do you think?

I am interested in others' opinion as well :)

**Comment by czanik** [comment]
I love this new effort! A lot easier to read than trying to hunt together info from commit messages and from the source code :) Thank you!

**Comment by MrAnno** [comment]
I like the idea. It's much easier and more fun to just read the news file, start a docker-image, copy-paste a versioned example config snippet and try the new feature.

If the news file gets too long because of this, we could use collapsible snippets:
<details>
  <summary>Example config, click to expand!</summary>

```
@version:3.25
@include "scl.conf"
destination d_http {
  http(
    url("http://127.0.0.1:8888")
    method("PUT")
    user_agent("syslog-ng User Agent")
    body("${ISODATE} ${MESSAGE}")
    azure-auth-header(
      workspace-id("workspace-id")
      secret("aa1a")
      method("POST")
      path("/api/logs")
      content-type("application/json")
    )
  );
};
source s_gen {
  example-msg-generator(num(1) template("Test message\n"));
};
log {
  source(s_gen);
  destination(d_http);
};
```
</details>

**Comment by lbudai** [comment]
@MrAnno : thanks for the hint... this expandable cfg look good (I've modified it : https://github.com/lbudai/syslog-ng/blob/lbudai-news-files-2020-jan/news/feature-3078.md )

**Comment by MrAnno** [comment]
@lbudai Thanks for trying it. :)

I just noticed that I've ruined the snippet, somehow line breaks have disappeared from my comment.. Sorry.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by alltilla** [comment]
The generated NEWS file looks pretty neat:

3.26.1
=======

## Highlights

<Fill this block manually from the blocks below>

## Features

 * `azure-auth-header`: Azure auth header is a plugin that generates
   authorization header for applications connecting to Azure.
   It can be used as a building block in higher level SCLs.
   Implemented as a `signal-slot` plugin.
   
   <details>
     <summary>Example config, click to expand!</summary>
   
   ```
   @version:3.25
   @include "scl.conf"
   destination d_http {
     http(
       url("http://127.0.0.1:8888")
       method("PUT")
       user_agent("syslog-ng User Agent")
       body("${ISODATE} ${MESSAGE}")
       azure-auth-header(
         workspace-id("workspace-id")
         secret("aa1a")
         method("POST")
         path("/api/logs")
         content-type("application/json")
       )
     );
   };
   source s_gen {
     example-msg-generator(num(1) template("Test message\n"));
   };
   log {
     source(s_gen);
     destination(d_http);
   };
   ```
   </details> (#3078)
 * `python`: allow specifying persist name from python.
   
   From now on users can specify a persist name template from python code.
   
   ```
   @staticmethod
   def generate_persist_name(options):
       return options["file_name"]
   ```
   
   Currently, in python destination, persist name is generated from the python class name. This can cause inconvenience if the same python class is planned to be used multiple times. For example if someone writes a PythonFileDestination, then the persist name would be python(PythonFileDestination). If a user wants to track many files, that causes persist collision, that needs to be resolved manually in configuration. After this change, module developers can specify a persist name template, that can be generate persist name uniquely (file name can be in included during generation)... Hence there is no need for users to manually resolve persist name collision. Similar example works with python source and fetcher too.
   
   Persist name from config takes precedence over `generate_persist_name`.
   
   Persist name is exposed through `self.persist_name`. (#3016)

## Bugfixes

 * `loggen, dqtool`: Fixed a crash, when writing error/debug message or relocating qfile. (#3069)

## Notes to developers

 * `NEWS.md`: From now on, for every PR that we want to include in the newsfile,
   we must create the news entry with the PR itself. See `news/README.md`. (#3066)
 * `signal-slot-connector`: a generic event handler interface for syslog-ng modules
   
   * The concept is simple:
   
   There is a SignalSlotConnector which stores Signal - Slot connections 
   Signal : Slot = 1 : N, so multiple slots can be assigned to the same Signal.
   When a Signal is emitted, the connected Slots are executed.
   Signals are string literals and each module can define its own signals.
   
   * Interface/protocol between signals and slots
   
   A macro (SIGNAL) can be used for defining signals as string literals:
   
   ```
   SIGNAL(module_name, signal, signal_parameter_type)
   ```
   
   The parameter type is for expressing a kind of contract between signals and slots.
   
   usage:
   
   ```
      #define signal_cfg_reloaded SIGNAL(config, reloaded, GlobalConfig)
   
      the generated literal:
   
      "config::signal_reloaded(GlobalConfig *)"
   ```
    
    emit passes the argument to the slots connected to the emitted signal. (#3043)
 * `http`: define HTTP signals
   
   This changeset defines the Signal interface for HTTP - with one signal at this time.
   
   What's in the changeset?
   
   * List ADT (abstract data type for list implementations) added to lib.
     * Interface:
       * append
       * foreach
       * is_empty
       * remove_all
   
   Implement the List ADT in http module with `struct curl_slist` for storing the headers.
   
   * HTTP signal(s):
   Currently only one signal is added, `header_request`.
   
   Note, that the license for `http-signals.h` is *LGPL* . (#3044)

## Other changes

 * `http`: `use-system-cert-store` functionality has been changed
   
   This option was added in order to support monolithic installations
   that ships even libcurl... But later, as it came out, it's not enough.
   What we really need is to do some autodetection regarding ca-file and ca-dir.
   In monolithic installations we enable this by default in the related SCLs. (#3086)
 * `afmongodb`: remove the support of deprecated legacy configurations (#3092)

## Credits

syslog-ng is developed as a community project, and as such it relies
on volunteers, to do the work necessarily to produce syslog-ng.

Reporting bugs, testing changes, writing code or simply providing
feedback are all important contributions, so please if you are a user
of syslog-ng, contribute.

We would like to thank the following people for their contribution:

<Fill this by the internal news file creating tool>

**Pull request merged**
