### PR TITLE
Minor compat changes for older platforms

### LINKED ISSUE #4591: Can't build on macOS
# syslog-ng 
Version of syslog-ng
3.35.1

## Platform
macOS 10.6.8

## Debug bundle
  CC       lib/transport/libsyslog_ng_la-transport-udp-socket.lo
lib/transport/transport-udp-socket.c: In function ‘_extract_dest_ip4_addr_from_cmsg’:
lib/transport/transport-udp-socket.c:65: error: ‘IP_PKTINFO’ undeclared (first use in this function)
lib/transport/transport-udp-socket.c:65: error: (Each undeclared identifier is reported only once
lib/transport/transport-udp-socket.c:65: error: for each function it appears in.)
lib/transport/transport-udp-socket.c:74: error: dereferencing pointer to incomplete type
lib/transport/transport-udp-socket.c: In function ‘log_transport_udp_setup_fd’:
lib/transport/transport-udp-socket.c:196: error: ‘IP_PKTINFO’ undeclared (first use in this function)
lib/transport/transport-udp-socket.c:201: error: ‘IPV6_RECVPKTINFO’ undeclared (first use in this function)
make[2]: *** [lib/transport/libsyslog_ng_la-transport-udp-socket.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Please help. What am I doing wrong?

### PR DESCRIPTION
**Pull request by MrAnno**
Fixes #4591

Since only minimal modifications were required to support older macOS versions, I've decided to prepare a few patches to make syslog-ng work on such systems.

### CODE REVIEW

**Comment by MrAnno** [comment]
@shgubar Could you please test this PR on macOS 10.6?

@HofiOne Could you take a look at this, please? This is related to old macOS versions.
`PKTINFO`, `clock_gettime(CLOCK_MONOTONIC)`, and `getline()` were not always available there.

Tarball:

**Comment by MrAnno** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by shgubar** [comment]
> Tarball: https://github.com/MrAnno/syslog-ng/suites/15658747065/artifacts/893805648

Doesn't exist.

**Comment by MrAnno** [comment]
Sorry, I try again:
[source-tarball.zip](https://github.com/syslog-ng/syslog-ng/files/12485670/source-tarball.3.zip)

**Comment by MrAnno** [comment]
@shgubar Yay! Thanks for your help :)

**Review by bazsi — APPROVED** [review]
This looks good to me, tests have run, user has confirmed compilation.

**Pull request merged**
