### PR TITLE
packaging: move $(slog) and related functionality to a separate package

### LINKED ISSUE #3202: secure logging should be a deb package of its own
Right now libsecure-logging.so is installed into the core package and I would rather see it as a separate package.

### PR DESCRIPTION
**Pull request by bazsi**
fixes #3202

### CODE REVIEW

**Comment by bazsi** [comment]
build packages please

**Comment by kira-syslogng** [comment]
Package Build SUCCESS

Packages are available at https://ci.syslog-ng.com/jenkins/job/kira-dbld-pull-requests/628/artifact/

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
build packages please

**Comment by kira-syslogng** [comment]
Package Build SUCCESS

Packages are available at https://ci.syslog-ng.com/jenkins/job/kira-dbld-pull-requests/630/artifact/

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
