### PR TITLE
Support Python 3.10

### PR DESCRIPTION
**Pull request by MrAnno**
This PR "adds support" for Python 3.10 by following new API constraints.

https://docs.python.org/3/whatsnew/3.10.html

@furiel

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by furiel — APPROVED** [review]
🎉

**Review by szemere — APPROVED** [review]

**Comment by alltilla** [comment]
I am having troubles testing this but that might be my personal problem.

May I ask, how did you test this locally?

**Comment by MrAnno** [comment]
I'm on Arch Linux, v3.10 is the current version of their python package.

When compiling from source, I usually configure it this way:
```
./configure --prefix=/usr --enable-shared --enable-optimizations \
    --enable-ipv6 --with-system-ffi --without-ensurepip
```

**Review by alltilla — APPROVED** [review]

**Pull request merged**
