### PR TITLE
Migrate the numeric part of basicfuncs to use GenericNumbers

### PR DESCRIPTION
**Pull request by bazsi**
This branch changes the basicfuncs/num-funcs.c plugin to use the new GenericNumber implementation instead its own local implementation for Numbers.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by Kokan — APPROVED** [review]

**Pull request merged**
